#!/bin/bash

# On a SCION topology where end to end connectivity is available, after
# restarting the dispatcher and flushing SCIOND path databases, end to end
# connectivity should still be available.

TEST_NAME="reconnecting"
TEST_TOPOLOGY="topology/Tiny.topo"

test_setup() {
    set -e
    ./scion.sh topology zkclean -c $TEST_TOPOLOGY -d -sd=go -ps=go
    ./scion.sh run
}

test_run() {
    set -e
    bin/end2end_integration -src 1-ff00:0:112 -dst 1-ff00:0:110 -attempts 5 -c tester
    docker restart $(glob_docker disp_)
    sqlite3 gen-cache/sd1-ff00_0_112.path.db "delete from segments;"
    sleep 5
    bin/end2end_integration -src 1-ff00:0:112 -dst 1-ff00:0:110 -attempts 5 -c tester
}

glob_docker() {
    [ $# -ge 1 ] || set -- '*'
    matches=
    for proc in $(./tools/dc scion config --services); do
        for spec in "$@"; do
            if glob_match $proc "$spec"; then
                matches="$matches $proc"
                break
            fi
        done
    done
    echo $matches
}

glob_match() {
    # If $1 is matched by $2, return true
    case "$1" in
        $2) return 0;;
    esac
    return 1
}

test_teardown() {
    set -e
    ./scion.sh stop
}

print_help() {
    echo
	cat <<-_EOF
	    $PROGRAM name
	        return the name of this test
	    $PROGRAM setup
	        execute only the setup phase.
	    $PROGRAM run
	        execute only the run phase.
	    $PROGRAM teardown 
	        execute only the teardown phase.
	_EOF
}

PROGRAM=`basename "$0"`
COMMAND="$1"

case "$COMMAND" in
    name)
        echo $TEST_NAME ;;
    setup|run|teardown)
        "test_$COMMAND" ;;
    *) print_help; exit 1 ;;
esac

