#!/bin/bash

# On a SCION topology where end to end connectivity is available, after
# restarting the dispatcher and flushing SCIOND path databases, end to end
# connectivity should still be available.

TEST_NAME="reconnecting"
TEST_TOPOLOGY="topology/Tiny.topo"

test_setup() {
    set -e
    ./scion.sh topology zkclean -c $TEST_TOPOLOGY -d -sd=go -ps=go
    ./scion.sh run nobuild
    ./tools/dc start tester_1-ff00_0_112 tester_1-ff00_0_110
}

test_run() {
    set -e
    bin/end2end_integration -src 1-ff00:0:112 -dst 1-ff00:0:110 -attempts 5 -d
    ./tools/dc stop scion_disp_1-ff00_0_112 scion_disp_1-ff00_0_110
    ./tools/dc start scion_disp_1-ff00_0_112 scion_disp_1-ff00_0_110
    ./tools/dc dc restart scion_bs1-ff00_0_112-1 scion_bs1-ff00_0_110-1
    sqlite3 gen-cache/sd1-ff00_0_112.path.db "delete from segments;"
    sleep 5
    bin/end2end_integration -src 1-ff00:0:112 -dst 1-ff00:0:110 -attempts 5 -d
}

test_teardown() {
    ./tools/dc down
}

print_help() {
    echo
	cat <<-_EOF
	    $PROGRAM name
	        return the name of this test
	    $PROGRAM setup
	        execute only the setup phase.
	    $PROGRAM run
	        execute only the run phase.
	    $PROGRAM teardown 
	        execute only the teardown phase.
	_EOF
}

PROGRAM=`basename "$0"`
COMMAND="$1"

case "$COMMAND" in
    name)
        echo $TEST_NAME ;;
    setup|run|teardown)
        "test_$COMMAND" ;;
    *) print_help; exit 1 ;;
esac

