// Code generated by capnpc-go. DO NOT EDIT.

package proto

import (
	math "math"
	capnp "zombiezen.com/go/capnproto2"
	text "zombiezen.com/go/capnproto2/encoding/text"
	schemas "zombiezen.com/go/capnproto2/schemas"
)

type RoutingPolicyExt struct{ capnp.Struct }

// RoutingPolicyExt_TypeID is the unique identifier for the type RoutingPolicyExt.
const RoutingPolicyExt_TypeID = 0x96c1dab83835e4f9

func NewRoutingPolicyExt(s *capnp.Segment) (RoutingPolicyExt, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return RoutingPolicyExt{st}, err
}

func NewRootRoutingPolicyExt(s *capnp.Segment) (RoutingPolicyExt, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return RoutingPolicyExt{st}, err
}

func ReadRootRoutingPolicyExt(msg *capnp.Message) (RoutingPolicyExt, error) {
	root, err := msg.RootPtr()
	return RoutingPolicyExt{root.Struct()}, err
}

func (s RoutingPolicyExt) String() string {
	str, _ := text.Marshal(0x96c1dab83835e4f9, s.Struct)
	return str
}

func (s RoutingPolicyExt) Set() bool {
	return s.Struct.Bit(0)
}

func (s RoutingPolicyExt) SetSet(v bool) {
	s.Struct.SetBit(0, v)
}

func (s RoutingPolicyExt) PolType() uint8 {
	return s.Struct.Uint8(1)
}

func (s RoutingPolicyExt) SetPolType(v uint8) {
	s.Struct.SetUint8(1, v)
}

func (s RoutingPolicyExt) IfID() uint64 {
	return s.Struct.Uint64(8)
}

func (s RoutingPolicyExt) SetIfID(v uint64) {
	s.Struct.SetUint64(8, v)
}

func (s RoutingPolicyExt) Isdases() (capnp.UInt64List, error) {
	p, err := s.Struct.Ptr(0)
	return capnp.UInt64List{List: p.List()}, err
}

func (s RoutingPolicyExt) HasIsdases() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s RoutingPolicyExt) SetIsdases(v capnp.UInt64List) error {
	return s.Struct.SetPtr(0, v.List.ToPtr())
}

// NewIsdases sets the isdases field to a newly
// allocated capnp.UInt64List, preferring placement in s's segment.
func (s RoutingPolicyExt) NewIsdases(n int32) (capnp.UInt64List, error) {
	l, err := capnp.NewUInt64List(s.Struct.Segment(), n)
	if err != nil {
		return capnp.UInt64List{}, err
	}
	err = s.Struct.SetPtr(0, l.List.ToPtr())
	return l, err
}

// RoutingPolicyExt_List is a list of RoutingPolicyExt.
type RoutingPolicyExt_List struct{ capnp.List }

// NewRoutingPolicyExt creates a new list of RoutingPolicyExt.
func NewRoutingPolicyExt_List(s *capnp.Segment, sz int32) (RoutingPolicyExt_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1}, sz)
	return RoutingPolicyExt_List{l}, err
}

func (s RoutingPolicyExt_List) At(i int) RoutingPolicyExt { return RoutingPolicyExt{s.List.Struct(i)} }

func (s RoutingPolicyExt_List) Set(i int, v RoutingPolicyExt) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s RoutingPolicyExt_List) String() string {
	str, _ := text.MarshalList(0x96c1dab83835e4f9, s.List)
	return str
}

// RoutingPolicyExt_Promise is a wrapper for a RoutingPolicyExt promised by a client call.
type RoutingPolicyExt_Promise struct{ *capnp.Pipeline }

func (p RoutingPolicyExt_Promise) Struct() (RoutingPolicyExt, error) {
	s, err := p.Pipeline.Struct()
	return RoutingPolicyExt{s}, err
}

type ISDAnnouncementExt struct{ capnp.Struct }

// ISDAnnouncementExt_TypeID is the unique identifier for the type ISDAnnouncementExt.
const ISDAnnouncementExt_TypeID = 0xc586650e812cc6a1

func NewISDAnnouncementExt(s *capnp.Segment) (ISDAnnouncementExt, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return ISDAnnouncementExt{st}, err
}

func NewRootISDAnnouncementExt(s *capnp.Segment) (ISDAnnouncementExt, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return ISDAnnouncementExt{st}, err
}

func ReadRootISDAnnouncementExt(msg *capnp.Message) (ISDAnnouncementExt, error) {
	root, err := msg.RootPtr()
	return ISDAnnouncementExt{root.Struct()}, err
}

func (s ISDAnnouncementExt) String() string {
	str, _ := text.Marshal(0xc586650e812cc6a1, s.Struct)
	return str
}

func (s ISDAnnouncementExt) Set() bool {
	return s.Struct.Bit(0)
}

func (s ISDAnnouncementExt) SetSet(v bool) {
	s.Struct.SetBit(0, v)
}

// ISDAnnouncementExt_List is a list of ISDAnnouncementExt.
type ISDAnnouncementExt_List struct{ capnp.List }

// NewISDAnnouncementExt creates a new list of ISDAnnouncementExt.
func NewISDAnnouncementExt_List(s *capnp.Segment, sz int32) (ISDAnnouncementExt_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return ISDAnnouncementExt_List{l}, err
}

func (s ISDAnnouncementExt_List) At(i int) ISDAnnouncementExt {
	return ISDAnnouncementExt{s.List.Struct(i)}
}

func (s ISDAnnouncementExt_List) Set(i int, v ISDAnnouncementExt) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s ISDAnnouncementExt_List) String() string {
	str, _ := text.MarshalList(0xc586650e812cc6a1, s.List)
	return str
}

// ISDAnnouncementExt_Promise is a wrapper for a ISDAnnouncementExt promised by a client call.
type ISDAnnouncementExt_Promise struct{ *capnp.Pipeline }

func (p ISDAnnouncementExt_Promise) Struct() (ISDAnnouncementExt, error) {
	s, err := p.Pipeline.Struct()
	return ISDAnnouncementExt{s}, err
}

type HiddenPathSegExtn struct{ capnp.Struct }

// HiddenPathSegExtn_TypeID is the unique identifier for the type HiddenPathSegExtn.
const HiddenPathSegExtn_TypeID = 0xff79b399e1e58cf3

func NewHiddenPathSegExtn(s *capnp.Segment) (HiddenPathSegExtn, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return HiddenPathSegExtn{st}, err
}

func NewRootHiddenPathSegExtn(s *capnp.Segment) (HiddenPathSegExtn, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return HiddenPathSegExtn{st}, err
}

func ReadRootHiddenPathSegExtn(msg *capnp.Message) (HiddenPathSegExtn, error) {
	root, err := msg.RootPtr()
	return HiddenPathSegExtn{root.Struct()}, err
}

func (s HiddenPathSegExtn) String() string {
	str, _ := text.Marshal(0xff79b399e1e58cf3, s.Struct)
	return str
}

func (s HiddenPathSegExtn) Set() bool {
	return s.Struct.Bit(0)
}

func (s HiddenPathSegExtn) SetSet(v bool) {
	s.Struct.SetBit(0, v)
}

// HiddenPathSegExtn_List is a list of HiddenPathSegExtn.
type HiddenPathSegExtn_List struct{ capnp.List }

// NewHiddenPathSegExtn creates a new list of HiddenPathSegExtn.
func NewHiddenPathSegExtn_List(s *capnp.Segment, sz int32) (HiddenPathSegExtn_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return HiddenPathSegExtn_List{l}, err
}

func (s HiddenPathSegExtn_List) At(i int) HiddenPathSegExtn {
	return HiddenPathSegExtn{s.List.Struct(i)}
}

func (s HiddenPathSegExtn_List) Set(i int, v HiddenPathSegExtn) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s HiddenPathSegExtn_List) String() string {
	str, _ := text.MarshalList(0xff79b399e1e58cf3, s.List)
	return str
}

// HiddenPathSegExtn_Promise is a wrapper for a HiddenPathSegExtn promised by a client call.
type HiddenPathSegExtn_Promise struct{ *capnp.Pipeline }

func (p HiddenPathSegExtn_Promise) Struct() (HiddenPathSegExtn, error) {
	s, err := p.Pipeline.Struct()
	return HiddenPathSegExtn{s}, err
}

type StaticInfoExtn struct{ capnp.Struct }

// StaticInfoExtn_TypeID is the unique identifier for the type StaticInfoExtn.
const StaticInfoExtn_TypeID = 0xdb505e3694652d57

func NewStaticInfoExtn(s *capnp.Segment) (StaticInfoExtn, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 6})
	return StaticInfoExtn{st}, err
}

func NewRootStaticInfoExtn(s *capnp.Segment) (StaticInfoExtn, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 6})
	return StaticInfoExtn{st}, err
}

func ReadRootStaticInfoExtn(msg *capnp.Message) (StaticInfoExtn, error) {
	root, err := msg.RootPtr()
	return StaticInfoExtn{root.Struct()}, err
}

func (s StaticInfoExtn) String() string {
	str, _ := text.Marshal(0xdb505e3694652d57, s.Struct)
	return str
}

func (s StaticInfoExtn) Latency() (StaticInfoExtn_LatencyInfo, error) {
	p, err := s.Struct.Ptr(0)
	return StaticInfoExtn_LatencyInfo{Struct: p.Struct()}, err
}

func (s StaticInfoExtn) HasLatency() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s StaticInfoExtn) SetLatency(v StaticInfoExtn_LatencyInfo) error {
	return s.Struct.SetPtr(0, v.Struct.ToPtr())
}

// NewLatency sets the latency field to a newly
// allocated StaticInfoExtn_LatencyInfo struct, preferring placement in s's segment.
func (s StaticInfoExtn) NewLatency() (StaticInfoExtn_LatencyInfo, error) {
	ss, err := NewStaticInfoExtn_LatencyInfo(s.Struct.Segment())
	if err != nil {
		return StaticInfoExtn_LatencyInfo{}, err
	}
	err = s.Struct.SetPtr(0, ss.Struct.ToPtr())
	return ss, err
}

func (s StaticInfoExtn) Geo() (StaticInfoExtn_GeoInfo, error) {
	p, err := s.Struct.Ptr(1)
	return StaticInfoExtn_GeoInfo{Struct: p.Struct()}, err
}

func (s StaticInfoExtn) HasGeo() bool {
	p, err := s.Struct.Ptr(1)
	return p.IsValid() || err != nil
}

func (s StaticInfoExtn) SetGeo(v StaticInfoExtn_GeoInfo) error {
	return s.Struct.SetPtr(1, v.Struct.ToPtr())
}

// NewGeo sets the geo field to a newly
// allocated StaticInfoExtn_GeoInfo struct, preferring placement in s's segment.
func (s StaticInfoExtn) NewGeo() (StaticInfoExtn_GeoInfo, error) {
	ss, err := NewStaticInfoExtn_GeoInfo(s.Struct.Segment())
	if err != nil {
		return StaticInfoExtn_GeoInfo{}, err
	}
	err = s.Struct.SetPtr(1, ss.Struct.ToPtr())
	return ss, err
}

func (s StaticInfoExtn) Linktype() (StaticInfoExtn_LinkTypeInfo, error) {
	p, err := s.Struct.Ptr(2)
	return StaticInfoExtn_LinkTypeInfo{Struct: p.Struct()}, err
}

func (s StaticInfoExtn) HasLinktype() bool {
	p, err := s.Struct.Ptr(2)
	return p.IsValid() || err != nil
}

func (s StaticInfoExtn) SetLinktype(v StaticInfoExtn_LinkTypeInfo) error {
	return s.Struct.SetPtr(2, v.Struct.ToPtr())
}

// NewLinktype sets the linktype field to a newly
// allocated StaticInfoExtn_LinkTypeInfo struct, preferring placement in s's segment.
func (s StaticInfoExtn) NewLinktype() (StaticInfoExtn_LinkTypeInfo, error) {
	ss, err := NewStaticInfoExtn_LinkTypeInfo(s.Struct.Segment())
	if err != nil {
		return StaticInfoExtn_LinkTypeInfo{}, err
	}
	err = s.Struct.SetPtr(2, ss.Struct.ToPtr())
	return ss, err
}

func (s StaticInfoExtn) Bandwidth() (StaticInfoExtn_BandwidthInfo, error) {
	p, err := s.Struct.Ptr(3)
	return StaticInfoExtn_BandwidthInfo{Struct: p.Struct()}, err
}

func (s StaticInfoExtn) HasBandwidth() bool {
	p, err := s.Struct.Ptr(3)
	return p.IsValid() || err != nil
}

func (s StaticInfoExtn) SetBandwidth(v StaticInfoExtn_BandwidthInfo) error {
	return s.Struct.SetPtr(3, v.Struct.ToPtr())
}

// NewBandwidth sets the bandwidth field to a newly
// allocated StaticInfoExtn_BandwidthInfo struct, preferring placement in s's segment.
func (s StaticInfoExtn) NewBandwidth() (StaticInfoExtn_BandwidthInfo, error) {
	ss, err := NewStaticInfoExtn_BandwidthInfo(s.Struct.Segment())
	if err != nil {
		return StaticInfoExtn_BandwidthInfo{}, err
	}
	err = s.Struct.SetPtr(3, ss.Struct.ToPtr())
	return ss, err
}

func (s StaticInfoExtn) InternalHops() (StaticInfoExtn_InternalHopsInfo, error) {
	p, err := s.Struct.Ptr(4)
	return StaticInfoExtn_InternalHopsInfo{Struct: p.Struct()}, err
}

func (s StaticInfoExtn) HasInternalHops() bool {
	p, err := s.Struct.Ptr(4)
	return p.IsValid() || err != nil
}

func (s StaticInfoExtn) SetInternalHops(v StaticInfoExtn_InternalHopsInfo) error {
	return s.Struct.SetPtr(4, v.Struct.ToPtr())
}

// NewInternalHops sets the internalHops field to a newly
// allocated StaticInfoExtn_InternalHopsInfo struct, preferring placement in s's segment.
func (s StaticInfoExtn) NewInternalHops() (StaticInfoExtn_InternalHopsInfo, error) {
	ss, err := NewStaticInfoExtn_InternalHopsInfo(s.Struct.Segment())
	if err != nil {
		return StaticInfoExtn_InternalHopsInfo{}, err
	}
	err = s.Struct.SetPtr(4, ss.Struct.ToPtr())
	return ss, err
}

func (s StaticInfoExtn) Note() (string, error) {
	p, err := s.Struct.Ptr(5)
	return p.Text(), err
}

func (s StaticInfoExtn) HasNote() bool {
	p, err := s.Struct.Ptr(5)
	return p.IsValid() || err != nil
}

func (s StaticInfoExtn) NoteBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(5)
	return p.TextBytes(), err
}

func (s StaticInfoExtn) SetNote(v string) error {
	return s.Struct.SetText(5, v)
}

// StaticInfoExtn_List is a list of StaticInfoExtn.
type StaticInfoExtn_List struct{ capnp.List }

// NewStaticInfoExtn creates a new list of StaticInfoExtn.
func NewStaticInfoExtn_List(s *capnp.Segment, sz int32) (StaticInfoExtn_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 6}, sz)
	return StaticInfoExtn_List{l}, err
}

func (s StaticInfoExtn_List) At(i int) StaticInfoExtn { return StaticInfoExtn{s.List.Struct(i)} }

func (s StaticInfoExtn_List) Set(i int, v StaticInfoExtn) error { return s.List.SetStruct(i, v.Struct) }

func (s StaticInfoExtn_List) String() string {
	str, _ := text.MarshalList(0xdb505e3694652d57, s.List)
	return str
}

// StaticInfoExtn_Promise is a wrapper for a StaticInfoExtn promised by a client call.
type StaticInfoExtn_Promise struct{ *capnp.Pipeline }

func (p StaticInfoExtn_Promise) Struct() (StaticInfoExtn, error) {
	s, err := p.Pipeline.Struct()
	return StaticInfoExtn{s}, err
}

func (p StaticInfoExtn_Promise) Latency() StaticInfoExtn_LatencyInfo_Promise {
	return StaticInfoExtn_LatencyInfo_Promise{Pipeline: p.Pipeline.GetPipeline(0)}
}

func (p StaticInfoExtn_Promise) Geo() StaticInfoExtn_GeoInfo_Promise {
	return StaticInfoExtn_GeoInfo_Promise{Pipeline: p.Pipeline.GetPipeline(1)}
}

func (p StaticInfoExtn_Promise) Linktype() StaticInfoExtn_LinkTypeInfo_Promise {
	return StaticInfoExtn_LinkTypeInfo_Promise{Pipeline: p.Pipeline.GetPipeline(2)}
}

func (p StaticInfoExtn_Promise) Bandwidth() StaticInfoExtn_BandwidthInfo_Promise {
	return StaticInfoExtn_BandwidthInfo_Promise{Pipeline: p.Pipeline.GetPipeline(3)}
}

func (p StaticInfoExtn_Promise) InternalHops() StaticInfoExtn_InternalHopsInfo_Promise {
	return StaticInfoExtn_InternalHopsInfo_Promise{Pipeline: p.Pipeline.GetPipeline(4)}
}

type StaticInfoExtn_LatencyInfo struct{ capnp.Struct }

// StaticInfoExtn_LatencyInfo_TypeID is the unique identifier for the type StaticInfoExtn_LatencyInfo.
const StaticInfoExtn_LatencyInfo_TypeID = 0x92ae8103dd768751

func NewStaticInfoExtn_LatencyInfo(s *capnp.Segment) (StaticInfoExtn_LatencyInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return StaticInfoExtn_LatencyInfo{st}, err
}

func NewRootStaticInfoExtn_LatencyInfo(s *capnp.Segment) (StaticInfoExtn_LatencyInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return StaticInfoExtn_LatencyInfo{st}, err
}

func ReadRootStaticInfoExtn_LatencyInfo(msg *capnp.Message) (StaticInfoExtn_LatencyInfo, error) {
	root, err := msg.RootPtr()
	return StaticInfoExtn_LatencyInfo{root.Struct()}, err
}

func (s StaticInfoExtn_LatencyInfo) String() string {
	str, _ := text.Marshal(0x92ae8103dd768751, s.Struct)
	return str
}

func (s StaticInfoExtn_LatencyInfo) ChildLatencies() (StaticInfoExtn_LatencyInfo_ChildLatency_List, error) {
	p, err := s.Struct.Ptr(0)
	return StaticInfoExtn_LatencyInfo_ChildLatency_List{List: p.List()}, err
}

func (s StaticInfoExtn_LatencyInfo) HasChildLatencies() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s StaticInfoExtn_LatencyInfo) SetChildLatencies(v StaticInfoExtn_LatencyInfo_ChildLatency_List) error {
	return s.Struct.SetPtr(0, v.List.ToPtr())
}

// NewChildLatencies sets the childLatencies field to a newly
// allocated StaticInfoExtn_LatencyInfo_ChildLatency_List, preferring placement in s's segment.
func (s StaticInfoExtn_LatencyInfo) NewChildLatencies(n int32) (StaticInfoExtn_LatencyInfo_ChildLatency_List, error) {
	l, err := NewStaticInfoExtn_LatencyInfo_ChildLatency_List(s.Struct.Segment(), n)
	if err != nil {
		return StaticInfoExtn_LatencyInfo_ChildLatency_List{}, err
	}
	err = s.Struct.SetPtr(0, l.List.ToPtr())
	return l, err
}

func (s StaticInfoExtn_LatencyInfo) PeeringLatencies() (StaticInfoExtn_LatencyInfo_PeerLatency_List, error) {
	p, err := s.Struct.Ptr(1)
	return StaticInfoExtn_LatencyInfo_PeerLatency_List{List: p.List()}, err
}

func (s StaticInfoExtn_LatencyInfo) HasPeeringLatencies() bool {
	p, err := s.Struct.Ptr(1)
	return p.IsValid() || err != nil
}

func (s StaticInfoExtn_LatencyInfo) SetPeeringLatencies(v StaticInfoExtn_LatencyInfo_PeerLatency_List) error {
	return s.Struct.SetPtr(1, v.List.ToPtr())
}

// NewPeeringLatencies sets the peeringLatencies field to a newly
// allocated StaticInfoExtn_LatencyInfo_PeerLatency_List, preferring placement in s's segment.
func (s StaticInfoExtn_LatencyInfo) NewPeeringLatencies(n int32) (StaticInfoExtn_LatencyInfo_PeerLatency_List, error) {
	l, err := NewStaticInfoExtn_LatencyInfo_PeerLatency_List(s.Struct.Segment(), n)
	if err != nil {
		return StaticInfoExtn_LatencyInfo_PeerLatency_List{}, err
	}
	err = s.Struct.SetPtr(1, l.List.ToPtr())
	return l, err
}

func (s StaticInfoExtn_LatencyInfo) EgressLatency() uint16 {
	return s.Struct.Uint16(0)
}

func (s StaticInfoExtn_LatencyInfo) SetEgressLatency(v uint16) {
	s.Struct.SetUint16(0, v)
}

func (s StaticInfoExtn_LatencyInfo) IngressToEgressLatency() uint16 {
	return s.Struct.Uint16(2)
}

func (s StaticInfoExtn_LatencyInfo) SetIngressToEgressLatency(v uint16) {
	s.Struct.SetUint16(2, v)
}

// StaticInfoExtn_LatencyInfo_List is a list of StaticInfoExtn_LatencyInfo.
type StaticInfoExtn_LatencyInfo_List struct{ capnp.List }

// NewStaticInfoExtn_LatencyInfo creates a new list of StaticInfoExtn_LatencyInfo.
func NewStaticInfoExtn_LatencyInfo_List(s *capnp.Segment, sz int32) (StaticInfoExtn_LatencyInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return StaticInfoExtn_LatencyInfo_List{l}, err
}

func (s StaticInfoExtn_LatencyInfo_List) At(i int) StaticInfoExtn_LatencyInfo {
	return StaticInfoExtn_LatencyInfo{s.List.Struct(i)}
}

func (s StaticInfoExtn_LatencyInfo_List) Set(i int, v StaticInfoExtn_LatencyInfo) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s StaticInfoExtn_LatencyInfo_List) String() string {
	str, _ := text.MarshalList(0x92ae8103dd768751, s.List)
	return str
}

// StaticInfoExtn_LatencyInfo_Promise is a wrapper for a StaticInfoExtn_LatencyInfo promised by a client call.
type StaticInfoExtn_LatencyInfo_Promise struct{ *capnp.Pipeline }

func (p StaticInfoExtn_LatencyInfo_Promise) Struct() (StaticInfoExtn_LatencyInfo, error) {
	s, err := p.Pipeline.Struct()
	return StaticInfoExtn_LatencyInfo{s}, err
}

type StaticInfoExtn_LatencyInfo_ChildLatency struct{ capnp.Struct }

// StaticInfoExtn_LatencyInfo_ChildLatency_TypeID is the unique identifier for the type StaticInfoExtn_LatencyInfo_ChildLatency.
const StaticInfoExtn_LatencyInfo_ChildLatency_TypeID = 0x885e742db1fb5301

func NewStaticInfoExtn_LatencyInfo_ChildLatency(s *capnp.Segment) (StaticInfoExtn_LatencyInfo_ChildLatency, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return StaticInfoExtn_LatencyInfo_ChildLatency{st}, err
}

func NewRootStaticInfoExtn_LatencyInfo_ChildLatency(s *capnp.Segment) (StaticInfoExtn_LatencyInfo_ChildLatency, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return StaticInfoExtn_LatencyInfo_ChildLatency{st}, err
}

func ReadRootStaticInfoExtn_LatencyInfo_ChildLatency(msg *capnp.Message) (StaticInfoExtn_LatencyInfo_ChildLatency, error) {
	root, err := msg.RootPtr()
	return StaticInfoExtn_LatencyInfo_ChildLatency{root.Struct()}, err
}

func (s StaticInfoExtn_LatencyInfo_ChildLatency) String() string {
	str, _ := text.Marshal(0x885e742db1fb5301, s.Struct)
	return str
}

func (s StaticInfoExtn_LatencyInfo_ChildLatency) Intra() uint16 {
	return s.Struct.Uint16(0)
}

func (s StaticInfoExtn_LatencyInfo_ChildLatency) SetIntra(v uint16) {
	s.Struct.SetUint16(0, v)
}

func (s StaticInfoExtn_LatencyInfo_ChildLatency) IfID() uint64 {
	return s.Struct.Uint64(8)
}

func (s StaticInfoExtn_LatencyInfo_ChildLatency) SetIfID(v uint64) {
	s.Struct.SetUint64(8, v)
}

// StaticInfoExtn_LatencyInfo_ChildLatency_List is a list of StaticInfoExtn_LatencyInfo_ChildLatency.
type StaticInfoExtn_LatencyInfo_ChildLatency_List struct{ capnp.List }

// NewStaticInfoExtn_LatencyInfo_ChildLatency creates a new list of StaticInfoExtn_LatencyInfo_ChildLatency.
func NewStaticInfoExtn_LatencyInfo_ChildLatency_List(s *capnp.Segment, sz int32) (StaticInfoExtn_LatencyInfo_ChildLatency_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return StaticInfoExtn_LatencyInfo_ChildLatency_List{l}, err
}

func (s StaticInfoExtn_LatencyInfo_ChildLatency_List) At(i int) StaticInfoExtn_LatencyInfo_ChildLatency {
	return StaticInfoExtn_LatencyInfo_ChildLatency{s.List.Struct(i)}
}

func (s StaticInfoExtn_LatencyInfo_ChildLatency_List) Set(i int, v StaticInfoExtn_LatencyInfo_ChildLatency) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s StaticInfoExtn_LatencyInfo_ChildLatency_List) String() string {
	str, _ := text.MarshalList(0x885e742db1fb5301, s.List)
	return str
}

// StaticInfoExtn_LatencyInfo_ChildLatency_Promise is a wrapper for a StaticInfoExtn_LatencyInfo_ChildLatency promised by a client call.
type StaticInfoExtn_LatencyInfo_ChildLatency_Promise struct{ *capnp.Pipeline }

func (p StaticInfoExtn_LatencyInfo_ChildLatency_Promise) Struct() (StaticInfoExtn_LatencyInfo_ChildLatency, error) {
	s, err := p.Pipeline.Struct()
	return StaticInfoExtn_LatencyInfo_ChildLatency{s}, err
}

type StaticInfoExtn_LatencyInfo_PeerLatency struct{ capnp.Struct }

// StaticInfoExtn_LatencyInfo_PeerLatency_TypeID is the unique identifier for the type StaticInfoExtn_LatencyInfo_PeerLatency.
const StaticInfoExtn_LatencyInfo_PeerLatency_TypeID = 0xea318fecf64edd5a

func NewStaticInfoExtn_LatencyInfo_PeerLatency(s *capnp.Segment) (StaticInfoExtn_LatencyInfo_PeerLatency, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return StaticInfoExtn_LatencyInfo_PeerLatency{st}, err
}

func NewRootStaticInfoExtn_LatencyInfo_PeerLatency(s *capnp.Segment) (StaticInfoExtn_LatencyInfo_PeerLatency, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return StaticInfoExtn_LatencyInfo_PeerLatency{st}, err
}

func ReadRootStaticInfoExtn_LatencyInfo_PeerLatency(msg *capnp.Message) (StaticInfoExtn_LatencyInfo_PeerLatency, error) {
	root, err := msg.RootPtr()
	return StaticInfoExtn_LatencyInfo_PeerLatency{root.Struct()}, err
}

func (s StaticInfoExtn_LatencyInfo_PeerLatency) String() string {
	str, _ := text.Marshal(0xea318fecf64edd5a, s.Struct)
	return str
}

func (s StaticInfoExtn_LatencyInfo_PeerLatency) Intra() uint16 {
	return s.Struct.Uint16(0)
}

func (s StaticInfoExtn_LatencyInfo_PeerLatency) SetIntra(v uint16) {
	s.Struct.SetUint16(0, v)
}

func (s StaticInfoExtn_LatencyInfo_PeerLatency) Inter() uint16 {
	return s.Struct.Uint16(2)
}

func (s StaticInfoExtn_LatencyInfo_PeerLatency) SetInter(v uint16) {
	s.Struct.SetUint16(2, v)
}

func (s StaticInfoExtn_LatencyInfo_PeerLatency) IfID() uint64 {
	return s.Struct.Uint64(8)
}

func (s StaticInfoExtn_LatencyInfo_PeerLatency) SetIfID(v uint64) {
	s.Struct.SetUint64(8, v)
}

// StaticInfoExtn_LatencyInfo_PeerLatency_List is a list of StaticInfoExtn_LatencyInfo_PeerLatency.
type StaticInfoExtn_LatencyInfo_PeerLatency_List struct{ capnp.List }

// NewStaticInfoExtn_LatencyInfo_PeerLatency creates a new list of StaticInfoExtn_LatencyInfo_PeerLatency.
func NewStaticInfoExtn_LatencyInfo_PeerLatency_List(s *capnp.Segment, sz int32) (StaticInfoExtn_LatencyInfo_PeerLatency_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return StaticInfoExtn_LatencyInfo_PeerLatency_List{l}, err
}

func (s StaticInfoExtn_LatencyInfo_PeerLatency_List) At(i int) StaticInfoExtn_LatencyInfo_PeerLatency {
	return StaticInfoExtn_LatencyInfo_PeerLatency{s.List.Struct(i)}
}

func (s StaticInfoExtn_LatencyInfo_PeerLatency_List) Set(i int, v StaticInfoExtn_LatencyInfo_PeerLatency) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s StaticInfoExtn_LatencyInfo_PeerLatency_List) String() string {
	str, _ := text.MarshalList(0xea318fecf64edd5a, s.List)
	return str
}

// StaticInfoExtn_LatencyInfo_PeerLatency_Promise is a wrapper for a StaticInfoExtn_LatencyInfo_PeerLatency promised by a client call.
type StaticInfoExtn_LatencyInfo_PeerLatency_Promise struct{ *capnp.Pipeline }

func (p StaticInfoExtn_LatencyInfo_PeerLatency_Promise) Struct() (StaticInfoExtn_LatencyInfo_PeerLatency, error) {
	s, err := p.Pipeline.Struct()
	return StaticInfoExtn_LatencyInfo_PeerLatency{s}, err
}

type StaticInfoExtn_BandwidthInfo struct{ capnp.Struct }

// StaticInfoExtn_BandwidthInfo_TypeID is the unique identifier for the type StaticInfoExtn_BandwidthInfo.
const StaticInfoExtn_BandwidthInfo_TypeID = 0xc6ff25e3b262348a

func NewStaticInfoExtn_BandwidthInfo(s *capnp.Segment) (StaticInfoExtn_BandwidthInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return StaticInfoExtn_BandwidthInfo{st}, err
}

func NewRootStaticInfoExtn_BandwidthInfo(s *capnp.Segment) (StaticInfoExtn_BandwidthInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return StaticInfoExtn_BandwidthInfo{st}, err
}

func ReadRootStaticInfoExtn_BandwidthInfo(msg *capnp.Message) (StaticInfoExtn_BandwidthInfo, error) {
	root, err := msg.RootPtr()
	return StaticInfoExtn_BandwidthInfo{root.Struct()}, err
}

func (s StaticInfoExtn_BandwidthInfo) String() string {
	str, _ := text.Marshal(0xc6ff25e3b262348a, s.Struct)
	return str
}

func (s StaticInfoExtn_BandwidthInfo) Bandwidths() (StaticInfoExtn_BandwidthInfo_InterfaceBandwidth_List, error) {
	p, err := s.Struct.Ptr(0)
	return StaticInfoExtn_BandwidthInfo_InterfaceBandwidth_List{List: p.List()}, err
}

func (s StaticInfoExtn_BandwidthInfo) HasBandwidths() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s StaticInfoExtn_BandwidthInfo) SetBandwidths(v StaticInfoExtn_BandwidthInfo_InterfaceBandwidth_List) error {
	return s.Struct.SetPtr(0, v.List.ToPtr())
}

// NewBandwidths sets the bandwidths field to a newly
// allocated StaticInfoExtn_BandwidthInfo_InterfaceBandwidth_List, preferring placement in s's segment.
func (s StaticInfoExtn_BandwidthInfo) NewBandwidths(n int32) (StaticInfoExtn_BandwidthInfo_InterfaceBandwidth_List, error) {
	l, err := NewStaticInfoExtn_BandwidthInfo_InterfaceBandwidth_List(s.Struct.Segment(), n)
	if err != nil {
		return StaticInfoExtn_BandwidthInfo_InterfaceBandwidth_List{}, err
	}
	err = s.Struct.SetPtr(0, l.List.ToPtr())
	return l, err
}

func (s StaticInfoExtn_BandwidthInfo) EgressBW() uint32 {
	return s.Struct.Uint32(0)
}

func (s StaticInfoExtn_BandwidthInfo) SetEgressBW(v uint32) {
	s.Struct.SetUint32(0, v)
}

func (s StaticInfoExtn_BandwidthInfo) IngressToEgressBW() uint32 {
	return s.Struct.Uint32(4)
}

func (s StaticInfoExtn_BandwidthInfo) SetIngressToEgressBW(v uint32) {
	s.Struct.SetUint32(4, v)
}

// StaticInfoExtn_BandwidthInfo_List is a list of StaticInfoExtn_BandwidthInfo.
type StaticInfoExtn_BandwidthInfo_List struct{ capnp.List }

// NewStaticInfoExtn_BandwidthInfo creates a new list of StaticInfoExtn_BandwidthInfo.
func NewStaticInfoExtn_BandwidthInfo_List(s *capnp.Segment, sz int32) (StaticInfoExtn_BandwidthInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return StaticInfoExtn_BandwidthInfo_List{l}, err
}

func (s StaticInfoExtn_BandwidthInfo_List) At(i int) StaticInfoExtn_BandwidthInfo {
	return StaticInfoExtn_BandwidthInfo{s.List.Struct(i)}
}

func (s StaticInfoExtn_BandwidthInfo_List) Set(i int, v StaticInfoExtn_BandwidthInfo) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s StaticInfoExtn_BandwidthInfo_List) String() string {
	str, _ := text.MarshalList(0xc6ff25e3b262348a, s.List)
	return str
}

// StaticInfoExtn_BandwidthInfo_Promise is a wrapper for a StaticInfoExtn_BandwidthInfo promised by a client call.
type StaticInfoExtn_BandwidthInfo_Promise struct{ *capnp.Pipeline }

func (p StaticInfoExtn_BandwidthInfo_Promise) Struct() (StaticInfoExtn_BandwidthInfo, error) {
	s, err := p.Pipeline.Struct()
	return StaticInfoExtn_BandwidthInfo{s}, err
}

type StaticInfoExtn_BandwidthInfo_InterfaceBandwidth struct{ capnp.Struct }

// StaticInfoExtn_BandwidthInfo_InterfaceBandwidth_TypeID is the unique identifier for the type StaticInfoExtn_BandwidthInfo_InterfaceBandwidth.
const StaticInfoExtn_BandwidthInfo_InterfaceBandwidth_TypeID = 0xd0676003f5393449

func NewStaticInfoExtn_BandwidthInfo_InterfaceBandwidth(s *capnp.Segment) (StaticInfoExtn_BandwidthInfo_InterfaceBandwidth, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return StaticInfoExtn_BandwidthInfo_InterfaceBandwidth{st}, err
}

func NewRootStaticInfoExtn_BandwidthInfo_InterfaceBandwidth(s *capnp.Segment) (StaticInfoExtn_BandwidthInfo_InterfaceBandwidth, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return StaticInfoExtn_BandwidthInfo_InterfaceBandwidth{st}, err
}

func ReadRootStaticInfoExtn_BandwidthInfo_InterfaceBandwidth(msg *capnp.Message) (StaticInfoExtn_BandwidthInfo_InterfaceBandwidth, error) {
	root, err := msg.RootPtr()
	return StaticInfoExtn_BandwidthInfo_InterfaceBandwidth{root.Struct()}, err
}

func (s StaticInfoExtn_BandwidthInfo_InterfaceBandwidth) String() string {
	str, _ := text.Marshal(0xd0676003f5393449, s.Struct)
	return str
}

func (s StaticInfoExtn_BandwidthInfo_InterfaceBandwidth) Bw() uint32 {
	return s.Struct.Uint32(0)
}

func (s StaticInfoExtn_BandwidthInfo_InterfaceBandwidth) SetBw(v uint32) {
	s.Struct.SetUint32(0, v)
}

func (s StaticInfoExtn_BandwidthInfo_InterfaceBandwidth) IfID() uint64 {
	return s.Struct.Uint64(8)
}

func (s StaticInfoExtn_BandwidthInfo_InterfaceBandwidth) SetIfID(v uint64) {
	s.Struct.SetUint64(8, v)
}

// StaticInfoExtn_BandwidthInfo_InterfaceBandwidth_List is a list of StaticInfoExtn_BandwidthInfo_InterfaceBandwidth.
type StaticInfoExtn_BandwidthInfo_InterfaceBandwidth_List struct{ capnp.List }

// NewStaticInfoExtn_BandwidthInfo_InterfaceBandwidth creates a new list of StaticInfoExtn_BandwidthInfo_InterfaceBandwidth.
func NewStaticInfoExtn_BandwidthInfo_InterfaceBandwidth_List(s *capnp.Segment, sz int32) (StaticInfoExtn_BandwidthInfo_InterfaceBandwidth_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return StaticInfoExtn_BandwidthInfo_InterfaceBandwidth_List{l}, err
}

func (s StaticInfoExtn_BandwidthInfo_InterfaceBandwidth_List) At(i int) StaticInfoExtn_BandwidthInfo_InterfaceBandwidth {
	return StaticInfoExtn_BandwidthInfo_InterfaceBandwidth{s.List.Struct(i)}
}

func (s StaticInfoExtn_BandwidthInfo_InterfaceBandwidth_List) Set(i int, v StaticInfoExtn_BandwidthInfo_InterfaceBandwidth) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s StaticInfoExtn_BandwidthInfo_InterfaceBandwidth_List) String() string {
	str, _ := text.MarshalList(0xd0676003f5393449, s.List)
	return str
}

// StaticInfoExtn_BandwidthInfo_InterfaceBandwidth_Promise is a wrapper for a StaticInfoExtn_BandwidthInfo_InterfaceBandwidth promised by a client call.
type StaticInfoExtn_BandwidthInfo_InterfaceBandwidth_Promise struct{ *capnp.Pipeline }

func (p StaticInfoExtn_BandwidthInfo_InterfaceBandwidth_Promise) Struct() (StaticInfoExtn_BandwidthInfo_InterfaceBandwidth, error) {
	s, err := p.Pipeline.Struct()
	return StaticInfoExtn_BandwidthInfo_InterfaceBandwidth{s}, err
}

type StaticInfoExtn_GeoInfo struct{ capnp.Struct }

// StaticInfoExtn_GeoInfo_TypeID is the unique identifier for the type StaticInfoExtn_GeoInfo.
const StaticInfoExtn_GeoInfo_TypeID = 0xd8c2ba2779275a74

func NewStaticInfoExtn_GeoInfo(s *capnp.Segment) (StaticInfoExtn_GeoInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StaticInfoExtn_GeoInfo{st}, err
}

func NewRootStaticInfoExtn_GeoInfo(s *capnp.Segment) (StaticInfoExtn_GeoInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StaticInfoExtn_GeoInfo{st}, err
}

func ReadRootStaticInfoExtn_GeoInfo(msg *capnp.Message) (StaticInfoExtn_GeoInfo, error) {
	root, err := msg.RootPtr()
	return StaticInfoExtn_GeoInfo{root.Struct()}, err
}

func (s StaticInfoExtn_GeoInfo) String() string {
	str, _ := text.Marshal(0xd8c2ba2779275a74, s.Struct)
	return str
}

func (s StaticInfoExtn_GeoInfo) Locations() (StaticInfoExtn_GeoInfo_Location_List, error) {
	p, err := s.Struct.Ptr(0)
	return StaticInfoExtn_GeoInfo_Location_List{List: p.List()}, err
}

func (s StaticInfoExtn_GeoInfo) HasLocations() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s StaticInfoExtn_GeoInfo) SetLocations(v StaticInfoExtn_GeoInfo_Location_List) error {
	return s.Struct.SetPtr(0, v.List.ToPtr())
}

// NewLocations sets the locations field to a newly
// allocated StaticInfoExtn_GeoInfo_Location_List, preferring placement in s's segment.
func (s StaticInfoExtn_GeoInfo) NewLocations(n int32) (StaticInfoExtn_GeoInfo_Location_List, error) {
	l, err := NewStaticInfoExtn_GeoInfo_Location_List(s.Struct.Segment(), n)
	if err != nil {
		return StaticInfoExtn_GeoInfo_Location_List{}, err
	}
	err = s.Struct.SetPtr(0, l.List.ToPtr())
	return l, err
}

// StaticInfoExtn_GeoInfo_List is a list of StaticInfoExtn_GeoInfo.
type StaticInfoExtn_GeoInfo_List struct{ capnp.List }

// NewStaticInfoExtn_GeoInfo creates a new list of StaticInfoExtn_GeoInfo.
func NewStaticInfoExtn_GeoInfo_List(s *capnp.Segment, sz int32) (StaticInfoExtn_GeoInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return StaticInfoExtn_GeoInfo_List{l}, err
}

func (s StaticInfoExtn_GeoInfo_List) At(i int) StaticInfoExtn_GeoInfo {
	return StaticInfoExtn_GeoInfo{s.List.Struct(i)}
}

func (s StaticInfoExtn_GeoInfo_List) Set(i int, v StaticInfoExtn_GeoInfo) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s StaticInfoExtn_GeoInfo_List) String() string {
	str, _ := text.MarshalList(0xd8c2ba2779275a74, s.List)
	return str
}

// StaticInfoExtn_GeoInfo_Promise is a wrapper for a StaticInfoExtn_GeoInfo promised by a client call.
type StaticInfoExtn_GeoInfo_Promise struct{ *capnp.Pipeline }

func (p StaticInfoExtn_GeoInfo_Promise) Struct() (StaticInfoExtn_GeoInfo, error) {
	s, err := p.Pipeline.Struct()
	return StaticInfoExtn_GeoInfo{s}, err
}

type StaticInfoExtn_GeoInfo_Location struct{ capnp.Struct }

// StaticInfoExtn_GeoInfo_Location_TypeID is the unique identifier for the type StaticInfoExtn_GeoInfo_Location.
const StaticInfoExtn_GeoInfo_Location_TypeID = 0xddd46d94d5f5ee47

func NewStaticInfoExtn_GeoInfo_Location(s *capnp.Segment) (StaticInfoExtn_GeoInfo_Location, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return StaticInfoExtn_GeoInfo_Location{st}, err
}

func NewRootStaticInfoExtn_GeoInfo_Location(s *capnp.Segment) (StaticInfoExtn_GeoInfo_Location, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return StaticInfoExtn_GeoInfo_Location{st}, err
}

func ReadRootStaticInfoExtn_GeoInfo_Location(msg *capnp.Message) (StaticInfoExtn_GeoInfo_Location, error) {
	root, err := msg.RootPtr()
	return StaticInfoExtn_GeoInfo_Location{root.Struct()}, err
}

func (s StaticInfoExtn_GeoInfo_Location) String() string {
	str, _ := text.Marshal(0xddd46d94d5f5ee47, s.Struct)
	return str
}

func (s StaticInfoExtn_GeoInfo_Location) GpsData() (StaticInfoExtn_GeoInfo_Location_Coordinates, error) {
	p, err := s.Struct.Ptr(0)
	return StaticInfoExtn_GeoInfo_Location_Coordinates{Struct: p.Struct()}, err
}

func (s StaticInfoExtn_GeoInfo_Location) HasGpsData() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s StaticInfoExtn_GeoInfo_Location) SetGpsData(v StaticInfoExtn_GeoInfo_Location_Coordinates) error {
	return s.Struct.SetPtr(0, v.Struct.ToPtr())
}

// NewGpsData sets the gpsData field to a newly
// allocated StaticInfoExtn_GeoInfo_Location_Coordinates struct, preferring placement in s's segment.
func (s StaticInfoExtn_GeoInfo_Location) NewGpsData() (StaticInfoExtn_GeoInfo_Location_Coordinates, error) {
	ss, err := NewStaticInfoExtn_GeoInfo_Location_Coordinates(s.Struct.Segment())
	if err != nil {
		return StaticInfoExtn_GeoInfo_Location_Coordinates{}, err
	}
	err = s.Struct.SetPtr(0, ss.Struct.ToPtr())
	return ss, err
}

func (s StaticInfoExtn_GeoInfo_Location) Interfaces() (capnp.UInt64List, error) {
	p, err := s.Struct.Ptr(1)
	return capnp.UInt64List{List: p.List()}, err
}

func (s StaticInfoExtn_GeoInfo_Location) HasInterfaces() bool {
	p, err := s.Struct.Ptr(1)
	return p.IsValid() || err != nil
}

func (s StaticInfoExtn_GeoInfo_Location) SetInterfaces(v capnp.UInt64List) error {
	return s.Struct.SetPtr(1, v.List.ToPtr())
}

// NewInterfaces sets the interfaces field to a newly
// allocated capnp.UInt64List, preferring placement in s's segment.
func (s StaticInfoExtn_GeoInfo_Location) NewInterfaces(n int32) (capnp.UInt64List, error) {
	l, err := capnp.NewUInt64List(s.Struct.Segment(), n)
	if err != nil {
		return capnp.UInt64List{}, err
	}
	err = s.Struct.SetPtr(1, l.List.ToPtr())
	return l, err
}

// StaticInfoExtn_GeoInfo_Location_List is a list of StaticInfoExtn_GeoInfo_Location.
type StaticInfoExtn_GeoInfo_Location_List struct{ capnp.List }

// NewStaticInfoExtn_GeoInfo_Location creates a new list of StaticInfoExtn_GeoInfo_Location.
func NewStaticInfoExtn_GeoInfo_Location_List(s *capnp.Segment, sz int32) (StaticInfoExtn_GeoInfo_Location_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return StaticInfoExtn_GeoInfo_Location_List{l}, err
}

func (s StaticInfoExtn_GeoInfo_Location_List) At(i int) StaticInfoExtn_GeoInfo_Location {
	return StaticInfoExtn_GeoInfo_Location{s.List.Struct(i)}
}

func (s StaticInfoExtn_GeoInfo_Location_List) Set(i int, v StaticInfoExtn_GeoInfo_Location) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s StaticInfoExtn_GeoInfo_Location_List) String() string {
	str, _ := text.MarshalList(0xddd46d94d5f5ee47, s.List)
	return str
}

// StaticInfoExtn_GeoInfo_Location_Promise is a wrapper for a StaticInfoExtn_GeoInfo_Location promised by a client call.
type StaticInfoExtn_GeoInfo_Location_Promise struct{ *capnp.Pipeline }

func (p StaticInfoExtn_GeoInfo_Location_Promise) Struct() (StaticInfoExtn_GeoInfo_Location, error) {
	s, err := p.Pipeline.Struct()
	return StaticInfoExtn_GeoInfo_Location{s}, err
}

func (p StaticInfoExtn_GeoInfo_Location_Promise) GpsData() StaticInfoExtn_GeoInfo_Location_Coordinates_Promise {
	return StaticInfoExtn_GeoInfo_Location_Coordinates_Promise{Pipeline: p.Pipeline.GetPipeline(0)}
}

type StaticInfoExtn_GeoInfo_Location_Coordinates struct{ capnp.Struct }

// StaticInfoExtn_GeoInfo_Location_Coordinates_TypeID is the unique identifier for the type StaticInfoExtn_GeoInfo_Location_Coordinates.
const StaticInfoExtn_GeoInfo_Location_Coordinates_TypeID = 0xc7a6dc5be99844b2

func NewStaticInfoExtn_GeoInfo_Location_Coordinates(s *capnp.Segment) (StaticInfoExtn_GeoInfo_Location_Coordinates, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return StaticInfoExtn_GeoInfo_Location_Coordinates{st}, err
}

func NewRootStaticInfoExtn_GeoInfo_Location_Coordinates(s *capnp.Segment) (StaticInfoExtn_GeoInfo_Location_Coordinates, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return StaticInfoExtn_GeoInfo_Location_Coordinates{st}, err
}

func ReadRootStaticInfoExtn_GeoInfo_Location_Coordinates(msg *capnp.Message) (StaticInfoExtn_GeoInfo_Location_Coordinates, error) {
	root, err := msg.RootPtr()
	return StaticInfoExtn_GeoInfo_Location_Coordinates{root.Struct()}, err
}

func (s StaticInfoExtn_GeoInfo_Location_Coordinates) String() string {
	str, _ := text.Marshal(0xc7a6dc5be99844b2, s.Struct)
	return str
}

func (s StaticInfoExtn_GeoInfo_Location_Coordinates) Latitude() float32 {
	return math.Float32frombits(s.Struct.Uint32(0))
}

func (s StaticInfoExtn_GeoInfo_Location_Coordinates) SetLatitude(v float32) {
	s.Struct.SetUint32(0, math.Float32bits(v))
}

func (s StaticInfoExtn_GeoInfo_Location_Coordinates) Longitude() float32 {
	return math.Float32frombits(s.Struct.Uint32(4))
}

func (s StaticInfoExtn_GeoInfo_Location_Coordinates) SetLongitude(v float32) {
	s.Struct.SetUint32(4, math.Float32bits(v))
}

func (s StaticInfoExtn_GeoInfo_Location_Coordinates) Address() (string, error) {
	p, err := s.Struct.Ptr(0)
	return p.Text(), err
}

func (s StaticInfoExtn_GeoInfo_Location_Coordinates) HasAddress() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s StaticInfoExtn_GeoInfo_Location_Coordinates) AddressBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return p.TextBytes(), err
}

func (s StaticInfoExtn_GeoInfo_Location_Coordinates) SetAddress(v string) error {
	return s.Struct.SetText(0, v)
}

// StaticInfoExtn_GeoInfo_Location_Coordinates_List is a list of StaticInfoExtn_GeoInfo_Location_Coordinates.
type StaticInfoExtn_GeoInfo_Location_Coordinates_List struct{ capnp.List }

// NewStaticInfoExtn_GeoInfo_Location_Coordinates creates a new list of StaticInfoExtn_GeoInfo_Location_Coordinates.
func NewStaticInfoExtn_GeoInfo_Location_Coordinates_List(s *capnp.Segment, sz int32) (StaticInfoExtn_GeoInfo_Location_Coordinates_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return StaticInfoExtn_GeoInfo_Location_Coordinates_List{l}, err
}

func (s StaticInfoExtn_GeoInfo_Location_Coordinates_List) At(i int) StaticInfoExtn_GeoInfo_Location_Coordinates {
	return StaticInfoExtn_GeoInfo_Location_Coordinates{s.List.Struct(i)}
}

func (s StaticInfoExtn_GeoInfo_Location_Coordinates_List) Set(i int, v StaticInfoExtn_GeoInfo_Location_Coordinates) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s StaticInfoExtn_GeoInfo_Location_Coordinates_List) String() string {
	str, _ := text.MarshalList(0xc7a6dc5be99844b2, s.List)
	return str
}

// StaticInfoExtn_GeoInfo_Location_Coordinates_Promise is a wrapper for a StaticInfoExtn_GeoInfo_Location_Coordinates promised by a client call.
type StaticInfoExtn_GeoInfo_Location_Coordinates_Promise struct{ *capnp.Pipeline }

func (p StaticInfoExtn_GeoInfo_Location_Coordinates_Promise) Struct() (StaticInfoExtn_GeoInfo_Location_Coordinates, error) {
	s, err := p.Pipeline.Struct()
	return StaticInfoExtn_GeoInfo_Location_Coordinates{s}, err
}

type StaticInfoExtn_LinkTypeInfo struct{ capnp.Struct }

// StaticInfoExtn_LinkTypeInfo_TypeID is the unique identifier for the type StaticInfoExtn_LinkTypeInfo.
const StaticInfoExtn_LinkTypeInfo_TypeID = 0xb4b9b8f861554bad

func NewStaticInfoExtn_LinkTypeInfo(s *capnp.Segment) (StaticInfoExtn_LinkTypeInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return StaticInfoExtn_LinkTypeInfo{st}, err
}

func NewRootStaticInfoExtn_LinkTypeInfo(s *capnp.Segment) (StaticInfoExtn_LinkTypeInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return StaticInfoExtn_LinkTypeInfo{st}, err
}

func ReadRootStaticInfoExtn_LinkTypeInfo(msg *capnp.Message) (StaticInfoExtn_LinkTypeInfo, error) {
	root, err := msg.RootPtr()
	return StaticInfoExtn_LinkTypeInfo{root.Struct()}, err
}

func (s StaticInfoExtn_LinkTypeInfo) String() string {
	str, _ := text.Marshal(0xb4b9b8f861554bad, s.Struct)
	return str
}

func (s StaticInfoExtn_LinkTypeInfo) PeeringLinks() (StaticInfoExtn_LinkTypeInfo_InterfaceLinkType_List, error) {
	p, err := s.Struct.Ptr(0)
	return StaticInfoExtn_LinkTypeInfo_InterfaceLinkType_List{List: p.List()}, err
}

func (s StaticInfoExtn_LinkTypeInfo) HasPeeringLinks() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s StaticInfoExtn_LinkTypeInfo) SetPeeringLinks(v StaticInfoExtn_LinkTypeInfo_InterfaceLinkType_List) error {
	return s.Struct.SetPtr(0, v.List.ToPtr())
}

// NewPeeringLinks sets the peeringLinks field to a newly
// allocated StaticInfoExtn_LinkTypeInfo_InterfaceLinkType_List, preferring placement in s's segment.
func (s StaticInfoExtn_LinkTypeInfo) NewPeeringLinks(n int32) (StaticInfoExtn_LinkTypeInfo_InterfaceLinkType_List, error) {
	l, err := NewStaticInfoExtn_LinkTypeInfo_InterfaceLinkType_List(s.Struct.Segment(), n)
	if err != nil {
		return StaticInfoExtn_LinkTypeInfo_InterfaceLinkType_List{}, err
	}
	err = s.Struct.SetPtr(0, l.List.ToPtr())
	return l, err
}

func (s StaticInfoExtn_LinkTypeInfo) EgressLinkType() StaticInfoExtn_LinkTypeInfo_LinkType {
	return StaticInfoExtn_LinkTypeInfo_LinkType(s.Struct.Uint16(0))
}

func (s StaticInfoExtn_LinkTypeInfo) SetEgressLinkType(v StaticInfoExtn_LinkTypeInfo_LinkType) {
	s.Struct.SetUint16(0, uint16(v))
}

// StaticInfoExtn_LinkTypeInfo_List is a list of StaticInfoExtn_LinkTypeInfo.
type StaticInfoExtn_LinkTypeInfo_List struct{ capnp.List }

// NewStaticInfoExtn_LinkTypeInfo creates a new list of StaticInfoExtn_LinkTypeInfo.
func NewStaticInfoExtn_LinkTypeInfo_List(s *capnp.Segment, sz int32) (StaticInfoExtn_LinkTypeInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return StaticInfoExtn_LinkTypeInfo_List{l}, err
}

func (s StaticInfoExtn_LinkTypeInfo_List) At(i int) StaticInfoExtn_LinkTypeInfo {
	return StaticInfoExtn_LinkTypeInfo{s.List.Struct(i)}
}

func (s StaticInfoExtn_LinkTypeInfo_List) Set(i int, v StaticInfoExtn_LinkTypeInfo) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s StaticInfoExtn_LinkTypeInfo_List) String() string {
	str, _ := text.MarshalList(0xb4b9b8f861554bad, s.List)
	return str
}

// StaticInfoExtn_LinkTypeInfo_Promise is a wrapper for a StaticInfoExtn_LinkTypeInfo promised by a client call.
type StaticInfoExtn_LinkTypeInfo_Promise struct{ *capnp.Pipeline }

func (p StaticInfoExtn_LinkTypeInfo_Promise) Struct() (StaticInfoExtn_LinkTypeInfo, error) {
	s, err := p.Pipeline.Struct()
	return StaticInfoExtn_LinkTypeInfo{s}, err
}

type StaticInfoExtn_LinkTypeInfo_LinkType uint16

// StaticInfoExtn_LinkTypeInfo_LinkType_TypeID is the unique identifier for the type StaticInfoExtn_LinkTypeInfo_LinkType.
const StaticInfoExtn_LinkTypeInfo_LinkType_TypeID = 0xb83b1b1b174f8aec

// Values of StaticInfoExtn_LinkTypeInfo_LinkType.
const (
	StaticInfoExtn_LinkTypeInfo_LinkType_unset    StaticInfoExtn_LinkTypeInfo_LinkType = 0
	StaticInfoExtn_LinkTypeInfo_LinkType_direct   StaticInfoExtn_LinkTypeInfo_LinkType = 1
	StaticInfoExtn_LinkTypeInfo_LinkType_multiHop StaticInfoExtn_LinkTypeInfo_LinkType = 2
	StaticInfoExtn_LinkTypeInfo_LinkType_openNet  StaticInfoExtn_LinkTypeInfo_LinkType = 3
)

// String returns the enum's constant name.
func (c StaticInfoExtn_LinkTypeInfo_LinkType) String() string {
	switch c {
	case StaticInfoExtn_LinkTypeInfo_LinkType_unset:
		return "unset"
	case StaticInfoExtn_LinkTypeInfo_LinkType_direct:
		return "direct"
	case StaticInfoExtn_LinkTypeInfo_LinkType_multiHop:
		return "multiHop"
	case StaticInfoExtn_LinkTypeInfo_LinkType_openNet:
		return "openNet"

	default:
		return ""
	}
}

// StaticInfoExtn_LinkTypeInfo_LinkTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func StaticInfoExtn_LinkTypeInfo_LinkTypeFromString(c string) StaticInfoExtn_LinkTypeInfo_LinkType {
	switch c {
	case "unset":
		return StaticInfoExtn_LinkTypeInfo_LinkType_unset
	case "direct":
		return StaticInfoExtn_LinkTypeInfo_LinkType_direct
	case "multiHop":
		return StaticInfoExtn_LinkTypeInfo_LinkType_multiHop
	case "openNet":
		return StaticInfoExtn_LinkTypeInfo_LinkType_openNet

	default:
		return 0
	}
}

type StaticInfoExtn_LinkTypeInfo_LinkType_List struct{ capnp.List }

func NewStaticInfoExtn_LinkTypeInfo_LinkType_List(s *capnp.Segment, sz int32) (StaticInfoExtn_LinkTypeInfo_LinkType_List, error) {
	l, err := capnp.NewUInt16List(s, sz)
	return StaticInfoExtn_LinkTypeInfo_LinkType_List{l.List}, err
}

func (l StaticInfoExtn_LinkTypeInfo_LinkType_List) At(i int) StaticInfoExtn_LinkTypeInfo_LinkType {
	ul := capnp.UInt16List{List: l.List}
	return StaticInfoExtn_LinkTypeInfo_LinkType(ul.At(i))
}

func (l StaticInfoExtn_LinkTypeInfo_LinkType_List) Set(i int, v StaticInfoExtn_LinkTypeInfo_LinkType) {
	ul := capnp.UInt16List{List: l.List}
	ul.Set(i, uint16(v))
}

type StaticInfoExtn_LinkTypeInfo_InterfaceLinkType struct{ capnp.Struct }

// StaticInfoExtn_LinkTypeInfo_InterfaceLinkType_TypeID is the unique identifier for the type StaticInfoExtn_LinkTypeInfo_InterfaceLinkType.
const StaticInfoExtn_LinkTypeInfo_InterfaceLinkType_TypeID = 0x9ab6cd3b4d0d17c7

func NewStaticInfoExtn_LinkTypeInfo_InterfaceLinkType(s *capnp.Segment) (StaticInfoExtn_LinkTypeInfo_InterfaceLinkType, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return StaticInfoExtn_LinkTypeInfo_InterfaceLinkType{st}, err
}

func NewRootStaticInfoExtn_LinkTypeInfo_InterfaceLinkType(s *capnp.Segment) (StaticInfoExtn_LinkTypeInfo_InterfaceLinkType, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return StaticInfoExtn_LinkTypeInfo_InterfaceLinkType{st}, err
}

func ReadRootStaticInfoExtn_LinkTypeInfo_InterfaceLinkType(msg *capnp.Message) (StaticInfoExtn_LinkTypeInfo_InterfaceLinkType, error) {
	root, err := msg.RootPtr()
	return StaticInfoExtn_LinkTypeInfo_InterfaceLinkType{root.Struct()}, err
}

func (s StaticInfoExtn_LinkTypeInfo_InterfaceLinkType) String() string {
	str, _ := text.Marshal(0x9ab6cd3b4d0d17c7, s.Struct)
	return str
}

func (s StaticInfoExtn_LinkTypeInfo_InterfaceLinkType) IfID() uint64 {
	return s.Struct.Uint64(0)
}

func (s StaticInfoExtn_LinkTypeInfo_InterfaceLinkType) SetIfID(v uint64) {
	s.Struct.SetUint64(0, v)
}

func (s StaticInfoExtn_LinkTypeInfo_InterfaceLinkType) LinkType() StaticInfoExtn_LinkTypeInfo_LinkType {
	return StaticInfoExtn_LinkTypeInfo_LinkType(s.Struct.Uint16(8))
}

func (s StaticInfoExtn_LinkTypeInfo_InterfaceLinkType) SetLinkType(v StaticInfoExtn_LinkTypeInfo_LinkType) {
	s.Struct.SetUint16(8, uint16(v))
}

// StaticInfoExtn_LinkTypeInfo_InterfaceLinkType_List is a list of StaticInfoExtn_LinkTypeInfo_InterfaceLinkType.
type StaticInfoExtn_LinkTypeInfo_InterfaceLinkType_List struct{ capnp.List }

// NewStaticInfoExtn_LinkTypeInfo_InterfaceLinkType creates a new list of StaticInfoExtn_LinkTypeInfo_InterfaceLinkType.
func NewStaticInfoExtn_LinkTypeInfo_InterfaceLinkType_List(s *capnp.Segment, sz int32) (StaticInfoExtn_LinkTypeInfo_InterfaceLinkType_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return StaticInfoExtn_LinkTypeInfo_InterfaceLinkType_List{l}, err
}

func (s StaticInfoExtn_LinkTypeInfo_InterfaceLinkType_List) At(i int) StaticInfoExtn_LinkTypeInfo_InterfaceLinkType {
	return StaticInfoExtn_LinkTypeInfo_InterfaceLinkType{s.List.Struct(i)}
}

func (s StaticInfoExtn_LinkTypeInfo_InterfaceLinkType_List) Set(i int, v StaticInfoExtn_LinkTypeInfo_InterfaceLinkType) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s StaticInfoExtn_LinkTypeInfo_InterfaceLinkType_List) String() string {
	str, _ := text.MarshalList(0x9ab6cd3b4d0d17c7, s.List)
	return str
}

// StaticInfoExtn_LinkTypeInfo_InterfaceLinkType_Promise is a wrapper for a StaticInfoExtn_LinkTypeInfo_InterfaceLinkType promised by a client call.
type StaticInfoExtn_LinkTypeInfo_InterfaceLinkType_Promise struct{ *capnp.Pipeline }

func (p StaticInfoExtn_LinkTypeInfo_InterfaceLinkType_Promise) Struct() (StaticInfoExtn_LinkTypeInfo_InterfaceLinkType, error) {
	s, err := p.Pipeline.Struct()
	return StaticInfoExtn_LinkTypeInfo_InterfaceLinkType{s}, err
}

type StaticInfoExtn_InternalHopsInfo struct{ capnp.Struct }

// StaticInfoExtn_InternalHopsInfo_TypeID is the unique identifier for the type StaticInfoExtn_InternalHopsInfo.
const StaticInfoExtn_InternalHopsInfo_TypeID = 0xeb06bcceba87669a

func NewStaticInfoExtn_InternalHopsInfo(s *capnp.Segment) (StaticInfoExtn_InternalHopsInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return StaticInfoExtn_InternalHopsInfo{st}, err
}

func NewRootStaticInfoExtn_InternalHopsInfo(s *capnp.Segment) (StaticInfoExtn_InternalHopsInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return StaticInfoExtn_InternalHopsInfo{st}, err
}

func ReadRootStaticInfoExtn_InternalHopsInfo(msg *capnp.Message) (StaticInfoExtn_InternalHopsInfo, error) {
	root, err := msg.RootPtr()
	return StaticInfoExtn_InternalHopsInfo{root.Struct()}, err
}

func (s StaticInfoExtn_InternalHopsInfo) String() string {
	str, _ := text.Marshal(0xeb06bcceba87669a, s.Struct)
	return str
}

func (s StaticInfoExtn_InternalHopsInfo) InterfaceHops() (StaticInfoExtn_InternalHopsInfo_InterfaceHops_List, error) {
	p, err := s.Struct.Ptr(0)
	return StaticInfoExtn_InternalHopsInfo_InterfaceHops_List{List: p.List()}, err
}

func (s StaticInfoExtn_InternalHopsInfo) HasInterfaceHops() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s StaticInfoExtn_InternalHopsInfo) SetInterfaceHops(v StaticInfoExtn_InternalHopsInfo_InterfaceHops_List) error {
	return s.Struct.SetPtr(0, v.List.ToPtr())
}

// NewInterfaceHops sets the interfaceHops field to a newly
// allocated StaticInfoExtn_InternalHopsInfo_InterfaceHops_List, preferring placement in s's segment.
func (s StaticInfoExtn_InternalHopsInfo) NewInterfaceHops(n int32) (StaticInfoExtn_InternalHopsInfo_InterfaceHops_List, error) {
	l, err := NewStaticInfoExtn_InternalHopsInfo_InterfaceHops_List(s.Struct.Segment(), n)
	if err != nil {
		return StaticInfoExtn_InternalHopsInfo_InterfaceHops_List{}, err
	}
	err = s.Struct.SetPtr(0, l.List.ToPtr())
	return l, err
}

func (s StaticInfoExtn_InternalHopsInfo) InToOutHops() uint8 {
	return s.Struct.Uint8(0)
}

func (s StaticInfoExtn_InternalHopsInfo) SetInToOutHops(v uint8) {
	s.Struct.SetUint8(0, v)
}

// StaticInfoExtn_InternalHopsInfo_List is a list of StaticInfoExtn_InternalHopsInfo.
type StaticInfoExtn_InternalHopsInfo_List struct{ capnp.List }

// NewStaticInfoExtn_InternalHopsInfo creates a new list of StaticInfoExtn_InternalHopsInfo.
func NewStaticInfoExtn_InternalHopsInfo_List(s *capnp.Segment, sz int32) (StaticInfoExtn_InternalHopsInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return StaticInfoExtn_InternalHopsInfo_List{l}, err
}

func (s StaticInfoExtn_InternalHopsInfo_List) At(i int) StaticInfoExtn_InternalHopsInfo {
	return StaticInfoExtn_InternalHopsInfo{s.List.Struct(i)}
}

func (s StaticInfoExtn_InternalHopsInfo_List) Set(i int, v StaticInfoExtn_InternalHopsInfo) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s StaticInfoExtn_InternalHopsInfo_List) String() string {
	str, _ := text.MarshalList(0xeb06bcceba87669a, s.List)
	return str
}

// StaticInfoExtn_InternalHopsInfo_Promise is a wrapper for a StaticInfoExtn_InternalHopsInfo promised by a client call.
type StaticInfoExtn_InternalHopsInfo_Promise struct{ *capnp.Pipeline }

func (p StaticInfoExtn_InternalHopsInfo_Promise) Struct() (StaticInfoExtn_InternalHopsInfo, error) {
	s, err := p.Pipeline.Struct()
	return StaticInfoExtn_InternalHopsInfo{s}, err
}

type StaticInfoExtn_InternalHopsInfo_InterfaceHops struct{ capnp.Struct }

// StaticInfoExtn_InternalHopsInfo_InterfaceHops_TypeID is the unique identifier for the type StaticInfoExtn_InternalHopsInfo_InterfaceHops.
const StaticInfoExtn_InternalHopsInfo_InterfaceHops_TypeID = 0xcd7606ede67cf290

func NewStaticInfoExtn_InternalHopsInfo_InterfaceHops(s *capnp.Segment) (StaticInfoExtn_InternalHopsInfo_InterfaceHops, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return StaticInfoExtn_InternalHopsInfo_InterfaceHops{st}, err
}

func NewRootStaticInfoExtn_InternalHopsInfo_InterfaceHops(s *capnp.Segment) (StaticInfoExtn_InternalHopsInfo_InterfaceHops, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return StaticInfoExtn_InternalHopsInfo_InterfaceHops{st}, err
}

func ReadRootStaticInfoExtn_InternalHopsInfo_InterfaceHops(msg *capnp.Message) (StaticInfoExtn_InternalHopsInfo_InterfaceHops, error) {
	root, err := msg.RootPtr()
	return StaticInfoExtn_InternalHopsInfo_InterfaceHops{root.Struct()}, err
}

func (s StaticInfoExtn_InternalHopsInfo_InterfaceHops) String() string {
	str, _ := text.Marshal(0xcd7606ede67cf290, s.Struct)
	return str
}

func (s StaticInfoExtn_InternalHopsInfo_InterfaceHops) Hops() uint8 {
	return s.Struct.Uint8(0)
}

func (s StaticInfoExtn_InternalHopsInfo_InterfaceHops) SetHops(v uint8) {
	s.Struct.SetUint8(0, v)
}

func (s StaticInfoExtn_InternalHopsInfo_InterfaceHops) IfID() uint64 {
	return s.Struct.Uint64(8)
}

func (s StaticInfoExtn_InternalHopsInfo_InterfaceHops) SetIfID(v uint64) {
	s.Struct.SetUint64(8, v)
}

// StaticInfoExtn_InternalHopsInfo_InterfaceHops_List is a list of StaticInfoExtn_InternalHopsInfo_InterfaceHops.
type StaticInfoExtn_InternalHopsInfo_InterfaceHops_List struct{ capnp.List }

// NewStaticInfoExtn_InternalHopsInfo_InterfaceHops creates a new list of StaticInfoExtn_InternalHopsInfo_InterfaceHops.
func NewStaticInfoExtn_InternalHopsInfo_InterfaceHops_List(s *capnp.Segment, sz int32) (StaticInfoExtn_InternalHopsInfo_InterfaceHops_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return StaticInfoExtn_InternalHopsInfo_InterfaceHops_List{l}, err
}

func (s StaticInfoExtn_InternalHopsInfo_InterfaceHops_List) At(i int) StaticInfoExtn_InternalHopsInfo_InterfaceHops {
	return StaticInfoExtn_InternalHopsInfo_InterfaceHops{s.List.Struct(i)}
}

func (s StaticInfoExtn_InternalHopsInfo_InterfaceHops_List) Set(i int, v StaticInfoExtn_InternalHopsInfo_InterfaceHops) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s StaticInfoExtn_InternalHopsInfo_InterfaceHops_List) String() string {
	str, _ := text.MarshalList(0xcd7606ede67cf290, s.List)
	return str
}

// StaticInfoExtn_InternalHopsInfo_InterfaceHops_Promise is a wrapper for a StaticInfoExtn_InternalHopsInfo_InterfaceHops promised by a client call.
type StaticInfoExtn_InternalHopsInfo_InterfaceHops_Promise struct{ *capnp.Pipeline }

func (p StaticInfoExtn_InternalHopsInfo_InterfaceHops_Promise) Struct() (StaticInfoExtn_InternalHopsInfo_InterfaceHops, error) {
	s, err := p.Pipeline.Struct()
	return StaticInfoExtn_InternalHopsInfo_InterfaceHops{s}, err
}

const schema_e6c88f91b6a1209e = "x\xda\x9cWm\x8cTW\x19~\x9fs\xe6\xce\x07\xcc" +
	"2s\xbd\xdb\xe0\xda\xb4S\x8cJ\xa5\x80-\xa0\xa9\xed" +
	"\x8f-\xd3\xddtw]\xda=@\xb3\xba\xd6\xca\x9d\x99" +
	"\xb33\x97\xce\xde;\x9d\xb9[XB\xb2!\xb1V\x88" +
	"\xa4\x96\xa0\xa1$5\xc5X\xa3\x89U\x8b\xa4\xa1\xa4?" +
	"\xc4\xc4V\x7f`4\x91D\xab\xc4\x18mM\xb1\xf8\xa3" +
	"\x06c5\xe6\x9as\xbfw\x19\xba\xc4\x9f\xf3\x9e\xf7\x9e" +
	"\xf3\xbc\xcf\xfb\xbc\x1fs\xe7m\x99\xfb\xd8]\xda\x1f5" +
	"\"1\xa2e=\xec\xfa\xcfK\x9b\xdcG\xbfBb\x03" +
	"\x98'\x9ez\xe2\x12?\xf4\x83c\x94\xc9\x11m\xbd\xc8" +
	"\xce\xc1\xb8\xc2rD\xc6\xdbl\x1f!9\x16\xb7\x02\xde" +
	"\xf4&y\xfcS\x8fN\xfd\x9e4\xe5\xb2u\x94\xef\x84" +
	"\xf19\xbe\x9e\xc8\x98\xe7\x7f%x\xef\xfd\xe5\x93w\x9f" +
	"}\xe3\xfc7H\x94\xc0\xbco\xdev\xea\xe5g\x9e\xfe" +
	"\xf9[\xa4Ay\x1f\xca0\x18G\xd53\xc6\xe1\x8c\xf2" +
	"~}\xed\xc0\x8e{/\xbc|\x92\xc4\x1d`\xde\x8b\x9f" +
	"y\xd8\xfc\xd7\xd9W\xce\x04@\xe6\xb4\xcb0\x0ek\xca" +
	"\xf9IM\x01\x89\x8f\x97\x01\xf1\xaf~S\x9b\x81\xf1\x9e" +
	"\xa6\x80\x0ce\x95\xf7;G\x1eZ{\xf3\xcd\xf7\x9e%" +
	"\xfd\x8e\xd4\xcd\x84\xadG\xb3\xdf\x82\xf1BV\xdd{*" +
	"\xdb$x\xa7^\xdbxh\x8d\xfc\xf2\xcf\x14d$\x90" +
	"}\x10\xbf\xc8~\x00\xc6\xef|\xe7\x8b\xd9a\x82wd" +
	"[\xed\xf4\x9f?\xea\xbd\xd6\x17\xc4\xd5l\x0dF!\xb7" +
	"V\x81\xc8\xfd\x90\xe0\x9d\x1e9\xf1\xf6\xe7\xff\xf0\x9d\xd7" +
	"I|\x02\xf0\x1e\xf8\xfb\xd5\x8b\xc7\xe7~s)\xf4\xfe" +
	"u\xee\x0d\x18Wr>\xd3\xbe\xf7\xd7\xde=\xf8\xd6\x95" +
	"\xec\x13\x17\x947\xf3N\xce>u\xee\x97\xaff\xff\x16" +
	"\x009\x9c\xbf\x0c\xe3\x85\xbc\x8f:\xaf\xe2\x1b\xdf\xf6\xe9" +
	"\xab|O\xf3W$6\x82%\xb0|\xe7\xff\xe6\xff\x0d" +
	"c\xa8\xa0\x9co*(gwf\xfd\xc2\xfas?\xfd" +
	"-\xe9\xb7^\x03\xfa\xf1\xc2\x16\x18\x87\x0a\x0a\xf4\xd1\x82" +
	"\x0a1>\xd7K):4\x9f\x84\xf3\x85w\x8d\x0b\x85" +
	"i\xa2\xadC\xab\xa6A\xa9\x98\xf4\x8f\xa5\x9e\x09\xc4\xf1" +
	"\xf8\xea\x030\x9e\\\xadn~f\xb5\x821s\xe9\xc1" +
	"\x7f\xbe\xf3\xf4]\x97\xfb\xe9\x0e\xc5\xd30\x86\x8a>\xe6" +
	"\xa2b#\x8e\xbf\x1f\xd3/\x16\x0f\xc08_TW_" +
	"(\xaa\xab\xff\xf1\xd57\xff\xf4\xec\x8f\x17\xbc~I\xdc" +
	">\xb0\x0a\x86\x18PW\xef\x18P\x11\x9a\xbd\xb9/\xca" +
	"\xfdnO\xdb\\7;v\xe7\x9e]\xae\xe9Z\xf5q" +
	"{\xd6\x19\xdd\xef\xda\x9b'MW\xda\xf5\x05\xf5{\xf3" +
	"\xfd-\xab\xdd\x98\x1c\x0e,S\x80\xc8\xf3\x0cQ\x06D" +
	"\xfa\xc7\xb7\x10\x89\x8fp\x88;\x19t`\x10\xca\xb8i" +
	"\x03\x91\xb8\x9dClc\xa8X\xb6\xdb5\x91#\x86\x1c" +
	"\xa1d\xcd\x8e\x8f\xa0@\x0c\x85\x14\x84\xccJ\x10\xe0\x88" +
	"<\x90\x94\xac^\xd8\x9b\xf0\xa8\x17j^\x80\xd0t\xa9" +
	"\xa4\xbe\xf0\xa6\xa4\xec\xaa\xaf)g\xd7\x17D9Fk" +
	"\x1e \x12{8\xc4\xc1\x14\xda\x85#D\xe2 \x878" +
	"\xc1\x006\x08F\xa4\x7f\xbdK$\x8es\x88\xe7\x19t" +
	"\x8eAp\"\xfd\xb9sD\xe2y\x0e\xf1}\x06\xaf\x1e" +
	"\xbd8,\xed\xba%{XC\x98\xe2@9AIP" +
	"F\xaf#e\xd7\xb2\x9b\x93\xf0\xc3\xb1d\x8f(q\x8e" +
	"\xa3\x08\x9de\xb3+{\xbdI\x93*~\xec\x11o\x9e" +
	"e\xfb\x07\xbb\xe1\x8c\x06\x1ea6b\x87\x88K\x1er" +
	"\xb9\xd3\x99w-\xbb9\xe5\xb4\xad\xfa\xc2\xe8~\x97T" +
	"\xdeRL|\x98H<\xc2!Z)&d5\xa4\xa7" +
	"\xcd\xa03\x04TX*\x99\x0d\x0e\xd1a\x00\x0f\x98\x98" +
	"S\x8e-\x0e\xf1%\x86\\O\xba\x001\x80\xb0\xd8q" +
	"\xda\xbb\x17:\x12Yb\xc8.K\xf7\xa2\xd5k\x98\xbd" +
	"\x84)e^\x93B\x9e\xbd\x8e\x0a,\xfb1u\xa7\xaf" +
	"\xc4q\xdb\x95\xddY\xb3.\x95\xb5\xa4\xcc\xcb\xe4\xb8!" +
	"-\xc7L(\xc7\x09\"\xb1\x91C\xdc\xcd\x96\x09\xb0\x1d" +
	"\xdeMD(%\xdd\x92\x80\xd2\x0d\xc83\x06\xc6g\x03" +
	"}&\xed\xb60\x91\xb4u\xbdp\xcc\x9bL\x1e\xf2\xa2" +
	"\x18 C+d:\x82\xbda\xed\x8c0Dy\xd9\xae" +
	"d{\x1f\x87\x98d\x89\x9c\xa8d\xd9\x8f\xa5d\x17\xbf" +
	"\xb7TI\x16\x0d\x07O\xbfO\x80\xda\x0d0\xef\xff\xc8" +
	"\x85\x84\x97}e\xa8\xda\x07\xf4u\xf7\x10\x81\xe9C\x13" +
	"D\xe0\xfaMU\xa2\xca\xbc\xdd\x93\xeep\xc3\xea\xca\xba" +
	"\xeb\xcd\xcd\xb7]k\xcc\xe9\x10\xd1\xa2\xd3\x91\xf6\x83\xd2" +
	"\xbdF\xad\xe3\xbbF\xb6\xdb\xb63o\xd7\xe5\x9c\xb4\xdd" +
	"\xd1\xfdp\xd5;\x99\x98\x96\x01\xa5\xd7<\x87\x18\\\xaa" +
	"\xb8\x95\x92T5\xed\xc6>\xab\xe1\xb6\xc6s\xf6\xac#" +
	"2H\x0d\x0d\x1d'S\xc9\x08=\xb9\xdb\x12\xc5\xf8\xd9" +
	"\xd1\x19\xb5-p\x88=I6\xbe0\x91*\x9d\xa8J" +
	"\xe4\xb1\xb0\"\\\x06\xaf\x16>J\xbc\x95JP\xfc\xee" +
	"\x92\x04U\xa7\x95\xf8\xf2\xc4\x90\xefS\xe6UL\xc7g" +
	"+\xd4\xc9\x03\xd2\x09\x12\xe5\xd4M\xd7r\xec\xcd\xf7;" +
	"N\xb7a\xd9\xa6\xcbeO\x91\x99\x8aj\"\x8cj*" +
	"U\xfc;v\x12\x89I\x0e\xf1\xd9\xa4\x0d>\xac\xea|" +
	"\x8aC<\xc2\xe0\xb5M\xd7r\xe7\x1b~\xb1\xac\"\x86" +
	"U\xaa\x80\x1c\xbb\xa9\x8c\x04\x19\xd9\x16\xcdFCAG" +
	"\x91\x18\x8a+\xe3\xf63`\x9b\xed1\xa7\xd3[Z\xe3" +
	"%ez\xbf\xfa\xee3nJ-\xa7\xd3\xeb\xdb~V" +
	"\xc2\x91(e\x09\x88\xaai\x0f\x07\xf6eH>\xb4\x02" +
	"\x12^\xdb\x17\xa5\xae?\x0e~\xbd<V\xfcD\xfaZ" +
	"M6\x0bLxQf\x89(]\x19*oE\x0eq" +
	"\xbb\xcaQ\xe4\x82\x94\xf0\xe2KB\xe1E\x00\xd8r\x00" +
	"\x15\x1f\x81\x18Dj\xe1\xd5\xd7\xd5\x92\xc5J_\xd7M" +
	"\xadQ\xeb\xaa\xc9N\xa9\xdf\xb27YV\xf4[\x8ex" +
	"\xd1\xf0&Uw^D.U|z\x17C\xb1&}" +
	"\xb1\xe4\xff\x8c\xb4\x80H\x0cD\xe2\x83q\xa4\xcfVS" +
	"C9\xa2\xfc9\xd5\x18Np\x88o\xabj\x0cu{" +
	"j\"\x99\xd4:\x0f\x87\xd6\xf7\x14Q\xdf\xe5\x10g\x18" +
	"\xf4Lf\x10\x19\"\xfd%\xd5n\x7f\xc4!^e\xd0" +
	"5m\x10\x1a\x91\xfe\x8aJ\xe3\x19\x0e\xf1\x13\x86\xc5v" +
	"8h\xcb\x09'\x04\x94\x09\xb9\xa6tPN\xf8\x08\xac" +
	"\xfeLq\xc3\x99RN/\xdd\xfei\xdc\x1a\xd0B9" +
	"!6<\xb5\xc2\xf8\xc9\x97>\xca\x09\xa5\x81C\xc9v" +
	"\\yMaeVj\x08\xc3\x81(|E\xc5\xdb\xb8" +
	"\x8e\x9a\x17\xb5\x08\xca\xb9\xb2\x97\x16w\xb5\x9f\xb8g\xc2" +
	"1:\xc6\xb0\xd8\xec\xf4FL\xd7D9\xb90\x1d\xc3" +
	"\xacY'~\xfdQ\x7f\x03;g\xb0\xc2U\xe2\x953" +
	"\xd5\xbd\xb6$\xd30\x067\xbe%\xd5\xd2\xa2\xa6\xbcC" +
	"\xe5q\x8cC\xec^\xbe\x87V|\x94\xff\xd7V\x9a\xf4" +
	"\xab\xe1@\xa3>\xad\xf1\xdf\x16\x1d\xddx\xa8PE\xaa" +
	"<\xa6\x89\xed\xf6\x99\xee\xb5\xd4t\xb7\x96~\x9a\x14q" +
	"\xfc@X\xc4\x96\xbd\xdbyh\xde\x1d\xa3\\\xaa\xe1]" +
	"\xd3[\xc6\xacFC\xdaS\xa6\xdb\xda%\x9b\x0a>\xd1" +
	"\x8d\xcd\xd5\xff\x05\x00\x00\xff\xff\xd5\x9c&\xd5"

func init() {
	schemas.Register(schema_e6c88f91b6a1209e,
		0x885e742db1fb5301,
		0x92ae8103dd768751,
		0x96c1dab83835e4f9,
		0x9ab6cd3b4d0d17c7,
		0xb4b9b8f861554bad,
		0xb83b1b1b174f8aec,
		0xc586650e812cc6a1,
		0xc6ff25e3b262348a,
		0xc7a6dc5be99844b2,
		0xcd7606ede67cf290,
		0xd0676003f5393449,
		0xd8c2ba2779275a74,
		0xdb505e3694652d57,
		0xddd46d94d5f5ee47,
		0xea318fecf64edd5a,
		0xeb06bcceba87669a,
		0xff79b399e1e58cf3)
}
