#!/bin/bash

set -e

BASE=$(dirname "$0")
. $(dirname "$BASE")/common.sh
. "$BASE/common.sh"

[ -z "$("$BASE/check")" ] && exit

echo "Installing necessary packages from pip3 for scion-web"
pip_install pip3 "$req"
