#!/bin/bash

set -e

BASE=$(dirname "$0")
. $(dirname "$BASE")/common.sh
. "$BASE/common.sh"

if go_installed; then
    go_ver_check || go_ver_msg
else
    echo "Go not found in \$PATH"
fi

if type -p govendor &> /dev/null; then
    VERSION="v1.0.8"
    ver=$(govendor -version 2>&1 || true)
    [ "$ver" = "$VERSION" ] || echo "Govendor version: expected $VERSION, got $ver"
else
    echo "govendor not found in \$PATH"
fi
