#!/bin/bash

# The $GO_INSTALL environment variable, if set, tells this script to
# install/upgrade (as appropriate) a compatible Go version. This env var isn't
# set by default, and should only be used in an automated environment, or if
# the user knows what they're doing. If you already have a /usr/local/go dir,
# setting $GO_INSTALL may remove that directory (if your existing Go install is
# not in your $PATH, or if the version isn't compatible), so use with caution.

set -e

BASE=$(dirname "$0")
. $(dirname "$BASE")/common.sh
. "$BASE/common.sh"

go_check_install() {
    if go_installed; then
        go_ver_check && return
        go_ver_msg
    fi
    [ -d /usr/local/go ] && sudo rm -r /usr/local/go
    go_install
}

go_install() {
    if [ -d /usr/local/go ]; then
        echo "ERROR: cannot install Go, /usr/local/go already exists"
        exit 1
    fi
    if [ "$(uname -o)" = "Linux" ]; then
        # Feeling paranoid.
        echo "ERROR: Non-linux OSes ($(uname -o)) aren't supported"
        exit 1
    fi
    local src sum
    case "$(uname -m)" in
        x86_64)
            src=https://storage.googleapis.com/golang/go1.9.linux-amd64.tar.gz
            sum=d70eadefce8e160638a9a6db97f7192d8463069ab33138893ad3bf31b0650a79
            ;;
        i?86)
            src=https://storage.googleapis.com/golang/go1.9.linux-386.tar.gz
            sum=7cccff99dacf59162cd67f5b11070d667691397fd421b0a9ad287da019debc4f
            ;;
        arm*|aarch*)
            src=https://storage.googleapis.com/golang/go1.9.linux-armv6l.tar.gz
            sum=f52ca5933f7a8de2daf7a3172b0406353622c6a39e67dd08bbbeb84c6496f487
            ;;
        *)
            echo "ERROR: unsupported architecture '$(uname -m)'"
            exit 1
    esac
    tmpdir=$(mktemp -d /tmp/go_install.XXXXXXX)
    file="${tmpdir:?}/$(basename ${src:?})"
    echo "$sum  $file"  > "$tmpdir/SHA256SUM"
    echo "Downloading $src to $file"
    curl -# "$src" -o "$file"
    echo "$sum $file" | sha256sum -c -
    echo "Installing to /usr/local/go. Ensure that /usr/local/go/bin is in your \$PATH"
    sudo tar -C /usr/local -xf "$file"
    rm -r "${tmpdir:?}"
}

# First handle the case where Go isn't installed, or needs to be upgraded.
if [ -n "$GO_INSTALL" ]; then
    go_check_install
fi

# Then confirm that go is installed, and with an appropriate version.
if go_installed; then
    go_ver_check || { echo "ERROR: $(go_ver_msg)"; exit 1; }
else
    echo "ERROR: Go not found in \$PATH ($PATH)"
    exit 1
fi

[ -z "$("$BASE/check")" ] && exit

echo "Installing/updating govendor dep manager"

# Make sure GOPATH is set
[ -n "$GOPATH" ] || { echo "ERROR: \$GOPATH is unset"; exit 1; }

GOPATH_BASE=${GOPATH%%:*} # Find the first dir in $GOPATH

host_user=github.com/kardianos
project=govendor
parent_dir="$GOPATH_BASE/src/${host_user:?}"
url="https://$host_user/${project:?}.git"
commit=fbbc78e8d1b533dfcf81c2a4be2cec2617a926f7

# Perform initial clone, if necessary
mkdir -p "${parent_dir:?}"
cd "$parent_dir"
[ -d "${project:?}" ] || git clone "${url:?}"

# Fetch/update/install
cd "$project"
git fetch
git checkout "${commit:?}"
go install -v
