#!/bin/bash

BRID=brC
TEST_NAME="${BRID}_acceptance"
PROGRAM=$(basename "$0")
COMMAND="$1"
DEVINFO_FN=acceptance/${BRID}_acceptance/devinfo.txt
BRUTIL=acceptance/brutil

. $BRUTIL/common.sh
. $BRUTIL/util.sh

# This function is called from test_setup
set_veths() {
    create_veth $NS veth0_root ifid_local 192.168.0.13/24 \
        192.168.0.11 192.168.0.12 192.168.0.14 192.168.0.51 192.168.0.61 192.168.0.71
    create_veth $NS veth1_root ifid_161 192.168.16.2/31 192.168.16.3
}

test_run() {
    set -e
    bin/braccept -borderID "$BRID" -devInfoFilePath "$DEVINFO_FN" \
        -keysDirPath "$BRUTIL/br-conf/keys" $@
}

# This function is called from test_teardown
del_veths() {
    delete_veth veth0_root veth1_root
}

do_command $PROGRAM $COMMAND $TEST_NAME ${@:2}
