#! /bin/bash

# In diff mode, we expect no changes (exit code 3)
if [[ "$GAZELLE_MODE" == "diff" ]]; then
    test $ret -eq 3 && exit 0
    exit 1
fi

# In fix mode, we succeed even if there are changes.
test $ret -eq 0 && exit 0
test $ret -eq 3 && exit 0
exit 1
