linters:
  # FIXME(roosd): For now, we disable all linters and turn them on one-by-one.
  disable-all: true
  enable:
    # Default linters.
    - forbidigo
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - typecheck
    - unused
    # Extended linters.
    - exportloopref
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - gofmt
    - lll
    - misspell
    - goheader
linters-settings:
  # ...
  forbidigo:
    forbid:
    - p: "([iI][fF][iI]d)|([iI]F[iI][dD])|([iI][fF]i[dD])"
      msg: "spell interface ID as ifID / IfID"
    - p: "(?i)interfaceID"  # case insensitive
      msg: "spell interface ID as ifID / IfID"
    - p: "Trc"
      msg: "spell trust root certificate as trc / TRC"
  lll:
    line-length: 100
    tab-width: 4
  errcheck:
    exclude-functions:
      - (*github.com/spf13/cobra.Command).MarkFlagRequired
  goheader:
    values:
      regexp:
        copyright-lines: "(Copyright 20[0-9][0-9] .*)(\nCopyright 20[0-9][0-9] .*)*"
    template: |-
      {{copyright-lines}}

      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.

issues:
  exclude-rules:
    # don't report long lines with long links
    - linters: [lll]
      source: "http[s]://\\S{80,}$"
    # don't report long lines with yaml/json/toml tags
    - linters: [lll]
      source: "`(yaml|toml|json):\"[^`]*`$"

    # these files originate from third-party projects
    - path: pkg/private/util/duration.go
      linters: [goheader]
    - path: pkg/private/serrors/stack.go
      linters: [goheader, errcheck]
    - path: scion-pki/certs/(certinfo|certformat).go
      linters: [lll, goheader, errcheck]
    - path: pkg/scrypto/cms
      linters: [goheader]

