DROP TABLE IF EXISTS NextQuery;

CREATE TABLE NextQuery(
    RowID INTEGER PRIMARY KEY,
    SrcIsdID INTEGER NOT NULL,
    SrcAsID INTEGER NOT NULL,
    DstIsdID INTEGER NOT NULL,
    DstAsID INTEGER NOT NULL,
    Policy DATA NOT NULL,
    NextQuery INTEGER NOT NULL,
    UNIQUE(SrcIsdID, SrcAsID, DstIsdID, DstAsID, Policy) ON CONFLICT REPLACE
);

PRAGMA user_version = 8;
