networks:
  bridge1:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: bridge1
    ipam:
      config:
      - subnet: 242.254.100.0/24
services:
  topo_sd_reload_dispatcher:
    container_name: topo_sd_reload_dispatcher
    image: bazel/acceptance/topo_sd_reload:dispatcher
    networks:
      bridge1:
        ipv4_address: 242.254.100.2
    volumes:
    - vol_logs:/share/logs:rw
    - vol_scion_disp1-ff00_0_110:/run/shm/dispatcher:rw
  topo_sd_reload_sciond:
    container_name: topo_sd_reload_sciond
    image: bazel/acceptance/topo_sd_reload:sciond
    volumes:
    - vol_logs:/share/logs:rw
    - vol_scion_disp1-ff00_0_110:/run/shm/dispatcher:ro
    network_mode: service:topo_sd_reload_dispatcher
  topo_sd_reload_log_exporter:
    container_name: topo_sd_reload_log_exporter
    image: alpine
    volumes:
    - vol_logs:/share/logs:ro
version: '2.4'
volumes:
  vol_logs: null
  vol_scion_disp1-ff00_0_110: null
