networks:
  bridge1:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: bridge1
    ipam:
      config:
      - subnet: 242.254.100.0/24
services:
  topo_sd_reload_dispatcher:
    container_name: topo_sd_reload_dispatcher
    image: bazel/acceptance/topo_sd_reload:dispatcher
    networks:
      bridge1:
        ipv4_address: 242.254.100.2
    volumes:
    - vol_topo_sd_reload_disp:/run/shm/dispatcher:rw
  topo_sd_reload_daemon:
    container_name: topo_sd_reload_daemon
    image: bazel/acceptance/topo_sd_reload:daemon
    volumes:
    - vol_topo_sd_reload_disp:/run/shm/dispatcher:ro
    - vol_topo_sd_reload_certs:/certs:ro
    network_mode: service:topo_sd_reload_dispatcher
version: '2.4'
volumes:
  vol_topo_sd_reload_disp: null
  vol_topo_sd_reload_certs: null
