FROM scion_app_base:latest
COPY --from=scion_app_builder:latest /home/scion/go/src/github.com/scionproto/scion/bin/border /app/

ENTRYPOINT ["/sbin/su-exec", "/app/border", "-config", "/share/conf/brconfig.toml"]
