FROM scion_app_base:latest
COPY --from=scion_app_builder:latest /home/scion/go/src/github.com/scionproto/scion/bin/godispatcher /app/

ENTRYPOINT ["/sbin/su-exec", "/app/godispatcher", "-config", "/share/conf/dispconfig.toml"]
