openapi: "3.0.2"
info:
  description: "Service Management API for the SCION Dispatcher"
  title: Dispatcher Management API
  version: "0.1.0"
servers:
  - url: http://{host}:{port}/api/v1
    variables:
      host:
        default: "localhost"
      port:
        default: "30441"
tags:
  - name: common
    description: Common API exposed by SCION services.
paths:
  /info:
    $ref: "../common/process.yml#/paths/~1info"
  /log/level:
    $ref: "../common/process.yml#/paths/~1log~1level"
  /config:
    $ref: "../common/process.yml#/paths/~1config"
