#!/bin/bash

set -ex
[ -d /rootfs ] || mkdir /rootfs
files=$(dpkg -L $1)
if [ -n "$2" ]; then
    files=$(dpkg -L $1 | grep -v $2)
fi
copyright=/usr/share/doc/"$1"/copyright
if [ -e "$copyright" ]; then
    mkdir -p /rootfs/LICENSES/"$1"
    cp "$copyright" /rootfs/LICENSES/"$1"/
fi
for f in $files /etc/services; do
    [ ! -d "$f" ] || continue
    dir="/rootfs$(dirname "$f")"
    mkdir -p "$dir"
    cp -a "$f" "$dir/"
done
