#!/bin/bash

set -e

mkdir -p hashes

img="${1}"
out="hashes/${1#scion_}"
tag="$img:latest"

h="$(docker image ls "$tag" --format '{{ .ID }}')"
if [ ! -f "$out" ] || [ "$h" != "$(cat "$out")" ]; then
    echo "$h" > "$out"
    echo "$out updated to $h"
else
    echo "$out up to date"
fi
