#!/bin/bash

set -e

target="$(basename ${1:?})"
shift
dfile="${1:?}"
shift
src="${1}"

img="scion_$target"
tag="$img:latest"

if [ -n "$src" ]; then
    # Allowing out of build context Dockerfile for 17.06+
    # see https://github.com/docker/compose/issues/4926#issuecomment-343002431
    docker build -t "$tag" $DOCKER_ARGS -f - "$src" < "$dfile"
else
    docker build -t "$tag" $DOCKER_ARGS - < "$dfile"
fi
./docker_hash "$img"
