#!/bin/bash

set -ex

REMOTE="scionproto"

echo "Tag: ${1:-}"

c_images="dispatcher"
go_images="border dispatcher_go sig beacon cert path sciond"
py_images="beacon_py cert_py path_py sciond_py"
images="$c_images $go_images $py_images"

# Tag local apps and push to remote
for app in $images; do
    local_img="scion_$app"
    remote_img="$REMOTE/$app"
    docker tag "$local_img:latest" "$remote_img:$1"
    docker tag "${local_img}_debug:latest" "${remote_img}_debug:$1"
    docker push "$remote_img:$1"
    docker push "${remote_img}_debug:$1"
done
