#!/bin/bash

set -ex

echo "Remote: ${1:-}"
echo "Tag: ${2:-latest}"

# Tag local apps for registry and push to remote
for app in border dispatcher sig beacon cert path sciond; do
    docker tag "scion_$app:latest" "$1/$app:$2"
    docker push "$1/$app:$2"
done

# ./publish eu.gcr.io/anapaya-containers 0.1.0
