#!/bin/bash

set -exu

TAG="$BUILDKITE_BUILD_NUMBER"

echo "$REGISTRY_PASSWORD" | docker login "$REGISTRY" -u "$REGISTRY_USER" --password-stdin

images="border dispatcher sig beacon_py cert cert_py path path_py sciond sciond_py"

if [ "${1:?}" == "push" ]; then
    # Tag local apps and push to remote
    for app in $images; do
        local_img="scion_$app"
        remote_img="$REGISTRY/$app"
        docker tag "$local_img:latest" "$remote_img:$TAG"
        docker push "$remote_img:$TAG"
    done
fi
if [ "$1" == "pull" ]; then
    # Pull images
    for app in $images; do
        local_img="scion_$app"
        remote_img="$REGISTRY/$app"
        docker pull "$remote_img:$TAG"
        docker tag "$remote_img:$TAG" "$local_img:latest"
    done
fi
