steps:
  - label: ":bazel: Build scion code"
    command:
      - bazel --bazelrc=.bazelrc_ci build //:scion //:scion-ci
    key: build
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
        - exit_status: 255 # Forced agent shutdown
    timeout_in_minutes: 10
  - label: ":bazel: Go tests"
    command:
      - bazel --bazelrc=.bazelrc_ci test //go/... --print_relative_test_log_paths
    key: go_tests
    artifact_paths:
      - "artifacts.out/**/*"
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
        - exit_status: 255 # Forced agent shutdown
    timeout_in_minutes: 10
  - label: "Check generated go_deps.bzl file is up to date with go.mod"
    command:
      - "rm -rf /tmp/$BUILDKITE_STEP_ID/"
      - "mkdir -p /tmp/$BUILDKITE_STEP_ID/"
      - "cp go.mod go.sum go_deps.bzl /tmp/$BUILDKITE_STEP_ID/"
      - "make godeps -B"
      - "bazel-${BUILDKITE_PIPELINE_SLUG}/external/go_sdk/bin/go mod tidy"
      - "diff -u /tmp/$BUILDKITE_STEP_ID/go.mod go.mod"
      - "diff -u /tmp/$BUILDKITE_STEP_ID/go.sum go.sum"
      - "diff -u /tmp/$BUILDKITE_STEP_ID/go_deps.bzl go_deps.bzl"
    key: go_deps_lint
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
        - exit_status: 255 # Forced agent shutdown
  - label: "Check generated go/proto files in git"
    command:
      - "rm -rf /tmp/$BUILDKITE_STEP_ID/"
      - "mkdir -p /tmp/$BUILDKITE_STEP_ID/"
      - "cp -R go/proto/ /tmp/$BUILDKITE_STEP_ID/"
      - "make gogen"
      - "diff -ur /tmp/$BUILDKITE_STEP_ID/proto/ go/proto/"
    key: go_gen_lint
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
        - exit_status: 255 # Forced agent shutdown
  - label: "Lint :bazel:"
    command: ./scion.sh lint
    key: lint
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
        - exit_status: 255 # Forced agent shutdown
  - label: "Acceptance: sig_failover"
    command:
      - mkdir -p $$ACCEPTANCE_ARTIFACTS
      - bazel test --action_env=ACCEPTANCE_ARTIFACTS //acceptance/sig_failover:sig_failover_test
    key: sig_failover
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
        - exit_status: 255 # Forced agent shutdown
    artifact_paths:
      - "artifacts.out/**/*"
  - label: "Acceptance: sig_short_exp_time"
    command:
      - mkdir -p $$ACCEPTANCE_ARTIFACTS
      - bazel test --action_env=ACCEPTANCE_ARTIFACTS //acceptance/sig_short_exp_time:sig_short_exp_time_test
    key: sig_short_exp_time
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
        - exit_status: 255 # Forced agent shutdown
    artifact_paths:
      - "artifacts.out/**/*"

