env:
  GOPROXY: "http://localhost:3200|https://proxy.golang.org|direct"
steps:
  - group: "End to End"
    key: e2e
    steps:
      - label: "E2E: default :man_in_business_suit_levitating: (scion, ping)"
        command:
          - echo "--- build"
          - make
          - echo "--- start topology"
          - ./scion.sh topology -c topology/default.topo
          - ./scion.sh run
          - tools/await-connectivity
          - ./bin/scion_integration || ( echo "^^^ +++" && false )
          - ./bin/end2end_integration || ( echo "^^^ +++" && false )
        parallelism: 10
        plugins: &shutdown-scion-post-command
          - scionproto/metahook#v0.3.0:
              post-command: |
                echo "--- Shutting down SCION topology"
                ./scion.sh stop
                echo "SCION topology successfully shut down"
        artifact_paths:
          - "artifacts.out/**/*"
        timeout_in_minutes: 15
        key: e2e_integration_tests_v2
        retry: &automatic-retry
          automatic:
            - exit_status: -1 # Agent was lost
            - exit_status: 255 # Forced agent shutdown

