steps:
  - label: ":bazel: Build scion code"
    command:
      - bazel --bazelrc=.bazelrc_ci build //:scion //:scion-ci
    key: build
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
        - exit_status: 255 # Forced agent shutdown
    timeout_in_minutes: 10
  - label: ":bazel: Go tests"
    command:
      - bazel --bazelrc=.bazelrc_ci test //go/... --print_relative_test_log_paths
    key: go_tests
    artifact_paths:
      - "artifacts.out/**/*"
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
        - exit_status: 255 # Forced agent shutdown
    timeout_in_minutes: 10
  - label: "Check generated go_deps.bzl file is up to date with go.mod"
    command:
      - "rm -rf  /tmp/${BUILDKITE_STEP_ID:-local}/"
      - "mkdir -p /tmp/${BUILDKITE_STEP_ID:-local}/"
      - "cp go.mod go.sum go_deps.bzl /tmp/${BUILDKITE_STEP_ID:-local}/"
      - "make godeps -B"
      - "bazel-${BUILDKITE_PIPELINE_SLUG}/external/go_sdk/bin/go mod tidy"
      - "diff -u /tmp/${BUILDKITE_STEP_ID:-local}/go.mod go.mod"
      - "diff -u /tmp/${BUILDKITE_STEP_ID:-local}/go.sum go.sum"
      - "diff -u /tmp/${BUILDKITE_STEP_ID:-local}/go_deps.bzl go_deps.bzl"
    key: go_deps_lint
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
        - exit_status: 255 # Forced agent shutdown
  - label: "Check generated go/proto files in git"
    command:
      - "rm -rf /tmp/${BUILDKITE_STEP_ID:-local}/"
      - "mkdir -p /tmp/${BUILDKITE_STEP_ID:-local}/"
      - "cp -R go/proto/ /tmp/${BUILDKITE_STEP_ID:-local}/"
      - "make gogen"
      - "diff -ur /tmp/${BUILDKITE_STEP_ID:-local}/proto/ go/proto/"
    key: go_gen_lint
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
        - exit_status: 255 # Forced agent shutdown
  - label: "Lint :bazel:"
    command: ./scion.sh lint
    key: lint
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
        - exit_status: 255 # Forced agent shutdown
  - label: "Integration: {cert_req,pp,end2end,scmp}_integration"
    command:
    - bazel --bazelrc=.bazelrc_ci build //:scion //:scion-ci >/dev/null 2>&1
    - tar -kxf bazel-bin/scion.tar -C bin --overwrite
    - tar -kxf bazel-bin/scion-ci.tar -C bin --overwrite
    - ./scion.sh topology nobuild
    - ./scion.sh run nobuild && sleep 10
    - ./bin/cert_req_integration  > /dev/null 2>&1
    - ./bin/pp_integration  > /dev/null 2>&1
    - ./bin/scmp_integration  > /dev/null 2>&1
    - ./bin/end2end_integration  > /dev/null 2>&1
    - tar -czf "logs-${BUILDKITE_COMMIT:-local}.tar.gz" logs/*
    - ./scion.sh topo_clean
    artifact_paths:
    - "logs-*.tar.gz"
    timeout_in_minutes: 5
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
        - exit_status: 255 # Forced agent shutdown
