env:
  SCION_MOUNT: /tmp/scion_out.$BUILDKITE_BUILD_NUMBER
  SCION_CNTR: scion_ci_$BUILDKITE_AGENT_NAME

steps:
  - label: Prepare scion_base and scion images
    command:
    - ./tools/ci/prepare_image cd291537ca49388d6c409701e18f23ff10d9231c2f9252be61a9a3ba6adbe9c6
    - ./docker.sh build
  - wait
  - label: Start container
    command:
    - mkdir $SCION_MOUNT
    - ./docker.sh start
  - wait
  - label: Build
    command: ./tools/ci/build
  - wait: ~
    continue_on_failure: true
  - label: Lint
    command: ./tools/ci/lint
  - label: Unit tests
    command: ./tools/ci/unittest
  - label: Python documentation (sphinx)
    command: ./tools/ci/sphinx
  - label: Integration tests
    command: ./tools/ci/integration
    concurrency: 1
    concurrency_group: 'integration-test'
  - wait: ~
    continue_on_failure: true
  - label: Gather logs
    command:
    - ./tools/ci/bk_clean_up
    - ./docker.sh stop
    artifact_paths:
    - "artifacts.out/**/*"

  - label: Build app images
    command: make -C docker/perapp
    branches: "v*.*.*"
  - label: Docker login
    command: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
    branches: "v*.*.*"
  - label: Push images
    command: ./docker/perapp/publish "$BUILDKITE_TAG"
    branches: "v*.*.*"
