env:
  GOPROXY: "http://localhost:3200|https://proxy.golang.org|direct"
steps:
  - group: "End to End"
    key: e2e
    steps:
    - label: "E2E: default (clab)"
      command:
        - bash -c "$(curl -sL https://get.containerlab.dev)"
        - echo "--- build"
        - bazel run --run_in_cwd //testing/clab/cmd/testgen -- -c topology/default-no-peers.topo
        - bazel run //testing/clab:clab_node.load
        - docker image ls
        - echo "--- show topology"
        - cat gen/scion.clab.yml
        - echo "--- start topology"
        - sudo netstat -tulpen
        - .buildkite/debug-clab.sh pre
        - clab deploy --debug -t gen/scion.clab.yml || (.buildkite/debug-clab.sh post && sudo netstat -tulpen && echo "^^^ +++" && false)
        - bazel run --run_in_cwd //testing/clab/cmd/await_connectivity || ( echo "^^^ +++" && false )
        - echo "--- run tests (scion)"
        - bazel run --run_in_cwd //testing/clab/cmd/e2e_scion || ( echo "^^^ +++" && false )
        - echo "--- run tests (http)"
        - bazel run --run_in_cwd //testing/clab/cmd/e2e_http run || ( echo "^^^ +++" && false )
      plugins:
      - scionproto/metahook#v0.3.0:
            pre-command: .buildkite/cleanup-leftovers.sh
            post-command: |
              echo "~~~ Shutting down SCION topology"
              clab destroy -t gen/scion.clab.yml
            pre-artifact: |
              if [ -f "gen/scion-dc.yml" ]; then
                  tools/dc collect_logs scion logs/
              fi
              tar -chaf test-out.tar.gz $(ls -d logs traces gen gen-cache) # ls -d to filter missing directories
            pre-exit: .buildkite/cleanup-leftovers.sh
      artifact_paths: &scion-run-artifact-paths
        - test-out.tar.gz
      timeout_in_minutes: 15
      key: clab_integration_e2e_default
      retry: &automatic-retry
        automatic:
        - exit_status: -1 # Agent was lost
        - exit_status: 255 # Forced agent shutdown
