env:
  GOPROXY: "http://localhost:3200|https://proxy.golang.org|direct"
steps:
  - label: "Build :bazel:"
    command:
      - bazel build --verbose_failures --announce_rc //:scion //:scion-ci
      - bazel run --verbose_failures //docker:prod //docker:test
    key: build
    artifact_paths:
      - "bazel-bin/scion.tar"
      - "bazel-bin/scion-ci.tar"
    plugins:
      - scionproto/metahook#v0.3.0:
          post-artifact: |
            cat << EOF | buildkite-agent annotate --style "info" --context "binaries"
            #### Build outputs
            - <a href="artifact://bazel-bin/scion.tar">SCION binaries</a>
            - <a href="artifact://bazel-bin/scion-ci.tar">SCION test tools and utilities</a>
            EOF
    retry: &automatic-retry
      automatic:
        - exit_status: -1 # Agent was lost
        - exit_status: 255 # Forced agent shutdown
    timeout_in_minutes: 10
  - wait
  - label: "Package :debian:"
    command:
      - make dist-deb
      - cd deb;
      - tar -chaf scion-deb-amd64.tar.gz *_amd64.deb
      - tar -chaf scion-deb-arm64.tar.gz *_arm64.deb
      - tar -chaf scion-deb-i386.tar.gz *_i386.deb
      - tar -chaf scion-deb-armel.tar.gz *_armel.deb
    artifact_paths:
      - "deb/*.tar.gz"
    plugins:
      - scionproto/metahook#v0.3.0:
          post-artifact: |
            cat << EOF | buildkite-agent annotate --style "info" --context "packages"
            #### Packages :debian:
            - <a href="artifact://deb/scion-deb-amd64.tar.gz">amd64</a>
            - <a href="artifact://deb/scion-deb-arm64.tar.gz">arm64</a>
            - <a href="artifact://deb/scion-deb-i386.tar.gz">i386</a>
            - <a href="artifact://deb/scion-deb-armel.tar.gz">armel</a>
            EOF
    key: dist-deb
    retry: *automatic-retry
  - label: "Unit Tests :bazel:"
    command:
      - bazel test --config=race --config=unit_all
    key: unit_tests
    plugins:
      - scionproto/metahook#v0.3.0:
          pre-artifact: tar -chaf bazel-testlogs.tar.gz bazel-testlogs
    artifact_paths:
      - bazel-testlogs.tar.gz
    retry: *automatic-retry
    timeout_in_minutes: 20
  - label: "Lint :bash:"
    command:
      - make lint
    key: lint
    retry: *automatic-retry
    timeout_in_minutes: 20
  - label: "Check Generated :bash:"
    command:
      - echo "--- go_deps.bzl"
      - mkdir -p /tmp/test-artifacts
      - cp go.mod go.sum go_deps.bzl /tmp/test-artifacts/
      - make go.mod
      - make go_deps.bzl -B
      - diff -u /tmp/test-artifacts/go.mod go.mod
      - diff -u /tmp/test-artifacts/go.sum go.sum
      - diff -u /tmp/test-artifacts/go_deps.bzl go_deps.bzl
      - echo "--- protobuf"
      - cp -R pkg/proto/ /tmp/test-artifacts
      - make protobuf
      - diff -ur /tmp/test-artifacts/proto/ pkg/proto/
      - echo "--- licenses"
      - mkdir -p /tmp/test-artifacts/licenses
      - ./tools/licenses.sh /tmp/test-artifacts/licenses
      - diff -rNu3 /tmp/test-artifacts/licenses ./licenses/data
      - echo "--- gomocks"
      - ./tools/gomocks.py diff
      - echo "--- antlr"
      - rm -rf /tmp/test-artifacts/antlr
      - cp -R antlr/ /tmp/test-artifacts/antlr
      - make antlr
      - diff -ur /tmp/test-artifacts/antlr/ antlr/
      - echo "--- testdata"
      - ./tools/update_testdata.sh
    timeout_in_minutes: 20
    key: check_generated
    retry: *automatic-retry
  - wait
  - group: "End to End"
    key: e2e
    steps:
    - label: "E2E: default :man_in_business_suit_levitating: (scion, ping)"
      command:
        - echo "--- build"
        - make
        - echo "--- start topology"
        - ./scion.sh topology -c topology/default.topo
        - ./scion.sh run
        - tools/await-connectivity
        - ./bin/scion_integration || ( echo "^^^ +++" && false )
        - ./bin/end2end_integration || ( echo "^^^ +++" && false )
      plugins: &scion-run-hooks
        - scionproto/metahook#v0.3.0:
            pre-command: .buildkite/cleanup-leftovers.sh
            post-command: |
              echo "~~~ Shutting down SCION topology"
              ./scion.sh stop
            pre-artifact: |
              if [ -f "gen/scion-dc.yml" ]; then
                  tools/dc collect_logs scion logs/
              fi
              tar -chaf test-out.tar.gz $(ls -d logs traces gen gen-cache) # ls -d to filter missing directories
            pre-exit: .buildkite/cleanup-leftovers.sh
      artifact_paths: &scion-run-artifact-paths
        - test-out.tar.gz
      timeout_in_minutes: 15
      key: e2e_integration_tests_v2
      retry: *automatic-retry
    - label: "E2E: failing links :man_in_business_suit_levitating:"
      command:
        - echo "--- build"
        - make
        - echo "--- start topology"
        - ./scion.sh topology -c topology/default-no-peers.topo
        - ./scion.sh run
        - tools/await-connectivity
        - ./bin/end2end_integration || ( echo "^^^ +++" && false )
        - ./tools/integration/revocation_test.sh
      plugins: *scion-run-hooks
      artifact_paths: *scion-run-artifact-paths
      timeout_in_minutes: 15
      key: e2e_revocation_test_v2
      retry: *automatic-retry
    - label: "E2E: default :docker: (ping)"
      command:
        - echo "--- build"
        - make build-dev docker-images
        - echo "--- start topology"
        - ./scion.sh topology -d
        - ./scion.sh run
        - tools/await-connectivity
        - echo "--- run tests"
        - ./bin/end2end_integration -d || ( echo "^^^ +++" && false )
      plugins: *scion-run-hooks
      artifact_paths: *scion-run-artifact-paths
      timeout_in_minutes: 15
      key: docker_integration_e2e_default
      retry: *automatic-retry
