steps:
  - label: ":bazel: Build scion code"
    command:
      - bazel --bazelrc=.bazelrc_ci build //:scion //:scion-ci
    key: build
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
        - exit_status: 255 # Forced agent shutdown
    timeout_in_minutes: 10
  - label: ":bazel: Go tests"
    command:
      - bazel --bazelrc=.bazelrc_ci test //go/... --print_relative_test_log_paths
    key: go_tests
    artifact_paths:
      - "artifacts.out/**/*"
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
        - exit_status: 255 # Forced agent shutdown
    timeout_in_minutes: 10
  - label: ":python: Python tests"
    command: ./scion.sh test py
    key: py_tests
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
        - exit_status: 255 # Forced agent shutdown
  - label: "Check generated go_deps.bzl file is up to date with go.mod"
    command:
      - "cp go.mod go.sum go_deps.bzl $$TEST_ARTIFACTS/"
      - make godeps -B
      - "bazel-${BUILDKITE_PIPELINE_SLUG}/external/go_sdk/bin/go mod tidy"
      - "diff -u $$TEST_ARTIFACTS/go.mod go.mod"
      - "diff -u $$TEST_ARTIFACTS/go.sum go.sum"
      - "diff -u $$TEST_ARTIFACTS/go_deps.bzl go_deps.bzl"
    key: go_deps_lint
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
        - exit_status: 255 # Forced agent shutdown
  - label: "Check generated go/proto files in git"
    command:
      - "cp -R go/proto/ $$TEST_ARTIFACTS"
      - make gogen
      - "diff -ur $$TEST_ARTIFACTS/proto/ go/proto/"
    key: go_gen_lint
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
        - exit_status: 255 # Forced agent shutdown
  - label: "Lint :bazel:"
    command: ./scion.sh lint
    key: lint
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
        - exit_status: 255 # Forced agent shutdown
  - label: "Revocation tests"
    command:
      - bazel --bazelrc=.bazelrc_ci build //:scion //:scion-ci >/dev/null 2>&1
      - tar -kxf bazel-bin/scion.tar -C bin --overwrite
      - tar -kxf bazel-bin/scion-ci.tar -C bin --overwrite
      - ./scion.sh topology
      - ./scion.sh run nobuild && sleep 10
      - ./bin/end2end_integration -log.console warn
      - ./integration/revocation_test.sh
    key: revocation_tests
    artifact_paths:
      - "artifacts.out/**/*"
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
        - exit_status: 255 # Forced agent shutdown
  - label: "Integration: {cert_req,pp,end2end,scmp}_integration"
    command:
    - bazel --bazelrc=.bazelrc_ci build //:scion //:scion-ci >/dev/null 2>&1
    - tar -kxf bazel-bin/scion.tar -C bin --overwrite
    - tar -kxf bazel-bin/scion-ci.tar -C bin --overwrite
    - ./scion.sh topology
    - ./scion.sh run nobuild && sleep 10
    - ./bin/cert_req_integration -log.console warn
    - ./bin/pp_integration  -log.console warn
    - ./bin/scmp_integration -log.console warn
    - ./bin/end2end_integration -log.console warn
    artifact_paths:
      - "artifacts.out/**/*"
    timeout_in_minutes: 5
    key: integration_tests
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
        - exit_status: 255 # Forced agent shutdown
