steps:
  - label: "end2end in docker"
    parallelism: 1
    command:
      - time ./runme
    key: end2end_docker_tests
    artifact_paths:
      - "artifacts.out/**/*"
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
        - exit_status: 255 # Forced agent shutdown
