env:
  GOPROXY: "http://localhost:3200|https://proxy.golang.org|direct"
steps:
  - label: "Build :bazel:"
    command:
      - bazel build --verbose_failures --announce_rc //:scion //:scion-ci
      - bazel build --verbose_failures //docker:prod //docker:test
    key: build
    artifact_paths:
      - "scion_${SCION_VERSION}_amd64_linux.tar.gz"     # Note: SCION_VERSION interpolated by buildkite agent uploading pipeline, see pre-command hook
      - "scion-ci_${SCION_VERSION}_amd64_linux.tar.gz"
    plugins:
      - scionproto/metahook#v0.3.0:
          pre-artifact: |
            gzip --to-stdout bazel-bin/scion.tar > scion_${SCION_VERSION}_amd64_linux.tar.gz
            gzip --to-stdout bazel-bin/scion-ci.tar > scion-ci_${SCION_VERSION}_amd64_linux.tar.gz
          post-artifact: |
            cat << EOF | buildkite-agent annotate --style "info" --context "binaries"
            #### Build outputs
            - <a href="artifact://scion_${SCION_VERSION}_amd64_linux.tar.gz">SCION binaries</a>
            - <a href="artifact://scion-ci_${SCION_VERSION}_amd64_linux.tar.gz">SCION test tools and utilities</a>
            EOF
    retry: &automatic-retry
      automatic:
        - exit_status: -1 # Agent was lost
        - exit_status: 255 # Forced agent shutdown
    timeout_in_minutes: 10
  - wait
  - label: "Package :debian: :openwrt: :rpm:"
    command: |
      make dist-deb BFLAGS="--file_name_version=${SCION_VERSION}"
      make dist-openwrt BFLAGS="--file_name_version=${SCION_VERSION}"
      make dist-rpm BFLAGS="--file_name_version=${SCION_VERSION}"
    artifact_paths:
      - "installables/scion_*.tar.gz"
    plugins:
      - scionproto/metahook#v0.3.0:
          pre-artifact: |
            set -x
            pushd installables
            tar -chaf scion_${SCION_VERSION}_deb_amd64.tar.gz *_${SCION_VERSION}_amd64.deb
            tar -chaf scion_${SCION_VERSION}_deb_arm64.tar.gz *_${SCION_VERSION}_arm64.deb
            tar -chaf scion_${SCION_VERSION}_deb_i386.tar.gz *_${SCION_VERSION}_i386.deb
            tar -chaf scion_${SCION_VERSION}_deb_armel.tar.gz *_${SCION_VERSION}_armel.deb
            tar -chaf scion_${SCION_VERSION}_openwrt_x86_64.tar.gz *_${SCION_VERSION}_x86_64.ipk
            tar -chaf scion_${SCION_VERSION}_rpm_x86_64.tar.gz *_${SCION_VERSION}_x86_64.rpm
            tar -chaf scion_${SCION_VERSION}_rpm_arm64.tar.gz *_${SCION_VERSION}_x86_64.rpm
            tar -chaf scion_${SCION_VERSION}_rpm_i386.tar.gz *_${SCION_VERSION}_x86_64.rpm
            tar -chaf scion_${SCION_VERSION}_rpm_armel.tar.gz *_${SCION_VERSION}_x86_64.rpm
            popd
            ls installables
          post-artifact: |
            cat << EOF | buildkite-agent annotate --style "info" --context "packages"
            #### Packages :debian:
            - <a href="artifact://installables/scion_${SCION_VERSION}_deb_amd64.tar.gz">amd64</a>
            - <a href="artifact://installables/scion_${SCION_VERSION}_deb_arm64.tar.gz">arm64</a>
            - <a href="artifact://installables/scion_${SCION_VERSION}_deb_i386.tar.gz">i386</a>
            - <a href="artifact://installables/scion_${SCION_VERSION}_deb_armel.tar.gz">armel</a>
            #### Packages :openwrt:
            - <a href="artifact://installables/scion_${SCION_VERSION}_openwrt_x86_64.tar.gz">x86_64</a>
            #### Packages :rpm:
            - <a href="artifact://installables/scion_${SCION_VERSION}_rpm_x86_64.tar.gz">x86_64</a>
            - <a href="artifact://installables/scion_${SCION_VERSION}_rpm_arm64.tar.gz">arm64</a>
            - <a href="artifact://installables/scion_${SCION_VERSION}_rpm_i386.tar.gz">i386</a>
            - <a href="artifact://installables/scion_${SCION_VERSION}_rpm_armel.tar.gz">armel</a>
            EOF
    key: dist
    retry: *automatic-retry
  - label: "Unit Tests :bazel:"
    command:
      - bazel test --config=race --config=unit_all
    key: unit_tests
    plugins:
      - scionproto/metahook#v0.3.0:
          pre-artifact: tar -chaf bazel-testlogs.tar.gz bazel-testlogs
    artifact_paths:
      - bazel-testlogs.tar.gz
    retry: *automatic-retry
    timeout_in_minutes: 20
  - label: "Lint :bash:"
    command:
      - make lint
    key: lint
    retry: *automatic-retry
    timeout_in_minutes: 20
  - label: "Check Generated :bash:"
    command:
      - echo "--- go_deps.bzl"
      - mkdir -p /tmp/test-artifacts
      - cp go.mod go.sum go_deps.bzl /tmp/test-artifacts/
      - make go.mod
      - make go_deps.bzl -B
      - diff -u /tmp/test-artifacts/go.mod go.mod
      - diff -u /tmp/test-artifacts/go.sum go.sum
      - diff -u /tmp/test-artifacts/go_deps.bzl go_deps.bzl
      - echo "--- protobuf"
      - cp -R pkg/proto/ /tmp/test-artifacts
      - make protobuf
      - diff -ur /tmp/test-artifacts/proto/ pkg/proto/
      - echo "--- licenses"
      - mkdir -p /tmp/test-artifacts/licenses
      - ./tools/licenses.sh /tmp/test-artifacts/licenses
      - diff -rNu3 /tmp/test-artifacts/licenses ./licenses/data
      - echo "--- gomocks"
      - make mocksdiff
      - echo "--- antlr"
      - rm -rf /tmp/test-artifacts/antlr
      - cp -R antlr/ /tmp/test-artifacts/antlr
      - make antlr
      - diff -ur /tmp/test-artifacts/antlr/ antlr/
      - echo "--- testdata"
      - ./tools/update_testdata.sh
    timeout_in_minutes: 20
    key: check_generated
    retry: *automatic-retry
  - wait
  - group: "End to End"
    key: e2e
    steps:
    - label: "E2E: default :man_in_business_suit_levitating: (scion, ping)"
      command:
        - echo "--- build"
        - make
        - echo "--- start topology"
        - ./scion.sh topology -c topology/default.topo
        - ./scion.sh run
        - tools/await-connectivity
        - ./bin/scion_integration || ( echo "^^^ +++" && false )
        - ./bin/end2end_integration || ( echo "^^^ +++" && false )
      plugins: &scion-run-hooks
        - scionproto/metahook#v0.3.0:
            pre-command: .buildkite/cleanup-leftovers.sh
            post-command: |
              echo "~~~ Shutting down SCION topology"
              ./scion.sh stop
            pre-artifact: |
              if [ -f "gen/scion-dc.yml" ]; then
                  tools/dc collect_logs scion logs/
              fi
              tar -chaf test-out.tar.gz $(ls -d logs traces gen gen-cache) # ls -d to filter missing directories
            pre-exit: .buildkite/cleanup-leftovers.sh
      artifact_paths: &scion-run-artifact-paths
        - test-out.tar.gz
      timeout_in_minutes: 15
      key: e2e_integration_tests_v2
      retry: *automatic-retry
    - label: "E2E: failing links :man_in_business_suit_levitating:"
      command:
        - echo "--- build"
        - make
        - echo "--- start topology"
        - ./scion.sh topology -c topology/default-no-peers.topo
        - ./scion.sh run
        - tools/await-connectivity
        - ./bin/end2end_integration || ( echo "^^^ +++" && false )
        - ./tools/integration/revocation_test.sh
      plugins: *scion-run-hooks
      artifact_paths: *scion-run-artifact-paths
      timeout_in_minutes: 15
      key: e2e_revocation_test_v2
      retry: *automatic-retry
    - label: "E2E: default :docker: (ping)"
      command:
        - echo "--- build"
        - make build-dev docker-images
        - echo "--- start topology"
        - ./scion.sh topology -d
        - ./scion.sh run
        - tools/await-connectivity
        - echo "--- run tests"
        - ./bin/end2end_integration -d || ( echo "^^^ +++" && false )
      plugins: *scion-run-hooks
      artifact_paths: *scion-run-artifact-paths
      timeout_in_minutes: 15
      key: docker_integration_e2e_default
      retry: *automatic-retry
