#!/bin/bash

echo "Running: ${1:?}"

# Pull CI image and start it
docker pull $SCION_IMG
./docker.sh start

# Run test
./tools/ci/"$@"
res=$?

# Pack logs and stop everything
$BASE/pack_logs
./docker.sh stop
rm -f $SCION_MOUNT/logs/*
$BASE/clean_env.sh
exit $res
