- label: Prepare scion_base and scion images
  command:
      - $BASE/clean_env.sh
      - ./tools/ci/prepare_image 84ae2e64f723733d97573660e0bd4dad624507ff5b37c2188c06d42ab3fc1eec
      - ./docker.sh build
  concurrency: 1
  concurrency_group: "build-scion"
# FIXME(worxli): we should commit the built code and push the image, then use that image for the
# rest of the pipeline
- wait
- label: Start container
  command:
      - mkdir $SCION_MOUNT
      - ./docker.sh start
- wait
