- label: Prepare scion_base and scion images
  command:
      - ./tools/ci/prepare_image d0e8b00ee1907f599e77b4ac677ab58740ad48c35ff235c516aaf1ee1d74cbef
      - ./docker.sh build
- wait
- label: Start container
  command:
      - mkdir $SCION_MOUNT
      - ./docker.sh start
- wait
