- label: Prepare scion_base and scion images
  command:
      - ./tools/ci/prepare_image 3e2fe3314bc635feb2fda81662e037a42d5b636887de2e5885307f66e9e3af3c
      - ./docker.sh build
  concurrency: 1
  concurrency_group: "build-scion"
# FIXME(worxli): we should commit the built code and push the image, then use that image for the
# rest of the pipeline
- wait
- label: Start container
  command:
      - mkdir $SCION_MOUNT
      - ./docker.sh start
- wait
