#!/bin/bash

# This test checks that the border router fetches the static topology
# from the discovery service, and that it writes the update to disk.
#
# The test is structured as follows:
# 1. Check connectivity
# 2. Serve static topology with invalid BS address -> link goes down
# 3. Check connectivity is broken
# 4. Check logs, and file diff
# 4. Serve original static topology -> link goes up
# 6. Check connectivity is up again

. acceptance/discovery_util/util.sh

PROGRAM=`basename "$0"`
COMMAND="$1"
TEST_NAME="discovery_br_fetches_static"

DST_IA=${DST_IA:-1-ff00:0:112}
DST_IA_FILE="$(ia_file $DST_IA)"

test_setup() {
    set -e
    base_setup

    for elem in gen/ISD1/AS$AS_FILE/br*; do
        for cfg in $elem/*.toml; do
            set_log_lvl "$cfg"
            set_interval "$cfg" "static"
            sed -i -e "/\[discovery.static]/a Filename = \"/share/logs/${elem##*/}-topo.json\"" $cfg
        done
    done

    base_start_scion
    ./tools/dc start tester_$DST_IA_FILE tester_$IA_FILE
}

test_run() {
    set -e
    sleep 3
    check_connectivity "initial check"

    log "Staring to serve static topology with wrong CS address."
    jq ".ControlService[].Addrs.IPv4.Public.Addr = \"127.42.42.42\" | .Timestamp = $( date +%s)" $TOPO | sponge $STATIC_FULL
    log "Waiting for CS to issue revocation and link going down"
    sleep 4
    check_connectivity_broken "invalid beacon service address"

    log "Checking topology is set and written to file system."
    check_logs "br$IA_FILE-1"
    diff -q $STATIC_FULL logs/br$IA_FILE-1-topo.json

    log "Setting original topology"
    cp $TOPO $STATIC_FULL

    log "Waiting for revocation to expire."
    sleep 12
    check_connectivity "serve original static topology"

    log "Checking fail action."
    check_br_fail_action "static"
}

check_connectivity_broken() {
    bin/end2end_integration -src $IA -dst $DST_IA -attempts 1 -d -log.console=crit || local failed=$?
    if [ -z ${failed+x} ]; then
        echo "FAIL: Traffic still passes. step=( $1 )"
        return 1
    fi
}

check_connectivity() {
    bin/end2end_integration -src $IA -dst $DST_IA -attempts 5 -d || fail "FAIL: Traffic does not pass. step=( $1 )"
}

check_logs() {
    grep -q "\[discovery\] Set topology.*mode=static" "logs/$1.log" || \
        fail "Setting static topology not found in logs. id=$1"
    grep -q "\[discovery\] Topology written to filesystem.*mode=static" "logs/$1.log" || \
        fail "Writing static topology not found in logs. id=$1"
}

shift
do_command $PROGRAM $COMMAND $TEST_NAME "$@"
