networks:
  bridge1:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: bridge1
    ipam:
      config:
      - subnet: 242.254.100.0/24
  bridge2:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: bridge2
    ipam:
      config:
      - subnet: 242.254.200.0/24
services:
  patha:
    command: [
      "-local_x", "242.254.100.3:50000",
      "-remote_x", "242.254.100.2:30041",
      "-local_y", "242.254.200.3:50000",
      "-remote_y", "242.254.200.2:30041",
      ]
    container_name: patha
    image: bazel/acceptance/sig_short_exp_time:udpproxy
    networks:
      bridge1:
        ipv4_address: 242.254.100.3
      bridge2:
        ipv4_address: 242.254.200.3
  pathb:
    command: [
      "-local_x", "242.254.100.4:50000",
      "-remote_x", "242.254.100.2:30041",
      "-local_y", "242.254.200.4:50000",
      "-remote_y", "242.254.200.2:30041",
      ]
    container_name: pathb
    image: bazel/acceptance/sig_short_exp_time:udpproxy
    networks:
      bridge1:
        ipv4_address: 242.254.100.4
      bridge2:
        ipv4_address: 242.254.200.4
  sig1:
    cap_add:
    - NET_ADMIN
    container_name: sig1
    image: bazel/acceptance/sig_short_exp_time:sig1
    networks:
      bridge1:
        ipv4_address: 242.254.100.2
    privileged: true
    volumes:
    - /dev/net/tun:/dev/net/tun
  sig2:
    cap_add:
    - NET_ADMIN
    container_name: sig2
    image: bazel/acceptance/sig_short_exp_time:sig2
    networks:
      bridge2:
        ipv4_address: 242.254.200.2
    privileged: true
    volumes:
    - /dev/net/tun:/dev/net/tun
  tester1:
    container_name: tester1
    image: alpine
    networks:
      bridge1:
        ipv4_address: 242.254.100.10
    privileged: true
  tester2:
    container_name: tester2
    image: alpine
    networks:
      bridge2:
        ipv4_address: 242.254.200.10
    privileged: true
version: '2.4'
volumes:
  vol_logs: null
