name: sig_short_exp_time
networks:
  bridge1:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: bridge1
    ipam:
      config:
      - subnet: 242.254.100.0/24
  bridge2:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: bridge2
    ipam:
      config:
      - subnet: 242.254.200.0/24
services:
  patha:
    command: [
      "-local_x", "242.254.100.3:50000",
      "-remote_x", "242.254.100.2:30041",
      "-local_y", "242.254.200.3:50000",
      "-remote_y", "242.254.200.2:30041",
      ]
    image: scion/tools/udpproxy:latest
    networks:
      bridge1:
        ipv4_address: 242.254.100.3
      bridge2:
        ipv4_address: 242.254.200.3
  pathb:
    command: [
      "-local_x", "242.254.100.4:50000",
      "-remote_x", "242.254.100.2:30041",
      "-local_y", "242.254.200.4:50000",
      "-remote_y", "242.254.200.2:30041",
      ]
    image: scion/tools/udpproxy:latest
    networks:
      bridge1:
        ipv4_address: 242.254.100.4
      bridge2:
        ipv4_address: 242.254.200.4
  dispatcher1:
    image: scion/dispatcher:latest
    networks:
      bridge1:
        ipv4_address: 242.254.100.2
    volumes:
    - vol_scion_disp_sig1-ff00_0_110:/run/shm/dispatcher:rw
    - ./testdata/1-ff00_0_110/dispatcher:/etc/scion/
    command: [ "--config", "/etc/scion/disp.toml" ]
  dispatcher2:
    image: scion/dispatcher:latest
    networks:
      bridge2:
        ipv4_address: 242.254.200.2
    volumes:
    - vol_scion_disp_sig1-ff00_0_111:/run/shm/dispatcher:rw
    - ./testdata/1-ff00_0_111/dispatcher:/etc/scion/
    command: [ "--config", "/etc/scion/disp.toml" ]
  sig1:
    cap_add:
    - NET_ADMIN
    depends_on:
    - dispatcher1
    image: scion/gateway:latest
    network_mode: service:dispatcher1
    privileged: true
    volumes:
    - vol_scion_disp_sig1-ff00_0_110:/run/shm/dispatcher:rw
    - /dev/net/tun:/dev/net/tun
    - ./testdata/1-ff00_0_110/sig:/etc/scion/
    command: [ "--config", "/etc/scion/sig.toml" ]
  sig2:
    cap_add:
    - NET_ADMIN
    depends_on:
    - dispatcher2
    image: scion/gateway:latest
    network_mode: service:dispatcher2
    privileged: true
    volumes:
    - vol_scion_disp_sig1-ff00_0_111:/run/shm/dispatcher:rw
    - /dev/net/tun:/dev/net/tun
    - ./testdata/1-ff00_0_111/sig:/etc/scion/
    command: [ "--config", "/etc/scion/sig.toml" ]
  tester1:
    image: alpine
    network_mode: service:dispatcher1
    privileged: true
  tester2:
    image: alpine
    network_mode: service:dispatcher2
    privileged: true
version: '2.4'
volumes:
  vol_logs: null
  vol_scion_disp_sig1-ff00_0_110: null
  vol_scion_disp_sig1-ff00_0_111: null
