#!/bin/bash

# This test checks whether the SIG quickly switches paths when one is close to
# expiration.
#
# The test sets up two ASes connected by two paths. The first SCIOND path reply
# only contains the first path, and it has a very short lifetime. Path replies
# after 5 seconds have passed include both paths: the first path with the short
# lifetime, and the second path with the long lifetime. Immediately after the
# short lifetime expires, the first path is taken down and a ping sent out. If
# the failover was correct, this ping should not be lost.

# Docker topology:
#
# +---------------------------+     +---------------------------+
# | dispatcher1 network stack |     | dispatcher2 network stack |
# |    +-----------------+    |     |    +-----------------+    |
# |    |     tester1     |    |     |    |     tester2     |    |
# |    +-----------------+    |     |    +-----------------+    |
# |                           |     |                           |
# |    +-----------------+    |     |    +-----------------+    |
# |    |      sig1       |    |     |    |      sig2       |    |
# |    +-----------------+    |     |    +-----------------+    |
# |                           |     |                           |
# |    +-----------------+    |     |    +-----------------+    |
# |    |   dispatcher1   |    |     |    |   dispatcher2   |    |
# |    |     :30041      |    |     |    |     :30041      |    |
# |    +-----------------+    |     |    +-----------------+    |
# |                           |     |                           |
# |    (route via dev sig)    |     |    (route via dev sig)    |
# |                           |     |                           |
# |      242.254.100.2/24     |     |     242.254.200.2/24      |
# +------------+--------------+     +-------------+-------------+
#              |                                  |
#   +----------+------------+         +-----------+-----------+
#   |        bridge1        |         |       bridge2         |
#   |    242.254.100.1/24   |         |   242.254.200.1/24    |
#   +-+-+-------------------+         +-------------------+-+-+
#     | |                                                 | |
#     | | +---------------------------------------------+ | |
#     | +-+                    patha                    +-+ |
#     |   | 242.254.100.3:50000 <-> 242.254.200.3:50000 |   |
#     |   +---------------------------------------------+   |
#     |                                                     |
#     |   +---------------------------------------------+   |
#     +---+                    pathb                    +----
#         | 242.254.100.3:50000 <-> 242.254.200.4:50000 |
#         +---------------------------------------------+


# --- begin runfiles.bash initialization v2 ---
# Copy-pasted from the Bazel Bash runfiles library v2.
set -uo pipefail; f=bazel_tools/tools/bash/runfiles/runfiles.bash
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null || \
source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null || \
source "$0.runfiles/$f" 2>/dev/null || \
source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
source "$(grep -sm1 "^$f " "$0.exe.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
{ echo>&2 "ERROR: cannot find $f"; exit 1; }; f=; set -e
# --- end runfiles.bash initialization v2 ---

run_test() {(set -e
    # Register with the docker daemon the docker images bazel created
    # (--norun is used for docker images created via go_image because the script runs them by default)
    bash "$(rlocation __main__/go/tools/udpproxy/udpproxy)" --norun
    bash "$(rlocation __main__/acceptance/sig_short_exp_time/dispatcher1)"
    bash "$(rlocation __main__/acceptance/sig_short_exp_time/dispatcher2)"
    bash "$(rlocation __main__/acceptance/sig_short_exp_time/sig1)"
    bash "$(rlocation __main__/acceptance/sig_short_exp_time/sig2)"

    docker-compose -f acceptance/sig_short_exp_time/docker-compose.yml up -d dispatcher1 dispatcher2 sig1 sig2

    # Set up forward route on network stack 1 and 2 through sig tunnel device
    # If this fails, the test is not stopped.
    docker-compose -f acceptance/sig_short_exp_time/docker-compose.yml run --rm tester1 ip route add 242.254.200.2/32 dev sig || true
    docker-compose -f acceptance/sig_short_exp_time/docker-compose.yml run --rm tester2 ip route add 242.254.100.2/32 dev sig || true

    echo "Initial ping tests"
    docker-compose -f acceptance/sig_short_exp_time/docker-compose.yml up -d patha pathb
    docker-compose -f acceptance/sig_short_exp_time/docker-compose.yml run --rm tester1 ping -c 1 242.254.200.2

    echo "Wait for path A to expire..."
    sleep 10

    echo "Shutting down path A"
    docker-compose -f acceptance/sig_short_exp_time/docker-compose.yml stop patha
    echo "Check no ping lost"
    docker-compose -f acceptance/sig_short_exp_time/docker-compose.yml run --rm tester1 ping -c 1 242.254.200.2
)}

set +e
run_test
RC=$?

# Write outputs to bazel directory
OUTPUT_DIR=$TEST_UNDECLARED_OUTPUTS_DIR
mkdir -p $OUTPUT_DIR/logs

for FILE in sig1-ff00_0_110.log sig1-ff00_0_111.log disp_1-ff00_0_110.log disp_1-ff00_0_111.log; do
    docker-compose -f acceptance/sig_short_exp_time/docker-compose.yml run log_exporter cat /share/logs/$FILE > $OUTPUT_DIR/logs/$FILE
done

docker-compose -f acceptance/sig_short_exp_time/docker-compose.yml down

exit $RC
