[general]
id = "cs1-ff00_0_122-1"
config_dir = "gen/ASff00_0_122"

[trust_db]
connection = "gen-cache/cs1-ff00_0_122-1.trust.db"

[beacon_db]
connection = "gen-cache/cs1-ff00_0_122-1.beacon.db"

[path_db]
connection = "gen-cache/cs1-ff00_0_122-1.path.db"

[tracing]
enabled = true
debug = true
agent = "172.17.0.1:6831"

[metrics]
prometheus = "127.0.0.74:30452"

[api]
addr = "127.0.0.74:31152"

[features]

[log.console]
level = "debug"
