#!/bin/bash

set -e

BASE=$(dirname "$0")
. $(dirname "$BASE")/common.sh

[ -z "$("$BASE/check" $1)" ] && exit

echo "Installing necessary packages from pip3"
pip_install pip3 "$BASE/requirements$1.txt"
