#!/bin/bash

ret=0

check() {
    echo "Check: $@"
    # If a check errors, exit immediately.
    output=$("$@") || { echo "ERROR: non-zero result"; exit 1; }
    if [ -n "$output" ]; then
        # If a `check` produced any output, count it as a failure.
        ret=$((ret+1))
        echo "$output"
    fi
}

for f in env/*/check; do
    check "$f"
done

if [ $ret -ne 0 ]; then
    echo "============================================================"
    echo "ERROR: outdated dependencies, scion_base needs to be rebuilt"
    echo "============================================================"
fi
exit $ret
