load("@scion_python_deps//:requirements.bzl", "requirement")
load("//acceptance/common:raw.bzl", "raw_test")
load("//tools/lint:py.bzl", "py_binary", "py_library")

exports_files(
    [
        "conf",
        "test.py",
        "conf/router.toml",
        "conf/topology.json",
        "conf/keys/master0.key",
        "conf/keys/master1.key",
    ],
    visibility = ["//visibility:public"],
)

args = [
    "--executable",
    "brload:$(location //acceptance/router_benchmark/brload:brload)",
    "--executable",
    "coremark:$(location //tools/coremark:coremark)",
    "--executable",
    "mmbm:$(location //tools/mmbm:mmbm)",
    "--docker-image=$(location //docker:router.tarball)",
]

data = [
    ":conf",
    "//docker:router.tarball",
    "//acceptance/router_benchmark/brload:brload",
    "//tools/coremark:coremark",
    "//tools/mmbm:mmbm",
]

# The router benchmarks are excluded from CI. Some underlays require special hardware and
# driver support that CI agents do not provide. The AF_XDP underlay, for instance, falls back
# to XDP_COPY without a driver that supports XDP_ZEROCOPY, which does not measure what the
# benchmark is meant to measure. Performance regression testing is scheduled on baremetal.
raw_test(
    name = "test_afxdp",
    src = "test.py",
    args = args + [
        "--underlay",
        "afxdp",
    ],
    data = data,
    homedir = "$(rootpath //docker:router.tarball)",
    # This test uses sudo and accesses /var/run/netns.
    local = True,
    tags = ["manual"],
    deps = ["benchmarklib"],
)

raw_test(
    name = "test_inet",
    src = "test.py",
    args = args + [
        "--underlay",
        "inet",
    ],
    data = data,
    homedir = "$(rootpath //docker:router.tarball)",
    # This test uses sudo and accesses /var/run/netns.
    local = True,
    tags = ["manual"],
    deps = ["benchmarklib"],
)

test_suite(
    name = "test",
    tags = ["manual"],
    tests = [
        ":test_afxdp",
        ":test_inet",
    ],
)

py_library(
    name = "benchmarklib",
    srcs = ["benchmarklib.py"],
)

py_binary(
    name = "benchmark",
    srcs = ["benchmark.py"],
    args = [
        "--brload",
        "$(location //acceptance/router_benchmark/brload:brload)",
    ],
    data = data,
    imports = ["."],
    visibility = ["//visibility:public"],
    deps = [
        "benchmarklib",
        requirement("plumbum"),
    ],
)
