#!/usr/bin/env python3

# Copyright 2019 Anapaya Systems
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


import logging
import time

from plumbum import local


from acceptance.common.log import LogExec, init_log
from acceptance.common.base import CmdBase, TestBase, set_name, TestState
from acceptance.common.scion import SCIONDocker
from acceptance.common.tools import DC
from lib.util import load_yaml_file, load_sciond_file

set_name(__file__)
logger = logging.getLogger(__name__)


class Test(TestBase):
    """
    Test that showpaths with the -p option works as intended.
    """


class Base(CmdBase):
    pass


@Test.subcommand('setup')
class TestSetup(Base):

    @LogExec(logger, 'setup')
    def main(self):
        self.scion.topology('topology/Tiny.topo')
        self.scion.run()
        if not self.no_docker:
            self.tools_dc('start', 'tester*')
            self.docker_status()
        # give some time for initial setup of control plane
        time.sleep(4)


@Test.subcommand("run")
class TestRun(Base):
    showpaths = local['./bin/showpaths']

    @LogExec(logger, "run")
    def main(self):
        sciond_file = load_sciond_file('gen/sciond_addresses.json')
        if self.no_docker:
            out = self.showpaths('-sciond', "[%s]:%d" % (sciond_file["1-ff00:0:112"], 30255),
                                 '-dstIA', '1-ff00:0:110', '-p')
        else:
            dcFile = load_yaml_file('gen/scion-dc.yml')
            networks = dcFile['services']['scion_disp_cs1-ff00_0_112-1']['networks']
            disp_net = next(iter(networks.items()))[1]
            if 'ipv4_address' in disp_net:
                local_disp = disp_net['ipv4_address']
            else:
                local_disp = disp_net['ipv6_address']
            out = self.tools_dc('exec_tester', '1-ff00_0_112', './bin/showpaths',
                                '-sciond', "[%s]:%d" % (sciond_file["1-ff00:0:112"], 30255),
                                '-dstIA', '1-ff00:0:110', '-p',
                                '-local', local_disp)

        if 'Alive' not in out:
            logger.error("Alive not found in output, output=%s", out)
            return 1
        logger.info("successful")


if __name__ == '__main__':
    init_log()
    Test.test_state = TestState(SCIONDocker(), DC(''))
    Test.run()
