openapi: "3.0.2"
info:
  description: "API for the SCION Router"
  title: Router Service API
  version: "0.0.1"
servers:
  - url: http://{host}:{port}/api/v1
    variables:
      host:
        default: "localhost"
      port:
        default: "30442"
tags:
  - name: interface
    description: Everything related to SCION interfaces.
  - name: common
    description: Common API exposed by SCION services.
paths:
  /info:
    $ref: "../common/process.yml#/paths/~1info"
  /log/level:
    $ref: "../common/process.yml#/paths/~1log~1level"
  /config:
    $ref: "../common/process.yml#/paths/~1config"
  /interfaces:
    $ref: "./interfaces.yml#/paths/~1interfaces"
