#!/bin/bash

. acceptance/lib.sh

cmd_help() {
    echo
	cat <<-_EOF
	    $PROGRAM setup TESTNAME
	        only the setup phase of test TESTNAME.
	    $PROGRAM run TESTNAME
	        only the run phase of test TESTNAME.
	    $PROGRAM teardown TESTNAME
	        only the teardown phase of test TESTNAME.
	    $PROGRAM gsetup
	        global set up of the acceptance testing framework.
	    $PROGRAM grun TESTNAME
	        global run of specific test.
	    $PROGRAM gteardown
	        global teardown of the acceptance testing framework.
	_EOF
}

PROGRAM=`basename "$0"`
COMMAND="$1"
shift 1
ACCEPTANCE_DIR="${ACCEPTANCE_DIR:-"acceptance"}"

test_prog() {
    if [ -f "$ACCEPTANCE_DIR/${TEST}_acceptance/test" ]; then
        TEST_PROGRAM="$ACCEPTANCE_DIR/${TEST}_acceptance/test"
    else
        TEST_PROGRAM="$ACCEPTANCE_DIR/${TEST}_acceptance/test.py"
    fi
} 

case "$COMMAND" in
    setup|run|teardown)
        TEST="$1"
        shift 1
        test_prog
        "$TEST_PROGRAM" $COMMAND "$@";;
    gsetup)
        global_setup ;;
    grun)
        artifacts_dir; stats_failed=0
        TEST="$1"
        test_prog
        global_run_single "$TEST_PROGRAM"
        [ $stats_failed -eq 0 ] ;;
    gteardown)
        global_teardown ;;
    *) cmd_help; exit 1 ;;
esac
