#!/bin/bash

BRID=core-brB
TEST_NAME="core_brB_acceptance"
PROGRAM=$(basename "$0")
COMMAND="$1"
DEVINFO_FN=acceptance/${TEST_NAME}/devinfo.txt
BRUTIL=acceptance/brutil

. $BRUTIL/common.sh
. $BRUTIL/util.sh

# This function is called from test_setup
set_veths() {
    create_veth $NS veth0_root ifid_local 192.168.0.12/24 \
        192.168.0.11 192.168.0.13 192.168.0.51 192.168.0.61 192.168.0.71
    create_veth $NS veth1_root ifid_1401 192.168.14.2/31 192.168.14.3
}

test_run() {
    set -e
    bin/braccept -borderID "$BRID" -devInfoFilePath "$DEVINFO_FN" \
        -keysDirPath "$BRUTIL/br-core-conf/keys" $@
}

# This function is called from test_teardown
del_veths() {
    delete_veth veth0_root veth1_root
}

do_command $PROGRAM $COMMAND $TEST_NAME
