#!/bin/bash

TEST_NAME="sig"
TEST_TOPOLOGY="topology/Tiny.topo"

. acceptance/common.sh

test_setup() {
    set -e
    ./scion.sh topology zkclean -c $TEST_TOPOLOGY -d --sig -n 242.254.0.0/16
    ./scion.sh run nobuild
    ./tools/dc start 'tester*'
    sleep 10
}

test_run() {
    ./bin/sig_ping_acceptance -d -log.console info
}

test_teardown() {
    set -e
    METRICS="${ACCEPTANCE_ARTIFACTS:?}/$TEST_NAME/metrics"
    collect_metrics "gen/ISD1/ASff00_0_110/br1-ff00_0_110-1/topology.json" "$METRICS"
    collect_metrics "gen/ISD1/ASff00_0_111/br1-ff00_0_111-1/topology.json" "$METRICS"
    collect_metrics "gen/ISD1/ASff00_0_112/br1-ff00_0_112-1/topology.json" "$METRICS"
    ./tools/dc down
}

print_help() {
    echo
	cat <<-_EOF
	    $PROGRAM name
	        return the name of this test
	    $PROGRAM setup
	        execute only the setup phase.
	    $PROGRAM run
	        execute only the run phase.
	    $PROGRAM teardown 
	        execute only the teardown phase.
	_EOF
}

PROGRAM=`basename "$0"`
COMMAND="$1"

case "$COMMAND" in
    name)
        echo $TEST_NAME ;;
    setup|run|teardown)
        "test_$COMMAND" ;;
    *) print_help; exit 1 ;;
esac
