#!/bin/bash

BRID=core-brA
TEST_NAME=$(basename $(dirname "${0:?}") _acceptance)
PROGRAM=$(basename "${0:?}")
COMMAND="${1:?}"

. acceptance/brutil/common.sh

# This function is called from test_setup
set_veths() {
    create_veth veth_int_host veth_int 192.168.0.11/24 f0:0d:ca:fe:00:01 \
        192.168.0.12 192.168.0.13 192.168.0.51 192.168.0.61 192.168.0.71
    create_veth veth_141_host veth_141 192.168.14.2/31 f0:0d:ca:fe:00:14 192.168.14.3
}

# This function is called from test_teardown
del_veths() {
    delete_veth veth_int_host veth_141_host
}

shift
do_command $PROGRAM $COMMAND $TEST_NAME "$@"
