#!/bin/sh -e

LANG=C
export LANG

build="`pwd`/build"
rm -rf "${build}"

[ -f tweetnaclmodule.c ] || ( python tweetnaclmodule.c.py > tweetnaclmodule.c )

(
  for i in 3 4 5 6 7 8 9
  do
    for j in 0 1 2 3 4 5 6 7 8 9
    do
        "python${i}.${j}" </dev/null 2>/dev/null || continue
        echo "python${i}.${j}"
    done
  done
) \
| while read python
do
  #loop over python versions
  echo "=== `date` === ${python}: starting"
  mkdir -p "${build}/work/${python}"
  cp *.c *.h *.py "${build}/work/${python}"
  (
    cd "${build}/work/${python}"
    compiler=`${python} compiler.py`
    linker=`${python} linker.py`
    echo "=== `date` === ${python}: compiling"
    ls *.c | sort |\
    while read fn; do
      ${compiler} -c "${fn}" || exit 111
    done || exit 111
    echo "=== `date` === ${python}: linking"
    ${linker} -o tweetnacl.so *.o || exit 111
    ls test_*.py | sort |\
    while read name; do
      echo "=== `date` === ${python}: testing ${name}"
      "${python}" "${name}" || exit 111
    done || exit 111
    mkdir -p "${build}/${python}"
    cp tweetnacl.so nacl.py "${build}/${python}"
    echo "=== `date` === ${python}: finished: ${build}/${python}/tweetnacl.so"
  ) || ( echo "=== `date` === ${python}: failed" )
done
rm -rf "${build}/work"
exit 0
