#!/bin/bash

BRID=brB
TEST_NAME="${BRID}_acceptance"
PROGRAM=$(basename "${0:?}")
COMMAND="${1:?}"
BRUTIL=acceptance/brutil
BRCONF_DIR=br-conf

. $BRUTIL/common.sh

# This function is called from test_setup
set_veths() {
    create_veth veth0_root ifid_local 192.168.0.12/24 \
        192.168.0.11 192.168.0.13 192.168.0.14 192.168.0.51 192.168.0.61 192.168.0.71
    create_veth veth1_root ifid_141 192.168.14.2/31 192.168.14.3
}

# This function is called from test_teardown
del_veths() {
    delete_veth veth0_root veth1_root
}

shift
do_command $PROGRAM $COMMAND $TEST_NAME "$@"
