---
version: "2.4"
services:
  go-module-proxy:
    container_name: go-module-proxy
    network_mode: host
    image: $REGISTRY/gomods/athens:v0.11.0
    environment:
      ATHENS_PORT: 3200
      ATHENS_STORAGE_TYPE: "s3"
      AWS_REGION: $ATHENS_S3_REGION
      AWS_ACCESS_KEY_ID: $ATHENS_S3_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $ATHENS_S3_SECRET_ACCESS_KEY
      ATHENS_S3_BUCKET_NAME: $ATHENS_S3_BUCKET
