#!/bin/bash


if [ -f ".buildkite/hooks/bazel-remote.yml" -a -z "$PRE_COMMAND_SETUP" ]; then
    echo "--- Uploading bazel-remote and go-module-proxy logs/metrics"
    curl http://localhost:8080/metrics > bazel-remote-cache.metrics
    docker logs bazel-remote-cache &> bazel-remote-cache.log

    curl http://localhost:3200/metrics > go-module-proxy.metrics
    docker logs go-module-proxy &> go-module-proxy.log

    buildkite-agent artifact upload "bazel-remote-cache.*;go-module-proxy.*"
fi

echo "--- Cleaning up the topology"

./scion.sh topo_clean

echo "--- Cleaning up docker containers/networks/volumes"
cntrs="$(docker ps -aq | grep -v -f <(docker ps -q --filter "name=go-module-proxy" --filter "name=bazel-remote-cache"))"
[ -n "$cntrs" ] && { echo "Remove leftover containers..."; docker rm -f $cntrs; }

echo "Remove leftover networks"
docker network prune -f
echo "Remove leftover volumes"
docker volume prune -f

echo "--- Cleaning up packages and logs"

rm -f scion-utils-{rpm,deb}.{version,release}
rm -rf bazel-testlogs logs/* traces gen gen-cache /tmp/test-artifacts
