#!/bin/bash

echo "--- Cleaning up the topology"

./scion.sh topo_clean

echo "--- Cleaning up docker containers/networks/volumes"
remote_cache=$(docker ps -q -f name=bazel-remote-cache)
if [ -z ${remote_cache#+x} ]; then
    cntrs="$(docker ps -aq)"
else
    cntrs="$(docker ps -aq | grep -v $remote_cache || true)"
fi
[ -n "$cntrs" ] && { echo "Remove leftover containers..."; docker rm -f $cntrs; }

echo "Remove leftover networks"
docker network prune -f
echo "Remove leftover volumes"
docker volume prune -f

echo "--- Cleaning up packages and logs"

rm -f scion-utils-{rpm,deb}.{version,release}
rm -rf bazel-testlogs logs/* traces gen gen-cache /tmp/test-artifacts
