#!/bin/bash

set -euo pipefail

. .buildkite/hooks/pre-exit

echo "--- Setting up bazel environment"

# ACCEPTANCE_ARTIFACTS is used for acceptance tests built with the "old"
# acceptance framework
export ACCEPTANCE_ARTIFACTS=/tmp/test-artifacts

if [ -z ${BAZEL_REMOTE_S3_ACCESS_KEY_ID+x} ]; then
    echo "S3 env not set, not starting bazel remote proxy"
    exit 0
fi

rm -f $HOME/.bazelrc
# Create a custom .bazelrc file in the home directory it takes precedence over
# the workspace rc file.
# We explicitly override --[no]stamp flag.
# --nostamp is required for better caching (only on non-release jobs).
if [ "$BUILDKITE_PIPELINE_SLUG" == "scion" ]; then
    echo "build --nostamp" > $HOME/.bazelrc
    # Also set a fixed GIT_VERSION so that the workspace_status_command always
    # returns the same value on CI to improve cache reuse.
    export GIT_VERSION="ci-fixed"
else
    echo "build --stamp" > $HOME/.bazelrc
fi

echo "--- Starting bazel remote cache proxy"

# Start bazel remote cache proxy for S3
# Note that S3 keys are injected by buildkite, see
# https://buildkite.com/docs/pipelines/secrets#storing-secrets-with-the-elastic-ci-stack-for-aws
docker run -e BAZEL_REMOTE_S3_BUCKET=$BAZEL_REMOTE_S3_BUCKET\
           -e BAZEL_REMOTE_S3_ENDPOINT=s3.eu-central-1.amazonaws.com\
           -e BAZEL_REMOTE_S3_ACCESS_KEY_ID=$BAZEL_REMOTE_S3_ACCESS_KEY_ID\
           -e BAZEL_REMOTE_S3_SECRET_ACCESS_KEY=$BAZEL_REMOTE_S3_SECRET_ACCESS_KEY\
           --net=host --name bazel-remote-cache -d buchgr/bazel-remote-cache\
           --max_size=5 --experimental_remote_asset_api
