// Copyright 2019 Anapaya Systems
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package pathdb

import (
	"crypto/sha256"
	"encoding/json"

	"github.com/scionproto/scion/go/lib/common"
	"github.com/scionproto/scion/go/lib/pathpol"
)

// PolicyHash is the hash of a policy.
type PolicyHash []byte

// NoPolicy should be used instead of nil when inserting policy hashes into
// fields which can't be null in the DB.
// The value is generated by running the TestNoPolicy, and copying the expected
// output to this field.
var NoPolicy = PolicyHash{0xb3, 0x2d, 0xa8, 0xff, 0x2e, 0x93, 0x66, 0x55, 0xe6,
	0x25, 0xee, 0xb6, 0xf1, 0x57, 0x4, 0x2e, 0xfd, 0x11, 0x2e, 0x5c, 0xb4, 0xa7,
	0xad, 0x40, 0xbe, 0xdc, 0x3d, 0x76, 0x57, 0x6e, 0x96, 0x63}

// HashPolicy creates a sha256 hash of the json serialized policy, note that
// this relies on the fact that JSON serialization for Go is predictable, i.e.
// marshalling the same struct twice returns the same JSON.
func HashPolicy(policy *pathpol.Policy) (PolicyHash, error) {
	pol := policy
	if pol == nil {
		pol = &pathpol.Policy{}
	}
	jsonPol, err := json.Marshal(pol)
	if err != nil {
		return nil, err
	}
	h := sha256.New()
	h.Write(jsonPol)
	return h.Sum(nil), nil
}

func (h PolicyHash) String() string {
	return common.RawBytes(h).String()
}
