# -*- mode: ruby -*-
# vi: set ft=ruby
Vagrant.require_version ">= 1.9.1"

Vagrant.configure(2) do |config|
  config.vm.hostname = "b1"
  config.vm.box = "ubuntu/xenial64"
  # Link between b1 and a1
  config.vm.network "private_network", ip: "169.254.0.2", virtualbox__intnet: "gwnet"
  # Link between b1 and b2 (endhost)
  config.vm.network "private_network", ip: "169.254.2.1", virtualbox__intnet: "gwnet-b"
  config.vm.synced_folder '.', '/vagrant'
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end
end
