#!/bin/bash

set -ex

echo "buildkite-agent ALL=(ALL)NOPASSWD:ALL" | sudo tee --append /etc/sudoers > /dev/null
sudo ln -s /dev/shm/ /run/shm

# Install docker 18.06
sudo yum install docker-18.06* -y
