#!/bin/bash

. $BASE/steps/common.sh

set -eu

TAG="$BUILDKITE_BUILD_NUMBER"

$BASE/scripts/registry_login &>/dev/null

images="border dispatcher dispatcher_go sig beacon beacon_py cert cert_py path path_py sciond sciond_py tester sig_acceptance"

if [ "${1:?}" == "push" ]; then
    # Tag local apps and push to remote
    log "Push images"
    for app in $images; do
        local_img="scion_$app"
        remote_img="$REGISTRY/$app"
        docker tag "$local_img:latest" "$remote_img:$TAG"
        docker push "$remote_img:$TAG" &>/dev/null
    done
fi
if [ "$1" == "pull" ]; then
    # Pull images
    log "Pull images"
    for app in $images; do
        local_img="scion_$app"
        remote_img="$REGISTRY/$app"
        docker pull "$remote_img:$TAG" &>/dev/null
        docker tag "$remote_img:$TAG" "$local_img:latest"
    done
fi
