#!/bin/bash

. $BASE/steps/common.sh

set -eu

# Set tag if not already set in environment
TAG=${TAG:-$BUILDKITE_BUILD_NUMBER}

mkdir -p "artifacts.out"

c_images="dispatcher" # for sig acceptance tests #2416
go_images="border dispatcher_go sig beacon cert path sciond"
tester_images="tester sig_acceptance"
images="$c_images $go_images $tester_images"

if [ "${1:?}" == "push" ]; then
    # Tag local apps and push to remote
    log "Push images"
    for app in $images; do
        local_img="scion_$app"
        remote_img="$REGISTRY/$app"
        log "Push $remote_img:$TAG" &>> "$STEP_LOG"
        docker tag "$local_img:latest" "$remote_img:$TAG"
        docker push "$remote_img:$TAG" &>> "$STEP_LOG"
    done
fi
if [ "$1" == "pull" ]; then
    # Pull images
    log "Pull images"
    for app in $images; do
        local_img="scion_$app"
        remote_img="$REGISTRY/$app"
        log "Pull $remote_img:$TAG" &>> "$STEP_LOG"
        docker pull "$remote_img:$TAG" &>> "$STEP_LOG" || exit 5
        docker tag "$remote_img:$TAG" "$local_img:latest"
    done
fi
