#!/bin/bash

set -eu

TAG="$BUILDKITE_BUILD_NUMBER"

$BASE/scripts/registry_login

images="border dispatcher sig beacon_py cert cert_py path path_py sciond sciond_py tester"

if [ "${1:?}" == "push" ]; then
    # Tag local apps and push to remote
    for app in $images; do
        local_img="scion_$app"
        remote_img="$REGISTRY/$app"
        docker tag "$local_img:latest" "$remote_img:$TAG"
        docker push "$remote_img:$TAG" &>/dev/null
    done
fi
if [ "$1" == "pull" ]; then
    # Pull images
    for app in $images; do
        local_img="scion_$app"
        remote_img="$REGISTRY/$app"
        docker pull "$remote_img:$TAG" &>/dev/null
        docker tag "$remote_img:$TAG" "$local_img:latest"
    done
fi
