#!/bin/bash

set -e

BASE_IMG=${BASE_IMG:-d1a7753613a484c212f8695b55260e664dbd6c8d906ffa789645ecc8d2897c55}

docker pull scionproto/scion_base@sha256:$BASE_IMG
docker tag scionproto/scion_base@sha256:$BASE_IMG scion_base:latest
./docker.sh build
