#!/bin/bash

set -e

BASE_IMG=${BASE_IMG:-1ee983194f283860bd47e57ef69bf2d274bfbb40ebc545031e574c282bfa6b97}

docker pull scionproto/scion_base@sha256:$BASE_IMG
docker tag scionproto/scion_base@sha256:$BASE_IMG scion_base:latest
./docker.sh build
