#!/bin/bash

set -e

BASE=$(dirname "$0")
. $(dirname "$BASE")/common.sh

[ -z "$("$BASE/check")" ] && exit

tmpdir=$(mktemp -d /tmp/zlog.XXXXXXX)
cd "${tmpdir:?}"
curl -L https://github.com/HardySimpson/zlog/archive/1.2.12.tar.gz | tar xzf - --strip-components=1
make -j6
echo "ldconfig" >> postinstall-pak
echo "ldconfig" >> postremove-pak
sudo checkinstall -D --pkgname zlog --nodoc -y --deldoc --deldesc --strip=no --stripso=no --pkgversion 1.2.12
sudo rm *deb
cd -
rm -r "${tmpdir:?}"
