// Package mgmtapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package mgmtapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FpZc+M2Ev4rXUweNhXq8rGJ9aaRNRNV5nBZSrYqsdcFkS0RMyTAAKBsrVf/fQsASfGSRXkms87WTs2D",
	"RQKNxoevG33w0fF4FHOGTEln+OgIlDFnEs2PV8S/xj8SlEr/8jhTyMyfJI5D6hFFOet9lJzpZ9ILMCL6",
	"r28FLp2h801vJ7pn38reTBHmE+FPhODC2W63ruOj9ASNtTBnqNcEkS6q36YTtdwxCkWXel3UP2PBY/3E",
	"6upTqShbJVQG6N8xEpkxahOjM3SkEpStnK3rUOnfWWlPaTmV/kjq4TJZfERP3X3CzR0JV1xPxAcSxaEW",
	"OxlfzkaOW1+lOI36BzGxo3/GzfRSz16TkPpUbQ7N+zUbp3HSmFGBvjP8vQmLfOcF8Q3bq6l+6zqKKrPb",
	"AvxQPLN8/9zM1DsYB4Sy+hlRKRMUh7ZVPOYdlkfNquCRiXAzDfbsytNqt9rbK0G1KrUNHjxrM9seczs0",
	"qlRsPf6zWUT9HR120BUEF1A0eID3LCynl2WrWpLzU9I/I47rLLmIiHKGToAPndS8njq6qY9MPzJ61qzy",
	"Jx43HBlTKJbEw5ISZyf5fD1gheJo51FFMzO/3YIF/K6ICkDiKkKmIOBxE1hWbgmqQWe57PeH/eFg0Hdc",
	"JyZKodBe9J83N/73nb/9TjrLfufi9nHgnm2H3z2ebMuPvvu3HvdtAdPp7LIzmh0A8i1fvcU1hnU0w+xx",
	"2am/5asVZSuwr10HWRIZR4WLZGUwWWrfg+ZSuHULO0zfVFSoYGvF3jZgdiX4IsSo4bpARWiDpiMIkogw",
	"EEh8sggR8CEOCTNXHcgYPU04UBxUQCVwz0uEQOYh8CWoACG2C4IKiAIqIcAwXiahnhFyw9TiKMJ8WNE1",
	"AvHXVAthEPB7PTgW3EP0u/APQZVCBpTBhK1CKgMzK9dvyQUgW1GGKKQLiUxIGG6AcQUyoQp9M4JxBgq9",
	"gFGPhCAV+YQBD30U0kjTo7V6If0X+l2neABjzhh6ZvuKg08UWRCJoGiEPvBENfGDMqkIsyZVhfeX6ykI",
	"XKJFzcKUkU0acHKU96LrAnZXXVhsgPi+5hWBpSDWeHJhArgAmSw6sbYtc2KF49nE2IV3ZAMLhESiXzkg",
	"wbmyi1KZT6LM6scT4SF43McyVL10YM/LMesYSn+j+CdkHc3ljj64jkGvY9HLfVwiaCdHpjGqUEQlsg7q",
	"PED4aT6/AjvAaAYrZCiIPv/FxqjNBV1RBhLFGoUhxdMULu3tvH/qOhF5oJE23POLC9eJKLO/Bv1+k7NM",
	"PUqdATLgQpMziojY1OzGHMx/m/QzFMYef2FkTWio12w6EPtA73BJklCfIVnwRA0XIWGfHLcN9xNG/0gw",
	"3FSNoIgHcKYHWPaZKPxBFXBbUx99GF1Nu/AhjnlK5qIlWe9FGVy/Hnd++LH/gwvUeCeGVAUoQKDHowiZ",
	"b+cudICXKWoA13jFnDKlXxPrIzv5cfjcS7Tx2XUYF7AK+cIcid1fSrfKMbczniNMpBr2WXvJqNh0P8zs",
	"lVu/H/AhpoLYk3vcKeAThcZ6m+gQ8NiGFAqjg1GCDkZyCjlECLIxrvNwtmBVtjFkSKS6S2Ktlt9eUf1c",
	"KhLFbac0RYY7IW4RrYpOKSqFUGc2nn54D3Ex4DkQJaY73hNzI/PvjszqjgUZ2UoFDVGNeZ5ZYrqZEqsH",
	"TY5RKiLU3WfFkiYyL4pxizDkGtcC9GdjX4vRF2fn/tmZfzBGT+cfCCjLVYH6EWePy/ib0RChlGR1mLR5",
	"cFnfYzH/Lm3zxwt4dQFnFzA+gZPX+v/FGC4voX8JJyM4/wFGF3A5gR8n5tU5vD6F/gUM+nA5KCIjY+Kh",
	"3ykDVMVgfj2u75wkKuCCas+6xjuS1mVaOZic7VUX43HxpUSVzqOp2nLQ0ObX4y9U9DBGUaht7LbpNsFY",
	"Vr5gKfPr8SGjmF+Pn10ASDdcV75mrO0UsZQta6Ej9DuWRAtbXnjaHVHpt0h9JQpKwiahp/Xh9dTXcUtK",
	"VeVV4G9yFrtN/1pgSnnfjKs7slQVBZ2T/slJpz/o9M/m/Yvh+cXw9PS3onk+eVdqmQtccoE1oYNnCq3A",
	"U1jBLWyhgEm2Y4hRUO7XQdlu0xy65iOzSHZ0Nc2DMHsLXBKMLKtKF7N9rMdrc0IhrZx+t98daDx4jIzE",
	"1Bk6p91+98RWHQIDf69Q/zEPVqgabk0qlY1kTd6hwg0QT9tlvXwkbYxMBMInxu9ZGtfeMB0ECx6aZIZ6",
	"2AWdAgmUSajAI0wHsEsaKhQ2/bFFjS68ToQOdyMu0L1hnKEZHBMpgUBMhKJeEhKRRro64KYRAlFwH1Av",
	"sErvdLxhqZJaP+N4gEigLE5UF0aw4DxEwjJ98kBdcRCoEsGAhOENK2LmgsAVEX6IUqZhBRXpoevfOhcx",
	"ROje6IPT1DdB19R3hs4bVOMi/vpgBIlQoZDO8PdHh2r0/0hQaO9oC+S7qlS76n0ejjRLMyDcEVWS184i",
	"mgWSMCzJSqel0Drb7a1b7lic9PtHtSpaXX+Fim/tDqw3MAy/eUMx1NygZ08qmOZA3x/XU8mKXA3KTJkl",
	"ZqmjYjPvkinWdXUdRVaaOI4Xx5+oc6unliy892iGdqi/3Wvsb3DPAsYZEVP8YpCWgQ+zeg+ptQfakSbT",
	"yim6WSUSbMvyvEb/2fQ6uErTmdXK2i+ON3tP9TjW9BYhXzyDOsg8rj0pkXA1eQeLjUIJWtbzSPVKa/Gi",
	"ifXQiTHqLGlYiUE6+t+ryZvpexhPrufT19PxaD4xT2/YaFYkUrfbvWHmzeT9ZcPoJ0WNR8eIclpQ2hzX",
	"X4fXVt095OZsSVcFGte5ZkccPHKFD6oXh2nrtHbr5ZdlbVezxPNQymUSwods8QK4TVjlqvQKTf4yGleC",
	"MmWrkfMP796C3Whixev4ylTwckh4pMNJi0kWi+5DZGq7On8tPF4RST3QW9MBjcYgJisEU/LNS7OFqNT2",
	"cKTci1LIV728YbYPqrzX9ideRfkaXw1LbWlhpSlYw8h14qQBlFkFFCP/Ffc3XwWPrJVZXH93E2z/p05p",
	"1uaUNJPTYmKLpK9egdyT5DXldrIpuTNjFRHKNCmQ+TCaVWuyMGUyRs+qQJlP19RPSLhTwQYOOjEE2xlG",
	"H9YU77tNscMs220taKgcitEq7ajzZWOFuNrCb8qCKpXeo1O1SrcQRUQZCeEJpU4ypU72KlWqNx+n0ldJ",
	"2kpNgyPStogoL9CEb2Bq9+VmcA3aFow1fVSx1t5j+leWwvkYomro2V6a53vWgXuqbG3Ext3Z4+ll3Xis",
	"oKzpdsB85jsDhull3vAsLN2F6TI16ThRsCZhgkCl7TCj0I6FASkIyfqeHmeS+saDEIgFLumD8R4kDHcE",
	"KDspYlyDVt/XLolKLSeRqF2u9h7mXX3agkj0gbO0lpN5U62KLSpRG2ENTkwekymTbpZ4quCmIMtm8CEO",
	"uY/OcElCiW5TrrI72WdnK6UemFQb4xkkNS6iwYbPGoqPTe0mA+FLMCTXOf/aGigU2vPO7DcY2TewRYN+",
	"0tQaLdp9On0uPNWsIrvPa+ryn7rt6tb6Iln45cKtbN9N0Vad14W0oPti89rD7d/290W74k3DinurN0+x",
	"r7lG85djYItCztVo/hPMJm/eTd7P04KKAfGKqCBrppcrMA0znFacfdE1mH367iOpEl6L9CMkCqVKhc9F",
	"IhVcc65gXKxt2HQAiRfo4H1PenJ8C6oLH4w+JAw3rgk15tfjPKVJ0UAfKJMKiWn4mA+/CnpzhrLRTOZ6",
	"9+3so94BKgXweXDd8EVfpfuf2YL2fM7LbuHkHfsjMoF02UWI5qC6n59P5zTU8vaUEzWPe1T6j1T6287i",
	"UQeQ2458tA3zbUuPu4/ae6rhc+G1qoBbsux3o09+RJAzpCxTb7Cd0EFrmRasdlKbvl/4M+OK+fW4iXXz",
	"63H3y9TVUoI9j1/HXOv7SJZd7dlNbxIbc8PvZV/rHsz/GfjMuGJ+PU6Dg98+ju4/fBz9/d18cj+txBK7",
	"UU4jRasxw+fTdG9rxX50tM64kIjQGTqBUvGw13sMuFTb4WPMhdr2SEx764H5+ktQ7a8NYnpI+eNs87G3",
	"ebx1HT21/Pp0MDg/0aZ5m2tT5f/YFD3NxzT4YD+1XmxSa0gDAXM/Zw1DWyOt1+AmaxQbZaoMAkPzlb7i",
	"zRWnaiR7pLTx1dXPU4iIMnws6mZw3t5u/xMAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
