#!/bin/bash

# Whenever the CS addresses in the topology file of a SD server are changed, if
# the SD process receives a SIGHUP it will reload the config and get future
# certificate chains from the new address.

. acceptance/common.sh

TEST_NAME="topo_sd_reloads_cs"
TEST_TOPOLOGY="topology/Tiny.topo"

SRC_IA=${SRC_IA:-1-ff00:0:112}
SRC_IA_FILE="$(ia_file $SRC_IA)"
SRC_AS_FILE="$(as_file $SRC_IA)"
DST_IA=${DST_IA:-1-ff00:0:110}

test_setup() {
    set -e
    ./scion.sh topology zkclean -c $TEST_TOPOLOGY -d -sd=go -ps=go
    for sd in gen/ISD1/*/endhost/sciond.toml; do
        sed -i 's/Level = .*$/Level = "trace"/g' "$sd"
        sed -i '/\[logging\.file\]/a FlushInterval = 1' "$sd"
    done
    ./scion.sh run nobuild
    ./tools/dc start tester_$SRC_IA_FILE
    docker_status
}

test_run() {
    set -e
    ./tools/dc exec_tester $SRC_IA_FILE bin/showpaths -srcIA $SRC_IA -dstIA $DST_IA -sciondFromIA || true
    local topo_file="gen/ISD1/AS$SRC_AS_FILE/endhost/topology.json"
    jq '.CertificateService[].Addrs.IPv4.Public = {Addr: "127.42.42.42", L4Port: 39999}' $topo_file | sponge $topo_file
    ./tools/dc dc kill -s HUP scion_sd$SRC_IA_FILE
    sqlite3 gen-cache/sd$SRC_IA_FILE.trust.db "delete from chains"
    sleep 1
    ./tools/dc exec_tester $SRC_IA_FILE bin/showpaths -srcIA $SRC_IA -dstIA $DST_IA -sciondFromIA -refresh || true
    sleep 2
    grep -q "\[TRACE\] \[Messenger\] Sending request .*req_type=ChainRequest .*$SRC_IA,\[127\.42\.42\.42\]:39999" "logs/sd$SRC_IA_FILE.log" || \
        { echo "Certificate chain request to 127.42.42.42:39999 not found in logs"; return 1; }
}

print_help() {
    echo
	cat <<-_EOF
	    $PROGRAM name
	        return the name of this test
	    $PROGRAM setup
	        execute only the setup phase.
	    $PROGRAM run
	        execute only the run phase.
	    $PROGRAM teardown
	        execute only the teardown phase.
	_EOF
}

PROGRAM=`basename "$0"`
COMMAND="$1"

case "$COMMAND" in
    name)
        echo $TEST_NAME ;;
    setup|run|teardown)
        "test_$COMMAND" ;;
    *) print_help; exit 1 ;;
esac

