#!/bin/bash

export BRACCEPT_ARGS=-bfd
export DOCKER_COMPOSE_FN=acceptance/br_bfd_acceptance/dc.yml
BRID=brA
TEST_NAME=$(basename $(dirname "${0:?}") _acceptance)
PROGRAM=$(basename "${0:?}")
COMMAND="${1:?}"

. acceptance/brutil/common.sh

# This function is called from test_setup
set_veths() {
    create_veth veth_int_host veth_int 192.168.0.11/24 f0:0d:ca:fe:00:01 \
        192.168.0.12 192.168.0.13 192.168.0.14 192.168.0.51 192.168.0.61 192.168.0.71
    create_veth veth_131_host veth_131 192.168.13.2/31 f0:0d:ca:fe:00:13 192.168.13.3
}

# This function is called from test_teardown
del_veths() {
    delete_veth veth_int_host veth_131_host
}

shift
do_command $PROGRAM $COMMAND $TEST_NAME "$@"
