#!/bin/bash

set -x
git submodule sync --recursive
git submodule update --init --recursive
# Ensure none of the dependency information has changed
# since scion_base was last built.
./docker/deps_check
# Restore the go dependency cache from scion_base
tar xf /tmp/build/go_vendor.tar.gz -C go/vendor/
# Syncing should be a no-op, just need installation to run
make -C go deps
cp sub/web/web_scion/settings/private.dist.py sub/web/web_scion/settings/private.py
./sub/web/manage.py makemigrations
./scion.sh topology
