#!/bin/bash

set -ex

./docker.sh exec "set -eo pipefail; (
                    cp go.mod go.sum go_deps.bzl /tmp/;
                    make godeps -B;
                    bazel-scion/external/go_sdk/bin/go mod tidy;
                    diff -u /tmp/go.mod go.mod;
                    diff -u /tmp/go.sum go.sum;
                    diff -u /tmp/go_deps.bzl go_deps.bzl;
                  ) |& tee logs/checkgodeps.run"
