#!/bin/bash

set -ex

docker cp ${1:-scion_ci}:/home/scion/go/src/github.com/scionproto/scion/logs "${2:?"Directory needs to be specified!"}"
docker cp ${1:-scion_ci}:/home/scion/go/src/github.com/scionproto/scion/gen "$2"

docker stop ${1:-scion_ci}
