#!/bin/bash

set -ex

# Update docker to 18.06
sudo apt-get update && sudo apt-get install --only-upgrade docker-ce=18.06.0~ce~3-0~ubuntu

# Update docker-compose to 1.22.0
case "$(uname -m)" in
    x86_64)
        src=https://github.com/docker/compose/releases/download/1.22.0/docker-compose-Linux-x86_64
        sum=f679a24b93f291c3bffaff340467494f388c0c251649d640e661d509db9d57e9
        file=/usr/local/bin/docker-compose
        ;;
    *)
        echo "ERROR: unsupported architecture '$(uname -m)'"
        exit 1
esac
sudo curl -L "$src" -o "$file"
echo "$sum $file" | sha256sum -c -
sudo chmod +x "$file"
