#!/bin/bash

set -ex

# Update docker to 18.06
sudo apt-get update && sudo apt-get install --only-upgrade docker-ce=18.06.0~ce~3-0~ubuntu

# Update docker-compose to 1.22.0
sudo curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
echo "f679a24b93f291c3bffaff340467494f388c0c251649d640e661d509db9d57e9 /usr/local/bin/docker-compose" > sha.txt; sha256sum --check sha.txt; rm sha.txt
sudo chmod +x /usr/local/bin/docker-compose
