#!/bin/bash

. tools/ci/common.sh
set -eo pipefail

# FIXME(worxli): host zk should be properly isolated from dockerized zk
./docker.sh exec "set -x; ./scion.sh topology -sd=go -ps=go ${DOCKER:+zkclean -d}"

if [ -n "$DOCKER" ]; then
    ./docker.sh exec "set -eo pipefail; ./integration/integration_test.sh |& tee logs/integration.run"
else
    # Run tests inside the CI container.
    ./docker.sh exec "set -eo pipefail; sudo service zookeeper start; ./integration/integration_test.sh |& tee logs/integration.run"
fi
