#!/bin/bash

. tools/ci/common.sh
set -e

./docker.sh exec "set -x; ./scion.sh topology ${DOCKER_BE:+ -d -n 172.21.0.0/16 -c topology/Tiny.topo}"
./docker.sh exec "set -eo pipefail; ./scion.sh run nobuild | grep -v "started" |& tee -a logs/integration.run"
./docker.sh exec "set -eo pipefail; ./scion.sh status |& tee -a logs/integration.run"
if [ -n "$DOCKER_BE" ]; then
    ./docker.sh exec "set -eo pipefail; ./tools/dc start tester* |& tee -a logs/integration.run"
fi
