#!/bin/bash

set -e

sleep 15

if [ -n "$DOCKER" ]; then
    ./docker.sh exec "set -eo pipefail; sudo service zookeeper start; |& tee logs/integration.run"
fi

# Run go infra test
./docker.sh exec "set -eo pipefail; integration/go_infra |& tee logs/integration.run"
result=$((result+$?))

if [ -n "$ALL" ]; then
# Run python integration tests
./docker.sh exec "set -eo pipefail; integration/py_integration |& tee logs/integration.run"
result=$((result+$?))
fi

# Run go integration tests
./docker.sh exec "set -eo pipefail; integration/go_integration |& tee logs/integration.run"
result=$((result+$?))

./docker.sh exec "set -eo pipefail; integration/revocation_test.sh |& tee logs/integration.run"
result=$((result+$?))

./docker.sh exec "set -eo pipefail; ./scion.sh status && scion.sh stop |& tee logs/integration.run"

if [ $result -eq 0 ]; then
    log "All integration tests successful"
else
    log "$result integration tests failed"
fi
exit $result
