#!/bin/bash

. tools/ci/common.sh

sleep 15
result=0

if [ -z "$DOCKER_BE" ]; then
    # Go infra tests
    ./docker.sh exec "set -eo pipefail; integration/go_infra |& tee -a logs/integration.run"
    result=$((result+$?))
fi

# Go integration tests
./docker.sh exec "set -eo pipefail; integration/go_integration |& tee -a logs/integration.run"
result=$((result+$?))

if [ -n "$ALL" ]; then
    # Python integration tests
    ./docker.sh exec "set -eo pipefail; integration/py_integration |& tee -a logs/integration.run"
    result=$((result+$?))
fi

# Revocation test
./docker.sh exec "set -eo pipefail; integration/revocation_test.sh |& tee -a logs/integration.run"
result=$((result+$?))

if [ $result -eq 0 ]; then
    echo "========> ($(date -u --rfc-3339=seconds)) All integration tests successful"
else
    echo "========> ($(date -u --rfc-3339=seconds)) $result integration tests failed"
fi

# Stop scion
./docker.sh exec "set -eo pipefail; { ./scion.sh status && ./scion.sh stop; } |& tee -a logs/integration.run"

# Make sure all compose controlled containers are stopped
if [ -n "$DOCKER_BE" ]; then
    ./docker.sh exec "set -eo pipefail; ./tools/dc down |& tee -a logs/integration.run"
fi

exit $result
