#!/bin/bash

CONTAINER="scion_ci"

. tools/ci/common.sh
[ "$DOCKER" = true ] && args="-d $CONTAINER"

docker inspect "$CONTAINER" &>/dev/null && docker rm -f "$CONTAINER"
./docker.sh build
./tools/ci/setup_container $args
./tools/ci/build "$CONTAINER"
./tools/ci/lint "$CONTAINER"
./tools/ci/unittest "$CONTAINER"
./tools/ci/sphinx "$CONTAINER"

if [ "$DOCKER" = true ]; then
    ./scion.sh stop
    echo "Stop local zookeeper"
    systemctl is-active --quiet zookeeper && sudo service zookeeper stop
    make -C docker/perapp
    rm -rf gen/ gen-cache/ gen-certs/ logs/
fi
./tools/ci/integration $args "$CONTAINER"

tmpdir=$(mktemp -d /tmp/artifacts.XXXXXXX)

./tools/ci/clean_up "$tmpdir" "$CONTAINER"
echo "Artifacts dir: $tmpdir"

docker rm -f "$CONTAINER"
./scion.sh stop
