#!/bin/bash

. tools/ci/common.sh

cntr=${1:-scion_ci}

set -e

[ -n "$DOCKER" ] && mount="-v /run/shm/dispatcher:/run/shm/dispatcher:rw -v /run/shm/sciond:/run/shm/sciond:rw"

docker create --name=$cntr --entrypoint= $mount scion:latest tail -f /dev/null
docker container start $cntr
