#!/bin/bash

set -ex

docker create --name=${1:-scion_ci} --entrypoint= -v "/run/shm/dispatcher:/run/shm/dispatcher:rw" -v "/run/shm/sciond:/run/shm/sciond:rw" scion:latest tail -f /dev/null
docker container start ${1:-scion_ci}
