#!/bin/bash

set -ex

./docker.sh exec "set -eo pipefail; make -f sphinx-doc/Makefile clean html |& tee logs/sphinx.run"
./docker.sh exec "set -eo pipefail; ./scion.sh test |& tee logs/unittests.run"
