- hosts: all
  become: true

  roles:
  - role: dresden-weekly.network-interfaces
    network_manage_devices: no
    network_interfaces:
    - device: enp0s8
      auto: true
      method: static
      address: 169.254.1.2
      netmask: 24
      up:
      - ip route add 169.254.2.0/24 via 169.254.1.1
