# -*- mode: ruby -*-
# vi: set ft=ruby
Vagrant.require_version ">= 1.9.1"

Vagrant.configure(2) do |config|
  config.vm.hostname = "a2"
  config.vm.box = "ubuntu/xenial64"
  # Link between a1 and a2 (endhost)
  config.vm.network "private_network", ip: "169.254.1.2",
      virtualbox__intnet: "gwnet-a", auto_config: false
  config.vm.synced_folder '.', '/vagrant'
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "256"
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python
  SHELL
  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible.yml"
      ansible.galaxy_role_file = "../requirements.yml"
      ansible.galaxy_roles_path = "../roles"
  end
end
