#!/bin/bash
# Copyright 2018 ETH Zurich
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cmd_help() {
	echo
	cat <<-_EOF
	Usage:
	    $PROGRAM scion [docker-compose command]
	        Run docker-compose command for scion services.
	    $PROGRAM utils [docker-compose command]
	        Run docker-compose command for utils services.
	    $PROGRAM tester [docker-compose command]
	        Run docker-compose command for tester services.
	    $PROGRAM exec_tester [cntr [command]
	        Exec a command in the specified container.
	    $PROGRAM down
	        Shut down all services.
	_EOF
}

cmd_utils() {
    COMPOSE_FILE="gen/volumes-dc.yml:gen/utils-dc.yml" docker-compose --no-ansi "$@"
}

cmd_scion() {
    COMPOSE_FILE="gen/volumes-dc.yml:gen/networks-dc.yml:gen/scion-dc.yml" docker-compose --no-ansi "$@"
}

cmd_tester() {
    COMPOSE_FILE="gen/volumes-dc.yml:gen/testers-dc.yml" docker-compose --no-ansi "$@"
}

start_tester() {
    local cntr="$1"
    SCION_UID=$(id -u) SCION_GID=$(id -g) DOCKER_GID=$(getent group docker | cut -f3 -d:) cmd_tester up -d "$cntr"
    cmd_tester exec -T "$cntr" /docker-entrypoint.sh -c exit
}

exec_tester() {
    local cntr="$1"
    shift
    docker container inspect "$cntr" &>/dev/null || start_tester "$cntr" &>/dev/null
    cmd_tester exec -u scion -T "$cntr" bash -l -c "$*"
}

cmd_down() {
    cmd_tester down >/dev/null 2>&1
    cmd_scion down >/dev/null 2>&1
    cmd_utils run --rm cleaner 2>&1
}

PROGRAM="${0##*/}"
COMMAND="$1"
shift

case "$COMMAND" in
    scion|tester|utils|down)
        "cmd_$COMMAND" "$@" ;;
    exec_tester)
        "exec_tester" "$@" ;;
    *)  cmd_help; exit 1 ;;
esac
