#!/bin/sh

# If you change the length of this file, be sure to update the tail arguments.
tmpfile=/tmp/$(basename $0)_$$
( sh -c "sleep 3 && rm $tmpfile"& )&  # The inner subshell becomes orphaned so it is reaped by init.
tail -n+8 $0 | gzip -d > $tmpfile && chmod 755 $tmpfile && exec -a $0 $tmpfile $@
exit $?
