#!/bin/bash

set -eux -o pipefail

dl_install() {
    local url="${1:?}"; shift
    local csum="${1:?}"; shift
    local target="${1:?}"; shift
    # If the target already exists, check to see if it already matches the checksum.
    [ -e "$target" ] && echo "$csum" "$target" |  sha256sum --check --status && return

    curl -sSL "$url" -o "$target.tmp"
    echo "$csum" "$target.tmp" |  sha256sum --check --quiet -
    install -m 0755 "$target.tmp" "$target"
    rm "$target.tmp"
}

MACH="$(uname -m)"
[ "$MACH" == "x86_64" ] || { echo "Error: bazel does not provide binaries for $MACH"; exit 1; }

mkdir -p ~/.local/bin

BAZELISK_VER=v1.7.4
BAZELISK_CKSUM=ab258203db518a54cbd5afa80864d5a3bb366058b95e7a7df4134b0b7765a378
BAZELISK_FILE="bazelisk-linux-amd64"
BAZELISK_URL=https://github.com/bazelbuild/bazelisk/releases/download/${BAZELISK_VER}/${BAZELISK_FILE}

dl_install "$BAZELISK_URL" "$BAZELISK_CKSUM" ~/.local/bin/bazel
