#!/bin/bash

set -e

[ $(id -u) -eq 0 ] || { echo "Error: this script should be run as root" && exit 1; }

# Install prereqs
DEBIAN_FRONTEND=noninteractive apt-get install -y apt-transport-https ca-certificates curl lsb-release software-properties-common

chksum() {
    echo "${1:?} ${2:?}" | sha256sum --status -c -
}

if [ "$(lsb_release -is)" == "LinuxMint" ]; then
    release=$(grep UBUNTU_CODENAME /etc/os-release | cut -f2 -d=)
fi
release=${release:-$(lsb_release -cs)}

# Add docker apt repo.
if ! grep -Rq "https://download.docker.com/linux/ubuntu" /etc/apt/sources.list.d/; then
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    add-apt-repository "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $release stable"
    apt-get update
fi

# Install docker-ce
DEBIAN_FRONTEND=noninteractive apt-get install -y docker-ce docker-ce-cli containerd.io

# Install docker-compose v2.5.1
case "$(uname -m)" in
    x86_64)
        src=https://github.com/docker/compose/releases/download/v2.5.1/docker-compose-linux-x86_64
        sum=d99de1ea7616f2a4c7914d37674f0650660a5e832be555805a71c0fc377233c9
        file=/usr/libexec/docker/cli-plugins/docker-compose
        ;;
    *)
        echo "ERROR: unsupported architecture '$(uname -m)'"
        exit 1
esac
# If the file doesn't exist, or the checksum fails, (re)download it.
if  [ ! -e "$file" ] || ! chksum $sum $file; then
    curl -sSL "$src" -o "$file"
    chksum $sum $file || { echo "Error: $file doesn't match the expected checksum. ($sum)"; exit 1; }
fi
chmod +x "$file"

# Install docker-compose switch.
curl -fL https://raw.githubusercontent.com/docker/compose-switch/master/install_on_linux.sh | sh
