#!/bin/bash

set -exu

dl_install() {
    local url="${1:?}"; shift
    local csum="${1:?}"; shift
    local target="${1:?}"; shift
    # If the target already exists, check to see if it already matches the checksum.
    [ -e "$target" ] && echo "$csum" "$target" |  sha256sum --check --status && return

    curl -sSL "$url" -o "$target.tmp"
    echo "$csum" "$target.tmp" |  sha256sum --check --quiet -
    install -m 0755 "$target.tmp" "$target"
    rm "$target.tmp"
}

MACH="$(uname -m)"
[ "$MACH" == "x86_64" ] || { echo "Error: bazel does not provide binaries for $MACH"; exit 1; }

mkdir -p ~/bin

BAZEL_VER=3.2.0
BAZEL_CKSUM=db0201df83ae6a9f6c19a9103edaeb6b7ce228040244b90a6e3b1c85da4a2152
BAZEL_FILE="bazel-${BAZEL_VER}-linux-${MACH}"
BAZEL_URL=https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VER}/${BAZEL_FILE}

dl_install "$BAZEL_URL" "$BAZEL_CKSUM" ~/bin/bazel
