#!/bin/bash

FILES=$(find -type f -iname '*.md' | grep -vf tools/md/skipped)
docker run --rm -v ${SCION_PWD:-${PWD}}:/data -v ${SCION_PWD:-${PWD}}/tools/md/mdlintstyle.rb:/style.rb $(docker build -q tools/md) $FILES -s /style.rb
