#!/usr/bin/env python3

# This script converts a version from ./tools/git-version to debian and rpm
# version files that can be consumed by bazel.
# Examples:
# - prefix-v0.8.0-rc1-1-g0aec09a
#   -> scion-utils-deb.version: 0.8.0~rc1~1~g0aec09a
#   -> scion-utils-rpm.version: 0.8.0
#   -> scion-utils-rpm.release: rc1-1-g0aec09a
# - prefix-v0.8.0
#   -> scion-utils-deb.version: 0.8.0
#   -> scion-utils-rpm.version: 0.8.0
#   -> scion-utils-rpm.release: 1

from pathlib import Path
import re
import sys

DEB_VERSION = 'scion-utils-deb.version'
RPM_VERSION = 'scion-utils-rpm.version'
RPM_RELEASE = 'scion-utils-rpm.release'

if len(sys.argv) < 2:
    print('Requires version as first argument')
    sys.exit(1)

for f in [DEB_VERSION, RPM_VERSION, RPM_RELEASE]:
    if Path(f).is_file():
        print('%s exists' % f)
        sys.exit(1)

version = sys.argv[1]
m = re.search(r'\d', version)
if m is None:
    print('Invalid version number: %s' % version)
    sys.exit(1)

version = version[m.start():]
deb_version = version.replace('-', '~')
parts = version.split('-', 1)
rpm_version, rpm_release = parts[0], '1'
if len(parts) > 1:
    rpm_release = parts[1]

Path(DEB_VERSION).write_text(deb_version)
Path(RPM_VERSION).write_text(rpm_version)
Path(RPM_RELEASE).write_text(rpm_release)
