#!/bin/bash

# Check if specific caps are set on file, and if not sets them using sudo.

set -e

[ $# -eq 2 ] || {
    echo "Usage: $0 <cap list> <filename>"
    exit 1
}

CAPS="${1:?}"
shift
FILE="${1:?}"
shift

[ -e "$FILE" ] || { echo "ERROR: file not found: $FILE"; exit 2; }

# Check if capabilities are already set
if ! /sbin/setcap -q -v "$CAPS" "$FILE"; then
    # Only prompt for password if necessary
    sudo -p "setcap $FILE [sudo] password for %p: " true
    sudo /sbin/setcap "$CAPS" "$FILE"
fi
