[general]
id = "sd5-ff00_0_510"
config_dir = "gen/ASff00_0_510"

[trust_db]
connection = "gen-cache/sd5-ff00_0_510.trust.db"

[path_db]
connection = "gen-cache/sd5-ff00_0_510.path.db"

[sd]
address = "127.0.0.139:30255"

[tracing]
enabled = true
debug = true
agent = "172.17.0.1:6831"

[metrics]
prometheus = "127.0.0.139:30455"

[features]

[api]
addr = "127.0.0.139:30955"

[log.console]
level = "debug"
