#!/bin/bash
# Copyright 2018 ETH Zurich
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

. integration/common.sh

opts "$@"
shift $((OPTIND-1))

result=0

run C2S_extn bin/cli_srv_ext_pyintegration -log.console error $DOCKER_ARGS
result=$((result+$?))
run SCMP_error bin/scmp_error_pyintegration -log.console error $DOCKER_ARGS
result=$((result+$?))

exit $result
