#!/bin/bash

#host_acceptance="brA brB brC brD core_brA core_brB core_brC"
host_acceptance="brD"

#for test in ./acceptance/*_acceptance; do
for test in ./acceptance/*_acceptance; do
    name="$(basename ${test%_acceptance})"
    RUN_HOST=n
    for host in $host_acceptance; do
        if [ "$host" = "$name" ]; then
            RUN_HOST=y
        fi
    done
    if [ "$RUN_HOST" = "y" ]; then
        echo "- label: Acceptance - $name"
        echo "  env:"
        echo "    ACCEPTANCE_ARTIFACTS: \$SCION_MOUNT/logs/acceptance"
        echo "    DOCKER_ARGS: \"-e ACCEPTANCE_ARTIFACTS=logs/acceptance --privileged --network=host -h $HOSTNAME\""
        echo "  command:"
        echo "  - $BASE/scripts/all_images pull"
        echo "  - $BASE/steps/host_acceptance $test"
    else
        continue
        echo "  env:"
        echo "    DOCKER_ARGS: \"-e ACCEPTANCE_ARTIFACTS=logs/acceptance --network=host -h $HOSTNAME\""
        echo "  command:"
        echo "  - $BASE/scripts/all_images pull"
        echo "  - $BASE/run_step run_acceptance $test"
    fi
    echo "  timeout_in_minutes: 10"
    echo "  artifact_paths:"
    echo "  - \"artifacts.out/**/*\""
done
