- label: "Perapp images :docker: :bazel:"
  command:
  - $BASE/scripts/registry_login
  - echo "$(date -u +"%F %T.%6N%z") Pull scion image"
  - docker pull $SCION_IMG
  - echo "$(date -u +"%F %T.%6N%z") Tag scion image"
  # docker.sh tester depends on scion:latest (needs to be tagged)
  - docker tag $SCION_IMG scion:latest
  - echo "$(date -u +"%F %T.%6N%z") Build perapp images"
  - ./docker.sh run -c "mkdir docker/_build && touch docker/_build/scion.stamp && make -C docker/perapp apps"
  - echo "$(date -u +"%F %T.%6N%z") Build tester image"
  - ./docker.sh tester
  - $BASE/scripts/all_images push
  - echo "$(date -u +"%F %T.%6N%z") All images pushed"
  artifact_paths:
    - "artifacts.out/**/*"
  retry:
    automatic:
      exit_status: 255
  timeout_in_minutes: 10
