- label: "Perapp images :docker: :bazel:"
  command:
  - echo "$(date -u +"%F %T.%6N%z") Pull scion image"
  - docker pull $SCION_IMG
  - echo "$(date -u +"%F %T.%6N%z") Tag scion image"
  # docker.sh tester depends on scion:latest (needs to be tagged)
  - docker tag $SCION_IMG scion:latest
  - echo "$(date -u +"%F %T.%6N%z") Build perapp images"
  - docker run -e  BAZEL_REMOTE_S3_BUCKET=buildkite-bazel-cache -e BAZEL_REMOTE_S3_ENDPOINT=s3.eu-central-1.amazonaws.com -e BAZEL_REMOTE_S3_ACCESS_KEY_ID=$BAZEL_REMOTE_S3_ACCESS_KEY_ID -e BAZEL_REMOTE_S3_SECRET_ACCESS_KEY=$BAZEL_REMOTE_S3_SECRET_ACCESS_KEY --net=host -d buchgr/bazel-remote-cache
  - DOCKER_ARGS="--network host" ./docker.sh run -c "mkdir docker/_build && touch docker/_build/scion.stamp && make -C docker/perapp app_builder apps"
  - echo "$(date -u +"%F %T.%6N%z") Build tester image"
  - ./docker.sh tester
  - $BASE/scripts/all_images push
  - echo "$(date -u +"%F %T.%6N%z") All images pushed"
  artifact_paths:
    - "artifacts.out/**/*"
  retry:
    automatic:
      - exit_status: -1  # Agent was lost
      - exit_status: 255 # Forced agent shutdown
  timeout_in_minutes: 10
