- label: "Perapp images :docker: :bazel:"
  command:
  - $BASE/scripts/registry_login
  - docker pull $SCION_IMG
  # docker.sh tester depends on scion:latest (needs to be tagged)
  - docker tag $SCION_IMG scion:latest
  - ./docker.sh run -c "mkdir docker/_build && touch docker/_build/scion.stamp && make -C docker/perapp apps"
  - ./docker.sh tester
  - $BASE/scripts/all_images push
  retry:
    automatic:
      exit_status: 255
  timeout_in_minutes: 10
