- label: Lint
  command: SCION_IMG="$SCION_BUILD_IMG" $BASE/run_step lint
  artifact_paths:
    - "artifacts.out/**/*"
  retry:
    automatic:
      exit_status: 255
  timeout_in_minutes: 10
- label: Build code and push "$SCION_IMG"
  command:
  - $BASE/scripts/registry_login
  - docker pull $SCION_BUILD_IMG
  - docker tag $SCION_BUILD_IMG scion:latest
  - mkdir docker/_build && touch docker/_build/scion.stamp
  - make -C docker/perapp app_builder
  - docker tag scion_app_builder "$SCION_IMG"
  - docker push $SCION_IMG
  artifact_paths:
    - "artifacts.out/**/*"
  retry:
    automatic:
      exit_status: 255
  timeout_in_minutes: 10
- wait
