- label: Build perapp images
  command:
  - docker pull $SCION_IMG
  - mkdir docker/_build && touch docker/_build/scion.stamp
  - make -C docker/perapp apps
- wait
- label: Push perapp images
  command:
  - $BASE/all_images push
- wait
