- label: Build and push perapp images
  command:
  - $BASE/scripts/registry_login
  - docker pull $SCION_IMG
  - docker tag $SCION_IMG scion:latest
  - mkdir docker/_build && touch docker/_build/scion.stamp
  - make -C docker/perapp apps
  - ./docker.sh tester
  - $BASE/scripts/all_images push
  retry:
    automatic:
      exit_status: 255
  timeout_in_minutes: 10
- wait
