- wait
- label: Build app images
  command:
    - mkdir docker/_build && touch docker/_build/scion.stamp
    - make -C docker/perapp
  branches: "v*.*.*"
- wait
- label: Push images
  command:
  - echo \$DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin
  - ./docker/perapp/publish "$BUILDKITE_TAG"
  branches: "v*.*.*"
