- label: "Integration - docker :docker:"
  command:
  - $BASE/scripts/all_images pull
  - $BASE/run_step integration -d -a
  retry:
    automatic:
      exit_status: -1
  timeout_in_minutes: 10
  artifact_paths:
  - "artifacts.out/**/*"
