#!/bin/bash

$BASE/scripts/clean_env
echo "Running: ${1:?}"

# Pull CI image and start it
docker pull $SCION_IMG &>/dev/null
./docker.sh start
# copy binaries from container
docker cp $SCION_CNTR:home/scion/go/src/github.com/scionproto/scion/bin . || true
./docker.sh stop

# Run test
$1/test setup
res=$?
$1/test run
res=$((res+$?))
$1/test teardown
res=$((res+$?))

# Clean
$BASE/scripts/clean_env
res=$((res+$?))
exit $res
