#!/bin/bash

run_wrapper() {
    PHASE=${1:?}
    shift
    if $@; then
        echo "$PHASE successful"
        return 0
    else
        echo "$PHASE failed"
        return 1
    fi
}

$BASE/scripts/clean_env
echo "Running: ${1:?}"

# Pull CI image and start it
docker pull $SCION_IMG &>/dev/null
mkdir -p $SCION_MOUNT
mkdir -p $ACCEPTANCE_ARTIFACTS
./docker.sh start

# Run test
run_wrapper "SETUP" "$1/test setup &>> $ACCEPTANCE_ARTIFACTS/setup.out"
res=$?
run_wrapper "RUN" "./docker.sh exec $1/test run &>> \$ACCEPTANCE_ARTIFACTS/run.out"
res=$((res+$?))
run_wrapper "TEARDOWN" "$1/test teardown &>> $ACCEPTANCE_ARTIFACTS/teardown.out"
res=$((res+$?))

# Pack logs and stop everything
cp -r logs "$SCION_MOUNT"
res=$((res+$?))
$BASE/scripts/pack_logs
res=$((res+$?))
./docker.sh stop
res=$((res+$?))
$BASE/scripts/clean_env
res=$((res+$?))
rm -r $SCION_MOUNT
exit $res
