#!/bin/bash

set -e

TESTS="revocation go_integration go_infra"

run_test() {
    echo "- label: Integration - ${1:?}"
    echo "  command:"
    echo "  - $BASE/run_step integration $1"
    echo "  timeout_in_minutes: 10"
    echo "  artifact_paths:"
    echo "  - \"artifacts.out/**/*\""
}

if [ "$RUN_ALL_TESTS" = "y" ]; then
    run_test "py_integration"
fi

for test in $TESTS; do
    run_test "$test"
done
