#!/bin/bash

set -e

TESTS="revocation go_integration"

run_test() {
    if [-z "$2" ]; then
        echo "- label: Integration - ${1:?}"
    else
        echo "- label: Integration - ${1:?} Mode=$2"
    fi
    echo "  command:"
    echo "  - $BASE/run_step integration $1 $2"
    echo "  timeout_in_minutes: 10"
    echo "  parallelism: 10"
    echo "  artifact_paths:"
    echo "  - \"artifacts.out/**/*\""
}

MODES="core-core noncore-localcore noncore-core noncore-noncore"

for mode in $MODES; do
    run_test "e2e_integration" "$mode"
done

if [ "$RUN_ALL_TESTS" = "y" ]; then
    run_test "py_ext_integration"
    run_test "py_scmp_integration"
fi

for test in $TESTS; do
    run_test "$test"
done
