#!/bin/bash

set -e

TESTS="revocation go_integration"

run_test() {
    if [ -z "$2" ]; then
        echo "- label: Integration - ${1:?}"
    else
        echo "- label: Integration - ${1:?} mode=$2"
    fi
    echo "  command:"
    echo "  - $BASE/run_step integration $1 $2"
    echo "  retry:"
    echo "    automatic:"
    echo "      - exit_status: -1"  # Agent was lost
    echo "      - exit_status: 255" # Forced agent shutdown
    echo "  timeout_in_minutes: 10"
    echo "  artifact_paths:"
    echo "  - \"artifacts.out/**/*\""
}

MODES="core-core noncore-localcore noncore-core noncore-noncore"

if [ "$RUN_ALL_TESTS" = "y" ]; then
    for mode in $MODES; do
        run_test "e2e_integration" "$mode"
    done
fi

for test in $TESTS; do
    run_test "$test"
done
