- label: "Scion image :docker: "
  command:
    - $BASE/scripts/build_scion_img
    - make -C docker/perapp app_builder
    - docker tag scion_app_builder "$SCION_IMG"
    - docker push $SCION_IMG
  artifact_paths:
    - "artifacts.out/**/*"
  retry:
    automatic:
      exit_status: -1
  timeout_in_minutes: 10
- wait
