- label: Build and push scion image
  command:
      - $BASE/scripts/build_scion_img
      - docker tag scion $SCION_BUILD_IMG
      - $BASE/scripts/registry_login
      - docker push $SCION_BUILD_IMG
  retry:
    automatic:
      exit_status: 255
  timeout_in_minutes: 10
- wait
