- label: "Scion image :docker: "
  command:
    - $BASE/scripts/build_scion_img
    - docker run -e  BAZEL_REMOTE_S3_BUCKET=buildkite-bazel-cache -e BAZEL_REMOTE_S3_ENDPOINT=s3.eu-central-1.amazonaws.com -e BAZEL_REMOTE_S3_ACCESS_KEY_ID=$BAZEL_REMOTE_S3_ACCESS_KEY_ID -e BAZEL_REMOTE_S3_SECRET_ACCESS_KEY=$BAZEL_REMOTE_S3_SECRET_ACCESS_KEY --net=host -d buchgr/bazel-remote-cache
    - make -C docker/perapp app_builder
    - docker tag scion_app_builder "$SCION_IMG"
    - docker push $SCION_IMG
  artifact_paths:
    - "artifacts.out/**/*"
  retry:
    automatic:
      - exit_status: -1  # Agent was lost
      - exit_status: 255 # Forced agent shutdown
  timeout_in_minutes: 10
- wait
