- label: "Check generated go/proto files in git"
  command: $BASE/run_step checkgogen
  timeout_in_minutes: 1
- label: "Unit tests :bazel:"
  command: $BASE/run_step test
  artifact_paths:
      - "artifacts.out/**/*"
  retry:
    automatic:
      exit_status: 255
  timeout_in_minutes: 10
- label: "Lint :bazel:"
  command: $BASE/run_step lint
  artifact_paths:
    - "artifacts.out/**/*"
  retry:
    automatic:
      exit_status: 255
  timeout_in_minutes: 10
