- label: "Check generated go/proto files in git"
  command: $BASE/run_step checkgogen
  retry:
    automatic:
      - exit_status: -1  # Agent was lost
      - exit_status: 255 # Forced agent shutdown
  timeout_in_minutes: 10
- label: "Unit tests :bazel:"
  command: $BASE/run_step test
  artifact_paths:
      - "artifacts.out/**/*"
  retry:
    automatic:
      - exit_status: -1  # Agent was lost
      - exit_status: 255 # Forced agent shutdown
  timeout_in_minutes: 10
- label: "Lint :bazel:"
  command: $BASE/run_step lint
  artifact_paths:
    - "artifacts.out/**/*"
  retry:
    automatic:
      - exit_status: -1  # Agent was lost
      - exit_status: 255 # Forced agent shutdown
  timeout_in_minutes: 10
