#!/bin/bash

# Whenever the BR's internal address in the topology file of a PS server is
# changed, if the PS process receives a SIGHUP it will reload the config and
# use the new internal address as next-hop when doing path segment
# synchronization with other core PSes.

. acceptance/common.sh

TEST_NAME="topo_ps_reloads_br"
TEST_TOPOLOGY="topology/Tiny.topo"

SRC_IA=${SRC_IA:-1-ff00:0:112}
SRC_IA_FILE="$(ia_file $SRC_IA)"
SRC_AS_FILE="$(as_file $SRC_IA)"
DST_IA=${DST_IA:-1-ff00:0:111}

test_setup() {
    set -e
    ./scion.sh topology zkclean -c $TEST_TOPOLOGY -d -sd=go -ps=go
    for sd in gen/ISD1/*/ps*/psconfig.toml; do
        sed -i 's/Level = .*$/Level = "trace"/g' "$sd"
        sed -i '/\[logging\.file\]/a FlushInterval = 1' "$sd"
    done
    ./scion.sh run nobuild
    ./tools/dc start tester_$SRC_IA_FILE
}

test_run() {
    set -e
    local topo_file="gen/ISD1/AS$SRC_AS_FILE/ps$SRC_IA_FILE-1/topology.json"
    jq '.BorderRouters[].InternalAddrs.IPv4.PublicOverlay = {Addr: "127.42.42.42", OverlayPort: 39999}' $topo_file | sponge $topo_file
    ./tools/dc dc kill -s HUP scion_ps"$SRC_IA_FILE"-1
    sleep 6
    ./tools/dc exec_tester $SRC_IA_FILE bin/showpaths -srcIA $SRC_IA -dstIA $DST_IA -sciondFromIA || true
    sleep 2
    grep -q "NextHop=\[127\.42\.42\.42\]:39999" "logs/ps$SRC_IA_FILE-1.log" || \
        { echo "PS path request with next-hop 127.42.42.42:39999 not found in logs"; return 1; }
}

test_teardown() {
    ./tools/dc down
}

print_help() {
    echo
	cat <<-_EOF
	    $PROGRAM name
	        return the name of this test
	    $PROGRAM setup
	        execute only the setup phase.
	    $PROGRAM run
	        execute only the run phase.
	    $PROGRAM teardown
	        execute only the teardown phase.
	_EOF
}

PROGRAM=`basename "$0"`
COMMAND="$1"

case "$COMMAND" in
    name)
        echo $TEST_NAME ;;
    setup|run|teardown)
        "test_$COMMAND" ;;
    *) print_help; exit 1 ;;
esac

