// Copyright 2026 SCION Association
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestProcess(t *testing.T) {
	files := map[string]string{
		"current.go":   "// Copyright 2026 SCION Association\n" + licenseBlock,
		"generated.go": "// Code generated by MockGen. DO NOT EDIT.\n\npackage main\n",
		"stale.go":     "// Copyright 2025 SCION Association\n" + licenseBlock,
	}
	for _, write := range []bool{false, true} {
		t.Run(fmt.Sprintf("write=%t", write), func(t *testing.T) {
			dir := t.TempDir()
			for name, content := range files {
				path := filepath.Join(dir, name)
				require.NoError(t, os.WriteFile(path, []byte(content), 0o644))
			}

			rep, err := process(dir, []string{"current.go", "generated.go", "stale.go"},
				"SCION Association", 2026, write)
			require.NoError(t, err)

			stale, summary := files["stale.go"],
				"would update 1 of 3 Go files changed since the merge base with "+
					"upstream/master\nrun `copyright -w` to write the patch\n"
			if write {
				stale, summary = "// Copyright 2026 SCION Association\n"+licenseBlock,
					"updated 1 of 3 Go files changed since the merge base with upstream/master\n"
			}
			for name, want := range map[string]string{
				"current.go":   files["current.go"],
				"generated.go": files["generated.go"],
				"stale.go":     stale,
			} {
				got, err := os.ReadFile(filepath.Join(dir, name))
				require.NoError(t, err)
				assert.Equal(t, want, string(got), name)
			}

			var patch strings.Builder
			for _, ch := range rep.changed {
				writePatch(&patch, ch)
			}
			assert.Equal(t, `diff --git a/stale.go b/stale.go
--- a/stale.go
+++ b/stale.go
@@ -1,4 +1,4 @@
-// Copyright 2025 SCION Association
+// Copyright 2026 SCION Association
 //
 // Licensed under the Apache License, Version 2.0 (the "License");
 // you may not use this file except in compliance with the License.
`, patch.String())

			var report strings.Builder
			rep.print(&report, "upstream/master", "copyright -w")
			assert.Equal(t,
				"left alone, generated file (1):\n    generated.go\n\n"+summary,
				report.String())
		})
	}
}

func TestPrintWithoutWriteCommand(t *testing.T) {
	rep := &report{files: 1, changed: []change{{file: "f.go"}}}
	var b strings.Builder
	rep.print(&b, "upstream/master", "")
	assert.Equal(t,
		"would update 1 of 1 Go file changed since the merge base with upstream/master\n"+
			"rerun with -w to write the patch\n",
		b.String())
}

func TestCheckAffiliation(t *testing.T) {
	org, err := checkAffiliation("  SCION Association ")
	require.NoError(t, err)
	assert.Equal(t, "SCION Association", org)

	for _, name := range []string{"", "  ", "Some Corp, Inc.", "Some\nCorp"} {
		_, err := checkAffiliation(name)
		assert.Error(t, err, "%q", name)
	}
}
